%% demo.m — Recreate 24_Dropbox_technology__HCCS_PrinterInstall_20180206_r0 via Mat2Ppt public API
% Source: 24_Dropbox_technology__HCCS_PrinterInstall_20180206_r0.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525927), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638880), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(790575), mat2ppt.util.Emu(1122363), mat2ppt.util.Emu(10858499), mat2ppt.util.Emu(2387600));
sp.text_frame().text = 'HCCS Network Printer Installation';

% Subtitle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(3602038), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(1655762));
sp.text_frame().text = 'Douglas CoombsFebruary 6, 2018, Rev. 0';


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525927), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638880), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Overview';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Description of Current PrintersPrinter Installation Instructions';


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525927), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638880), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Current Printers';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(188121), mat2ppt.util.Emu(1222110), mat2ppt.util.Emu(11651454), mat2ppt.util.Emu(4954853));
sp.text_frame().text = 'Teacher’s LoungeColor HP Wireless (Model #): 192.168.1.57HP Color Laserjet 3500: 192.168.1.58Mrs. Teeter’s 1/2nd ClassroomBW: HP Laserjet 4050N: IP Address TBD (ideally 192.168.1.59)Outside Mrs. Sanchez ClassroomBW: HP Laserjet 4100: 192.168.1.97';


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525927), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638880), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(486137), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10058400), mat2ppt.util.Emu(659559));
sp.text_frame().text = 'Installing a Network Printer Using TCP/IP (1/4)';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(188121), mat2ppt.util.Emu(1222110), mat2ppt.util.Emu(11651454), mat2ppt.util.Emu(4954853));
sp.text_frame().text = 'Overview of stepsControl Panel -> Devices and printersAdd a printer Add a Local PrinterCreate a New PortSelect Type of Port: Standard TCP/IP PortType IP Address in Hostname or IP address: 192.168.1.##Installing the Printer Driver Add Printer -> Have DiskPrint Test Page';


%% ===== Slide 5 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525927), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638880), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(535021), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10032665), mat2ppt.util.Emu(659559));
sp.text_frame().text = 'Installing a Network Printer Using TCP/IP (2/4)';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(188121), mat2ppt.util.Emu(1222110), mat2ppt.util.Emu(11651454), mat2ppt.util.Emu(4954853));
sp.text_frame().text = 'Control Panel -> Devices and printersAdd a printer Add a Local Printer';

% picture Picture 3
img = fullfile(assets, 'image4.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4442569), mat2ppt.util.Emu(2920610), mat2ppt.util.Emu(6390009), mat2ppt.util.Emu(4244119));
end

% Rectangle 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(5306752), mat2ppt.util.Emu(3566567), mat2ppt.util.Emu(647700), mat2ppt.util.Emu(202181));


%% ===== Slide 6 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525927), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638880), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(535021), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10090538), mat2ppt.util.Emu(659559));
sp.text_frame().text = 'Installing a Network Printer Using TCP/IP (3/4)';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(188121), mat2ppt.util.Emu(1222110), mat2ppt.util.Emu(11651454), mat2ppt.util.Emu(4954853));
sp.text_frame().text = 'Add a Local PrinterCreate a New PortSelect Type of Port: Standard TCP/IP Port';

% picture Picture 4
img = fullfile(assets, 'image5.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1829470), mat2ppt.util.Emu(2597969), mat2ppt.util.Emu(4593021), mat2ppt.util.Emu(3364315));
end

% picture Picture 5
img = fullfile(assets, 'image6.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6539564), mat2ppt.util.Emu(1994356), mat2ppt.util.Emu(5417084), mat2ppt.util.Emu(3967928));
end


%% ===== Slide 7 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525927), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638880), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(535021), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10021090), mat2ppt.util.Emu(659559));
sp.text_frame().text = 'Installing a Network Printer Using TCP/IP (4/4)';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(188121), mat2ppt.util.Emu(1222110), mat2ppt.util.Emu(11651454), mat2ppt.util.Emu(4954853));
sp.text_frame().text = 'Type IP Address in Hostname or IP address: 192.168.1.##Installing the Printer Driver Add Printer -> Have Disk';

% picture Picture 6
img = fullfile(assets, 'image7.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1452793), mat2ppt.util.Emu(2338086), mat2ppt.util.Emu(4994305), mat2ppt.util.Emu(3658249));
end

% picture Picture 7
img = fullfile(assets, 'image8.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6744113), mat2ppt.util.Emu(2338086), mat2ppt.util.Emu(4994305), mat2ppt.util.Emu(3658249));
end

% Rectangle 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(10556111), mat2ppt.util.Emu(5023414), mat2ppt.util.Emu(983848), mat2ppt.util.Emu(289366));

% Rectangle 10
sp = sh.add_shape('rect', mat2ppt.util.Emu(3221619), mat2ppt.util.Emu(3981690), mat2ppt.util.Emu(3028709), mat2ppt.util.Emu(212527));

% Rectangle 11
sp = sh.add_shape('rect', mat2ppt.util.Emu(3221618), mat2ppt.util.Emu(3692323), mat2ppt.util.Emu(3028709), mat2ppt.util.Emu(190653));


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide2 sp used title-area default geom: Title 1
% GAP: slide2 sp used title-area default geom: Content Placeholder 2
% GAP: slide3 sp used title-area default geom: Title 1
