classdef MSO_AUTO_SIZE
%MSO_AUTO_SIZE  Enumeration (BaseEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/text.py::MSO_AUTO_SIZE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        NONE = mat2ppt.enum.BaseEnum("NONE", 0)
        SHAPE_TO_FIT_TEXT = mat2ppt.enum.BaseEnum("SHAPE_TO_FIT_TEXT", 1)
        TEXT_TO_FIT_SHAPE = mat2ppt.enum.BaseEnum("TEXT_TO_FIT_SHAPE", 2)
        MIXED = mat2ppt.enum.BaseEnum("MIXED", -2)
    end
end
