classdef MSO_COLOR_TYPE
%MSO_COLOR_TYPE  Enumeration (BaseEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/dml.py::MSO_COLOR_TYPE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        RGB = mat2ppt.enum.BaseEnum("RGB", 1)
        SCHEME = mat2ppt.enum.BaseEnum("SCHEME", 2)
        HSL = mat2ppt.enum.BaseEnum("HSL", 101)
        PRESET = mat2ppt.enum.BaseEnum("PRESET", 102)
        SCRGB = mat2ppt.enum.BaseEnum("SCRGB", 103)
        SYSTEM = mat2ppt.enum.BaseEnum("SYSTEM", 104)
    end
end
