classdef MSO_TEXT_UNDERLINE_TYPE
%MSO_TEXT_UNDERLINE_TYPE  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/text.py::MSO_TEXT_UNDERLINE_TYPE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        NONE = mat2ppt.enum.BaseXmlEnum("NONE", 0, "none")
        DASH_HEAVY_LINE = mat2ppt.enum.BaseXmlEnum("DASH_HEAVY_LINE", 8, "dashHeavy")
        DASH_LINE = mat2ppt.enum.BaseXmlEnum("DASH_LINE", 7, "dash")
        DASH_LONG_HEAVY_LINE = mat2ppt.enum.BaseXmlEnum("DASH_LONG_HEAVY_LINE", 10, "dashLongHeavy")
        DASH_LONG_LINE = mat2ppt.enum.BaseXmlEnum("DASH_LONG_LINE", 9, "dashLong")
        DOT_DASH_HEAVY_LINE = mat2ppt.enum.BaseXmlEnum("DOT_DASH_HEAVY_LINE", 12, "dotDashHeavy")
        DOT_DASH_LINE = mat2ppt.enum.BaseXmlEnum("DOT_DASH_LINE", 11, "dotDash")
        DOT_DOT_DASH_HEAVY_LINE = mat2ppt.enum.BaseXmlEnum("DOT_DOT_DASH_HEAVY_LINE", 14, "dotDotDashHeavy")
        DOT_DOT_DASH_LINE = mat2ppt.enum.BaseXmlEnum("DOT_DOT_DASH_LINE", 13, "dotDotDash")
        DOTTED_HEAVY_LINE = mat2ppt.enum.BaseXmlEnum("DOTTED_HEAVY_LINE", 6, "dottedHeavy")
        DOTTED_LINE = mat2ppt.enum.BaseXmlEnum("DOTTED_LINE", 5, "dotted")
        DOUBLE_LINE = mat2ppt.enum.BaseXmlEnum("DOUBLE_LINE", 3, "dbl")
        HEAVY_LINE = mat2ppt.enum.BaseXmlEnum("HEAVY_LINE", 4, "heavy")
        SINGLE_LINE = mat2ppt.enum.BaseXmlEnum("SINGLE_LINE", 2, "sng")
        WAVY_DOUBLE_LINE = mat2ppt.enum.BaseXmlEnum("WAVY_DOUBLE_LINE", 17, "wavyDbl")
        WAVY_HEAVY_LINE = mat2ppt.enum.BaseXmlEnum("WAVY_HEAVY_LINE", 16, "wavyHeavy")
        WAVY_LINE = mat2ppt.enum.BaseXmlEnum("WAVY_LINE", 15, "wavy")
        WORDS = mat2ppt.enum.BaseXmlEnum("WORDS", 1, "words")
        MIXED = mat2ppt.enum.BaseXmlEnum("MIXED", -2, "")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "MSO_TEXT_UNDERLINE_TYPE has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.MSO_TEXT_UNDERLINE_TYPE);
            for i = 1:numel(names)
                mem = mat2ppt.enum.MSO_TEXT_UNDERLINE_TYPE.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "MSO_TEXT_UNDERLINE_TYPE has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.MSO_TEXT_UNDERLINE_TYPE);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.MSO_TEXT_UNDERLINE_TYPE.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of MSO_TEXT_UNDERLINE_TYPE");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "MSO_TEXT_UNDERLINE_TYPE.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
