classdef MSO_CONNECTOR_TYPE
%MSO_CONNECTOR_TYPE  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/shapes.py::MSO_CONNECTOR_TYPE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        CURVE = mat2ppt.enum.BaseXmlEnum("CURVE", 3, "curvedConnector3")
        ELBOW = mat2ppt.enum.BaseXmlEnum("ELBOW", 2, "bentConnector3")
        STRAIGHT = mat2ppt.enum.BaseXmlEnum("STRAIGHT", 1, "line")
        MIXED = mat2ppt.enum.BaseXmlEnum("MIXED", -2, "")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "MSO_CONNECTOR_TYPE has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.MSO_CONNECTOR_TYPE);
            for i = 1:numel(names)
                mem = mat2ppt.enum.MSO_CONNECTOR_TYPE.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "MSO_CONNECTOR_TYPE has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.MSO_CONNECTOR_TYPE);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.MSO_CONNECTOR_TYPE.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of MSO_CONNECTOR_TYPE");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "MSO_CONNECTOR_TYPE.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
