classdef MSO_LINE_DASH_STYLE
%MSO_LINE_DASH_STYLE  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/dml.py::MSO_LINE_DASH_STYLE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        DASH = mat2ppt.enum.BaseXmlEnum("DASH", 4, "dash")
        DASH_DOT = mat2ppt.enum.BaseXmlEnum("DASH_DOT", 5, "dashDot")
        DASH_DOT_DOT = mat2ppt.enum.BaseXmlEnum("DASH_DOT_DOT", 6, "lgDashDotDot")
        LONG_DASH = mat2ppt.enum.BaseXmlEnum("LONG_DASH", 7, "lgDash")
        LONG_DASH_DOT = mat2ppt.enum.BaseXmlEnum("LONG_DASH_DOT", 8, "lgDashDot")
        ROUND_DOT = mat2ppt.enum.BaseXmlEnum("ROUND_DOT", 3, "sysDot")
        SOLID = mat2ppt.enum.BaseXmlEnum("SOLID", 1, "solid")
        SQUARE_DOT = mat2ppt.enum.BaseXmlEnum("SQUARE_DOT", 2, "sysDash")
        DASH_STYLE_MIXED = mat2ppt.enum.BaseXmlEnum("DASH_STYLE_MIXED", -2, "")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "MSO_LINE_DASH_STYLE has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.MSO_LINE_DASH_STYLE);
            for i = 1:numel(names)
                mem = mat2ppt.enum.MSO_LINE_DASH_STYLE.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "MSO_LINE_DASH_STYLE has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.MSO_LINE_DASH_STYLE);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.MSO_LINE_DASH_STYLE.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of MSO_LINE_DASH_STYLE");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "MSO_LINE_DASH_STYLE.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
