classdef MSO_PATTERN_TYPE
%MSO_PATTERN_TYPE  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/dml.py::MSO_PATTERN_TYPE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        CROSS = mat2ppt.enum.BaseXmlEnum("CROSS", 51, "cross")
        DARK_DOWNWARD_DIAGONAL = mat2ppt.enum.BaseXmlEnum("DARK_DOWNWARD_DIAGONAL", 15, "dkDnDiag")
        DARK_HORIZONTAL = mat2ppt.enum.BaseXmlEnum("DARK_HORIZONTAL", 13, "dkHorz")
        DARK_UPWARD_DIAGONAL = mat2ppt.enum.BaseXmlEnum("DARK_UPWARD_DIAGONAL", 16, "dkUpDiag")
        DARK_VERTICAL = mat2ppt.enum.BaseXmlEnum("DARK_VERTICAL", 14, "dkVert")
        DASHED_DOWNWARD_DIAGONAL = mat2ppt.enum.BaseXmlEnum("DASHED_DOWNWARD_DIAGONAL", 28, "dashDnDiag")
        DASHED_HORIZONTAL = mat2ppt.enum.BaseXmlEnum("DASHED_HORIZONTAL", 32, "dashHorz")
        DASHED_UPWARD_DIAGONAL = mat2ppt.enum.BaseXmlEnum("DASHED_UPWARD_DIAGONAL", 27, "dashUpDiag")
        DASHED_VERTICAL = mat2ppt.enum.BaseXmlEnum("DASHED_VERTICAL", 31, "dashVert")
        DIAGONAL_BRICK = mat2ppt.enum.BaseXmlEnum("DIAGONAL_BRICK", 40, "diagBrick")
        DIAGONAL_CROSS = mat2ppt.enum.BaseXmlEnum("DIAGONAL_CROSS", 54, "diagCross")
        DIVOT = mat2ppt.enum.BaseXmlEnum("DIVOT", 46, "divot")
        DOTTED_DIAMOND = mat2ppt.enum.BaseXmlEnum("DOTTED_DIAMOND", 24, "dotDmnd")
        DOTTED_GRID = mat2ppt.enum.BaseXmlEnum("DOTTED_GRID", 45, "dotGrid")
        DOWNWARD_DIAGONAL = mat2ppt.enum.BaseXmlEnum("DOWNWARD_DIAGONAL", 52, "dnDiag")
        HORIZONTAL = mat2ppt.enum.BaseXmlEnum("HORIZONTAL", 49, "horz")
        HORIZONTAL_BRICK = mat2ppt.enum.BaseXmlEnum("HORIZONTAL_BRICK", 35, "horzBrick")
        LARGE_CHECKER_BOARD = mat2ppt.enum.BaseXmlEnum("LARGE_CHECKER_BOARD", 36, "lgCheck")
        LARGE_CONFETTI = mat2ppt.enum.BaseXmlEnum("LARGE_CONFETTI", 33, "lgConfetti")
        LARGE_GRID = mat2ppt.enum.BaseXmlEnum("LARGE_GRID", 34, "lgGrid")
        LIGHT_DOWNWARD_DIAGONAL = mat2ppt.enum.BaseXmlEnum("LIGHT_DOWNWARD_DIAGONAL", 21, "ltDnDiag")
        LIGHT_HORIZONTAL = mat2ppt.enum.BaseXmlEnum("LIGHT_HORIZONTAL", 19, "ltHorz")
        LIGHT_UPWARD_DIAGONAL = mat2ppt.enum.BaseXmlEnum("LIGHT_UPWARD_DIAGONAL", 22, "ltUpDiag")
        LIGHT_VERTICAL = mat2ppt.enum.BaseXmlEnum("LIGHT_VERTICAL", 20, "ltVert")
        NARROW_HORIZONTAL = mat2ppt.enum.BaseXmlEnum("NARROW_HORIZONTAL", 30, "narHorz")
        NARROW_VERTICAL = mat2ppt.enum.BaseXmlEnum("NARROW_VERTICAL", 29, "narVert")
        OUTLINED_DIAMOND = mat2ppt.enum.BaseXmlEnum("OUTLINED_DIAMOND", 41, "openDmnd")
        PERCENT_10 = mat2ppt.enum.BaseXmlEnum("PERCENT_10", 2, "pct10")
        PERCENT_20 = mat2ppt.enum.BaseXmlEnum("PERCENT_20", 3, "pct20")
        PERCENT_25 = mat2ppt.enum.BaseXmlEnum("PERCENT_25", 4, "pct25")
        PERCENT_30 = mat2ppt.enum.BaseXmlEnum("PERCENT_30", 5, "pct30")
        ERCENT_40 = mat2ppt.enum.BaseXmlEnum("ERCENT_40", 6, "pct40")
        PERCENT_5 = mat2ppt.enum.BaseXmlEnum("PERCENT_5", 1, "pct5")
        PERCENT_50 = mat2ppt.enum.BaseXmlEnum("PERCENT_50", 7, "pct50")
        PERCENT_60 = mat2ppt.enum.BaseXmlEnum("PERCENT_60", 8, "pct60")
        PERCENT_70 = mat2ppt.enum.BaseXmlEnum("PERCENT_70", 9, "pct70")
        PERCENT_75 = mat2ppt.enum.BaseXmlEnum("PERCENT_75", 10, "pct75")
        PERCENT_80 = mat2ppt.enum.BaseXmlEnum("PERCENT_80", 11, "pct80")
        PERCENT_90 = mat2ppt.enum.BaseXmlEnum("PERCENT_90", 12, "pct90")
        PLAID = mat2ppt.enum.BaseXmlEnum("PLAID", 42, "plaid")
        SHINGLE = mat2ppt.enum.BaseXmlEnum("SHINGLE", 47, "shingle")
        SMALL_CHECKER_BOARD = mat2ppt.enum.BaseXmlEnum("SMALL_CHECKER_BOARD", 17, "smCheck")
        SMALL_CONFETTI = mat2ppt.enum.BaseXmlEnum("SMALL_CONFETTI", 37, "smConfetti")
        SMALL_GRID = mat2ppt.enum.BaseXmlEnum("SMALL_GRID", 23, "smGrid")
        SOLID_DIAMOND = mat2ppt.enum.BaseXmlEnum("SOLID_DIAMOND", 39, "solidDmnd")
        SPHERE = mat2ppt.enum.BaseXmlEnum("SPHERE", 43, "sphere")
        TRELLIS = mat2ppt.enum.BaseXmlEnum("TRELLIS", 18, "trellis")
        UPWARD_DIAGONAL = mat2ppt.enum.BaseXmlEnum("UPWARD_DIAGONAL", 53, "upDiag")
        VERTICAL = mat2ppt.enum.BaseXmlEnum("VERTICAL", 50, "vert")
        WAVE = mat2ppt.enum.BaseXmlEnum("WAVE", 48, "wave")
        WEAVE = mat2ppt.enum.BaseXmlEnum("WEAVE", 44, "weave")
        WIDE_DOWNWARD_DIAGONAL = mat2ppt.enum.BaseXmlEnum("WIDE_DOWNWARD_DIAGONAL", 25, "wdDnDiag")
        WIDE_UPWARD_DIAGONAL = mat2ppt.enum.BaseXmlEnum("WIDE_UPWARD_DIAGONAL", 26, "wdUpDiag")
        ZIG_ZAG = mat2ppt.enum.BaseXmlEnum("ZIG_ZAG", 38, "zigZag")
        MIXED = mat2ppt.enum.BaseXmlEnum("MIXED", -2, "")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "MSO_PATTERN_TYPE has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.MSO_PATTERN_TYPE);
            for i = 1:numel(names)
                mem = mat2ppt.enum.MSO_PATTERN_TYPE.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "MSO_PATTERN_TYPE has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.MSO_PATTERN_TYPE);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.MSO_PATTERN_TYPE.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of MSO_PATTERN_TYPE");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "MSO_PATTERN_TYPE.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
