classdef MSO_SHAPE_TYPE
%MSO_SHAPE_TYPE  Enumeration (BaseEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/shapes.py::MSO_SHAPE_TYPE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        AUTO_SHAPE = mat2ppt.enum.BaseEnum("AUTO_SHAPE", 1)
        CALLOUT = mat2ppt.enum.BaseEnum("CALLOUT", 2)
        CANVAS = mat2ppt.enum.BaseEnum("CANVAS", 20)
        CHART = mat2ppt.enum.BaseEnum("CHART", 3)
        COMMENT = mat2ppt.enum.BaseEnum("COMMENT", 4)
        DIAGRAM = mat2ppt.enum.BaseEnum("DIAGRAM", 21)
        EMBEDDED_OLE_OBJECT = mat2ppt.enum.BaseEnum("EMBEDDED_OLE_OBJECT", 7)
        FORM_CONTROL = mat2ppt.enum.BaseEnum("FORM_CONTROL", 8)
        FREEFORM = mat2ppt.enum.BaseEnum("FREEFORM", 5)
        GROUP = mat2ppt.enum.BaseEnum("GROUP", 6)
        IGX_GRAPHIC = mat2ppt.enum.BaseEnum("IGX_GRAPHIC", 24)
        INK = mat2ppt.enum.BaseEnum("INK", 22)
        INK_COMMENT = mat2ppt.enum.BaseEnum("INK_COMMENT", 23)
        LINE = mat2ppt.enum.BaseEnum("LINE", 9)
        LINKED_OLE_OBJECT = mat2ppt.enum.BaseEnum("LINKED_OLE_OBJECT", 10)
        LINKED_PICTURE = mat2ppt.enum.BaseEnum("LINKED_PICTURE", 11)
        MEDIA = mat2ppt.enum.BaseEnum("MEDIA", 16)
        OLE_CONTROL_OBJECT = mat2ppt.enum.BaseEnum("OLE_CONTROL_OBJECT", 12)
        PICTURE = mat2ppt.enum.BaseEnum("PICTURE", 13)
        PLACEHOLDER = mat2ppt.enum.BaseEnum("PLACEHOLDER", 14)
        SCRIPT_ANCHOR = mat2ppt.enum.BaseEnum("SCRIPT_ANCHOR", 18)
        TABLE = mat2ppt.enum.BaseEnum("TABLE", 19)
        TEXT_BOX = mat2ppt.enum.BaseEnum("TEXT_BOX", 17)
        TEXT_EFFECT = mat2ppt.enum.BaseEnum("TEXT_EFFECT", 15)
        WEB_VIDEO = mat2ppt.enum.BaseEnum("WEB_VIDEO", 26)
        MIXED = mat2ppt.enum.BaseEnum("MIXED", -2)
    end
end
