classdef MSO_THEME_COLOR_INDEX
%MSO_THEME_COLOR_INDEX  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/dml.py::MSO_THEME_COLOR_INDEX
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        NOT_THEME_COLOR = mat2ppt.enum.BaseXmlEnum("NOT_THEME_COLOR", 0, "")
        ACCENT_1 = mat2ppt.enum.BaseXmlEnum("ACCENT_1", 5, "accent1")
        ACCENT_2 = mat2ppt.enum.BaseXmlEnum("ACCENT_2", 6, "accent2")
        ACCENT_3 = mat2ppt.enum.BaseXmlEnum("ACCENT_3", 7, "accent3")
        ACCENT_4 = mat2ppt.enum.BaseXmlEnum("ACCENT_4", 8, "accent4")
        ACCENT_5 = mat2ppt.enum.BaseXmlEnum("ACCENT_5", 9, "accent5")
        ACCENT_6 = mat2ppt.enum.BaseXmlEnum("ACCENT_6", 10, "accent6")
        BACKGROUND_1 = mat2ppt.enum.BaseXmlEnum("BACKGROUND_1", 14, "bg1")
        BACKGROUND_2 = mat2ppt.enum.BaseXmlEnum("BACKGROUND_2", 16, "bg2")
        DARK_1 = mat2ppt.enum.BaseXmlEnum("DARK_1", 1, "dk1")
        DARK_2 = mat2ppt.enum.BaseXmlEnum("DARK_2", 3, "dk2")
        FOLLOWED_HYPERLINK = mat2ppt.enum.BaseXmlEnum("FOLLOWED_HYPERLINK", 12, "folHlink")
        HYPERLINK = mat2ppt.enum.BaseXmlEnum("HYPERLINK", 11, "hlink")
        LIGHT_1 = mat2ppt.enum.BaseXmlEnum("LIGHT_1", 2, "lt1")
        LIGHT_2 = mat2ppt.enum.BaseXmlEnum("LIGHT_2", 4, "lt2")
        TEXT_1 = mat2ppt.enum.BaseXmlEnum("TEXT_1", 13, "tx1")
        TEXT_2 = mat2ppt.enum.BaseXmlEnum("TEXT_2", 15, "tx2")
        MIXED = mat2ppt.enum.BaseXmlEnum("MIXED", -2, "")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "MSO_THEME_COLOR_INDEX has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.MSO_THEME_COLOR_INDEX);
            for i = 1:numel(names)
                mem = mat2ppt.enum.MSO_THEME_COLOR_INDEX.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "MSO_THEME_COLOR_INDEX has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.MSO_THEME_COLOR_INDEX);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.MSO_THEME_COLOR_INDEX.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of MSO_THEME_COLOR_INDEX");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "MSO_THEME_COLOR_INDEX.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
