classdef MSO_VERTICAL_ANCHOR
%MSO_VERTICAL_ANCHOR  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/text.py::MSO_VERTICAL_ANCHOR
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        TOP = mat2ppt.enum.BaseXmlEnum("TOP", 1, "t")
        MIDDLE = mat2ppt.enum.BaseXmlEnum("MIDDLE", 3, "ctr")
        BOTTOM = mat2ppt.enum.BaseXmlEnum("BOTTOM", 4, "b")
        MIXED = mat2ppt.enum.BaseXmlEnum("MIXED", -2, "")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "MSO_VERTICAL_ANCHOR has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.MSO_VERTICAL_ANCHOR);
            for i = 1:numel(names)
                mem = mat2ppt.enum.MSO_VERTICAL_ANCHOR.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "MSO_VERTICAL_ANCHOR has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.MSO_VERTICAL_ANCHOR);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.MSO_VERTICAL_ANCHOR.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of MSO_VERTICAL_ANCHOR");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "MSO_VERTICAL_ANCHOR.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
