classdef MSO_PATTERN
%MSO_PATTERN  Alias of mat2ppt.enum.MSO_PATTERN_TYPE.
%
%   Ported from python-pptx 1.0.2: MSO_PATTERN = MSO_PATTERN_TYPE

    properties (Constant)
        CROSS = mat2ppt.enum.MSO_PATTERN_TYPE.CROSS
        DARK_DOWNWARD_DIAGONAL = mat2ppt.enum.MSO_PATTERN_TYPE.DARK_DOWNWARD_DIAGONAL
        DARK_HORIZONTAL = mat2ppt.enum.MSO_PATTERN_TYPE.DARK_HORIZONTAL
        DARK_UPWARD_DIAGONAL = mat2ppt.enum.MSO_PATTERN_TYPE.DARK_UPWARD_DIAGONAL
        DARK_VERTICAL = mat2ppt.enum.MSO_PATTERN_TYPE.DARK_VERTICAL
        DASHED_DOWNWARD_DIAGONAL = mat2ppt.enum.MSO_PATTERN_TYPE.DASHED_DOWNWARD_DIAGONAL
        DASHED_HORIZONTAL = mat2ppt.enum.MSO_PATTERN_TYPE.DASHED_HORIZONTAL
        DASHED_UPWARD_DIAGONAL = mat2ppt.enum.MSO_PATTERN_TYPE.DASHED_UPWARD_DIAGONAL
        DASHED_VERTICAL = mat2ppt.enum.MSO_PATTERN_TYPE.DASHED_VERTICAL
        DIAGONAL_BRICK = mat2ppt.enum.MSO_PATTERN_TYPE.DIAGONAL_BRICK
        DIAGONAL_CROSS = mat2ppt.enum.MSO_PATTERN_TYPE.DIAGONAL_CROSS
        DIVOT = mat2ppt.enum.MSO_PATTERN_TYPE.DIVOT
        DOTTED_DIAMOND = mat2ppt.enum.MSO_PATTERN_TYPE.DOTTED_DIAMOND
        DOTTED_GRID = mat2ppt.enum.MSO_PATTERN_TYPE.DOTTED_GRID
        DOWNWARD_DIAGONAL = mat2ppt.enum.MSO_PATTERN_TYPE.DOWNWARD_DIAGONAL
        HORIZONTAL = mat2ppt.enum.MSO_PATTERN_TYPE.HORIZONTAL
        HORIZONTAL_BRICK = mat2ppt.enum.MSO_PATTERN_TYPE.HORIZONTAL_BRICK
        LARGE_CHECKER_BOARD = mat2ppt.enum.MSO_PATTERN_TYPE.LARGE_CHECKER_BOARD
        LARGE_CONFETTI = mat2ppt.enum.MSO_PATTERN_TYPE.LARGE_CONFETTI
        LARGE_GRID = mat2ppt.enum.MSO_PATTERN_TYPE.LARGE_GRID
        LIGHT_DOWNWARD_DIAGONAL = mat2ppt.enum.MSO_PATTERN_TYPE.LIGHT_DOWNWARD_DIAGONAL
        LIGHT_HORIZONTAL = mat2ppt.enum.MSO_PATTERN_TYPE.LIGHT_HORIZONTAL
        LIGHT_UPWARD_DIAGONAL = mat2ppt.enum.MSO_PATTERN_TYPE.LIGHT_UPWARD_DIAGONAL
        LIGHT_VERTICAL = mat2ppt.enum.MSO_PATTERN_TYPE.LIGHT_VERTICAL
        NARROW_HORIZONTAL = mat2ppt.enum.MSO_PATTERN_TYPE.NARROW_HORIZONTAL
        NARROW_VERTICAL = mat2ppt.enum.MSO_PATTERN_TYPE.NARROW_VERTICAL
        OUTLINED_DIAMOND = mat2ppt.enum.MSO_PATTERN_TYPE.OUTLINED_DIAMOND
        PERCENT_10 = mat2ppt.enum.MSO_PATTERN_TYPE.PERCENT_10
        PERCENT_20 = mat2ppt.enum.MSO_PATTERN_TYPE.PERCENT_20
        PERCENT_25 = mat2ppt.enum.MSO_PATTERN_TYPE.PERCENT_25
        PERCENT_30 = mat2ppt.enum.MSO_PATTERN_TYPE.PERCENT_30
        ERCENT_40 = mat2ppt.enum.MSO_PATTERN_TYPE.ERCENT_40
        PERCENT_5 = mat2ppt.enum.MSO_PATTERN_TYPE.PERCENT_5
        PERCENT_50 = mat2ppt.enum.MSO_PATTERN_TYPE.PERCENT_50
        PERCENT_60 = mat2ppt.enum.MSO_PATTERN_TYPE.PERCENT_60
        PERCENT_70 = mat2ppt.enum.MSO_PATTERN_TYPE.PERCENT_70
        PERCENT_75 = mat2ppt.enum.MSO_PATTERN_TYPE.PERCENT_75
        PERCENT_80 = mat2ppt.enum.MSO_PATTERN_TYPE.PERCENT_80
        PERCENT_90 = mat2ppt.enum.MSO_PATTERN_TYPE.PERCENT_90
        PLAID = mat2ppt.enum.MSO_PATTERN_TYPE.PLAID
        SHINGLE = mat2ppt.enum.MSO_PATTERN_TYPE.SHINGLE
        SMALL_CHECKER_BOARD = mat2ppt.enum.MSO_PATTERN_TYPE.SMALL_CHECKER_BOARD
        SMALL_CONFETTI = mat2ppt.enum.MSO_PATTERN_TYPE.SMALL_CONFETTI
        SMALL_GRID = mat2ppt.enum.MSO_PATTERN_TYPE.SMALL_GRID
        SOLID_DIAMOND = mat2ppt.enum.MSO_PATTERN_TYPE.SOLID_DIAMOND
        SPHERE = mat2ppt.enum.MSO_PATTERN_TYPE.SPHERE
        TRELLIS = mat2ppt.enum.MSO_PATTERN_TYPE.TRELLIS
        UPWARD_DIAGONAL = mat2ppt.enum.MSO_PATTERN_TYPE.UPWARD_DIAGONAL
        VERTICAL = mat2ppt.enum.MSO_PATTERN_TYPE.VERTICAL
        WAVE = mat2ppt.enum.MSO_PATTERN_TYPE.WAVE
        WEAVE = mat2ppt.enum.MSO_PATTERN_TYPE.WEAVE
        WIDE_DOWNWARD_DIAGONAL = mat2ppt.enum.MSO_PATTERN_TYPE.WIDE_DOWNWARD_DIAGONAL
        WIDE_UPWARD_DIAGONAL = mat2ppt.enum.MSO_PATTERN_TYPE.WIDE_UPWARD_DIAGONAL
        ZIG_ZAG = mat2ppt.enum.MSO_PATTERN_TYPE.ZIG_ZAG
        MIXED = mat2ppt.enum.MSO_PATTERN_TYPE.MIXED
    end

    methods (Static)
        function m = from_xml(xmlValue)
            m = mat2ppt.enum.MSO_PATTERN_TYPE.from_xml(xmlValue);
        end
        function x = to_xml(value)
            x = mat2ppt.enum.MSO_PATTERN_TYPE.to_xml(value);
        end
    end
end
