classdef MSO_FILL_TYPE
%MSO_FILL_TYPE  Enumeration (BaseEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/dml.py::MSO_FILL_TYPE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        BACKGROUND = mat2ppt.enum.BaseEnum("BACKGROUND", 5)
        GRADIENT = mat2ppt.enum.BaseEnum("GRADIENT", 3)
        GROUP = mat2ppt.enum.BaseEnum("GROUP", 101)
        PATTERNED = mat2ppt.enum.BaseEnum("PATTERNED", 2)
        PICTURE = mat2ppt.enum.BaseEnum("PICTURE", 6)
        SOLID = mat2ppt.enum.BaseEnum("SOLID", 1)
        TEXTURED = mat2ppt.enum.BaseEnum("TEXTURED", 4)
    end
end
