classdef PP_ACTION_TYPE
%PP_ACTION_TYPE  Enumeration (BaseEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/action.py::PP_ACTION_TYPE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        END_SHOW = mat2ppt.enum.BaseEnum("END_SHOW", 6)
        FIRST_SLIDE = mat2ppt.enum.BaseEnum("FIRST_SLIDE", 3)
        HYPERLINK = mat2ppt.enum.BaseEnum("HYPERLINK", 7)
        LAST_SLIDE = mat2ppt.enum.BaseEnum("LAST_SLIDE", 4)
        LAST_SLIDE_VIEWED = mat2ppt.enum.BaseEnum("LAST_SLIDE_VIEWED", 5)
        NAMED_SLIDE = mat2ppt.enum.BaseEnum("NAMED_SLIDE", 101)
        NAMED_SLIDE_SHOW = mat2ppt.enum.BaseEnum("NAMED_SLIDE_SHOW", 10)
        NEXT_SLIDE = mat2ppt.enum.BaseEnum("NEXT_SLIDE", 1)
        NONE = mat2ppt.enum.BaseEnum("NONE", 0)
        OPEN_FILE = mat2ppt.enum.BaseEnum("OPEN_FILE", 102)
        OLE_VERB = mat2ppt.enum.BaseEnum("OLE_VERB", 11)
        PLAY = mat2ppt.enum.BaseEnum("PLAY", 12)
        PREVIOUS_SLIDE = mat2ppt.enum.BaseEnum("PREVIOUS_SLIDE", 2)
        RUN_MACRO = mat2ppt.enum.BaseEnum("RUN_MACRO", 8)
        RUN_PROGRAM = mat2ppt.enum.BaseEnum("RUN_PROGRAM", 9)
    end
end
