classdef PP_MEDIA_TYPE
%PP_MEDIA_TYPE  Enumeration (BaseEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/shapes.py::PP_MEDIA_TYPE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        MOVIE = mat2ppt.enum.BaseEnum("MOVIE", 3)
        OTHER = mat2ppt.enum.BaseEnum("OTHER", 1)
        MIXED = mat2ppt.enum.BaseEnum("MIXED", -2)
    end
end
