classdef PP_PLACEHOLDER_TYPE
%PP_PLACEHOLDER_TYPE  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/shapes.py::PP_PLACEHOLDER_TYPE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        BITMAP = mat2ppt.enum.BaseXmlEnum("BITMAP", 9, "clipArt")
        BODY = mat2ppt.enum.BaseXmlEnum("BODY", 2, "body")
        CENTER_TITLE = mat2ppt.enum.BaseXmlEnum("CENTER_TITLE", 3, "ctrTitle")
        CHART = mat2ppt.enum.BaseXmlEnum("CHART", 8, "chart")
        DATE = mat2ppt.enum.BaseXmlEnum("DATE", 16, "dt")
        FOOTER = mat2ppt.enum.BaseXmlEnum("FOOTER", 15, "ftr")
        HEADER = mat2ppt.enum.BaseXmlEnum("HEADER", 14, "hdr")
        MEDIA_CLIP = mat2ppt.enum.BaseXmlEnum("MEDIA_CLIP", 10, "media")
        OBJECT = mat2ppt.enum.BaseXmlEnum("OBJECT", 7, "obj")
        ORG_CHART = mat2ppt.enum.BaseXmlEnum("ORG_CHART", 11, "dgm")
        PICTURE = mat2ppt.enum.BaseXmlEnum("PICTURE", 18, "pic")
        SLIDE_IMAGE = mat2ppt.enum.BaseXmlEnum("SLIDE_IMAGE", 101, "sldImg")
        SLIDE_NUMBER = mat2ppt.enum.BaseXmlEnum("SLIDE_NUMBER", 13, "sldNum")
        SUBTITLE = mat2ppt.enum.BaseXmlEnum("SUBTITLE", 4, "subTitle")
        TABLE = mat2ppt.enum.BaseXmlEnum("TABLE", 12, "tbl")
        TITLE = mat2ppt.enum.BaseXmlEnum("TITLE", 1, "title")
        VERTICAL_BODY = mat2ppt.enum.BaseXmlEnum("VERTICAL_BODY", 6, "")
        VERTICAL_OBJECT = mat2ppt.enum.BaseXmlEnum("VERTICAL_OBJECT", 17, "")
        VERTICAL_TITLE = mat2ppt.enum.BaseXmlEnum("VERTICAL_TITLE", 5, "")
        MIXED = mat2ppt.enum.BaseXmlEnum("MIXED", -2, "")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "PP_PLACEHOLDER_TYPE has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.PP_PLACEHOLDER_TYPE);
            for i = 1:numel(names)
                mem = mat2ppt.enum.PP_PLACEHOLDER_TYPE.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "PP_PLACEHOLDER_TYPE has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.PP_PLACEHOLDER_TYPE);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.PP_PLACEHOLDER_TYPE.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of PP_PLACEHOLDER_TYPE");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "PP_PLACEHOLDER_TYPE.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
