classdef PP_PARAGRAPH_ALIGNMENT
%PP_PARAGRAPH_ALIGNMENT  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/text.py::PP_PARAGRAPH_ALIGNMENT
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        CENTER = mat2ppt.enum.BaseXmlEnum("CENTER", 2, "ctr")
        DISTRIBUTE = mat2ppt.enum.BaseXmlEnum("DISTRIBUTE", 5, "dist")
        JUSTIFY = mat2ppt.enum.BaseXmlEnum("JUSTIFY", 4, "just")
        JUSTIFY_LOW = mat2ppt.enum.BaseXmlEnum("JUSTIFY_LOW", 7, "justLow")
        LEFT = mat2ppt.enum.BaseXmlEnum("LEFT", 1, "l")
        RIGHT = mat2ppt.enum.BaseXmlEnum("RIGHT", 3, "r")
        THAI_DISTRIBUTE = mat2ppt.enum.BaseXmlEnum("THAI_DISTRIBUTE", 6, "thaiDist")
        MIXED = mat2ppt.enum.BaseXmlEnum("MIXED", -2, "")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "PP_PARAGRAPH_ALIGNMENT has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.PP_PARAGRAPH_ALIGNMENT);
            for i = 1:numel(names)
                mem = mat2ppt.enum.PP_PARAGRAPH_ALIGNMENT.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "PP_PARAGRAPH_ALIGNMENT has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.PP_PARAGRAPH_ALIGNMENT);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.PP_PARAGRAPH_ALIGNMENT.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of PP_PARAGRAPH_ALIGNMENT");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "PP_PARAGRAPH_ALIGNMENT.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
