classdef PROG_ID
%PROG_ID  Enumeration (BaseEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/shapes.py::PROG_ID
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        DOCX = mat2ppt.enum.BaseEnum("DOCX", 302, "DOCX")
        PPTX = mat2ppt.enum.BaseEnum("PPTX", 332, "PPTX")
        XLSX = mat2ppt.enum.BaseEnum("XLSX", 335, "XLSX")
    end
end
