classdef XL_AXIS_CROSSES
%XL_AXIS_CROSSES  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/chart.py::XL_AXIS_CROSSES
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        AUTOMATIC = mat2ppt.enum.BaseXmlEnum("AUTOMATIC", -4105, "autoZero")
        CUSTOM = mat2ppt.enum.BaseXmlEnum("CUSTOM", -4114, "")
        MAXIMUM = mat2ppt.enum.BaseXmlEnum("MAXIMUM", 2, "max")
        MINIMUM = mat2ppt.enum.BaseXmlEnum("MINIMUM", 4, "min")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "XL_AXIS_CROSSES has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.XL_AXIS_CROSSES);
            for i = 1:numel(names)
                mem = mat2ppt.enum.XL_AXIS_CROSSES.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "XL_AXIS_CROSSES has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.XL_AXIS_CROSSES);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.XL_AXIS_CROSSES.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of XL_AXIS_CROSSES");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "XL_AXIS_CROSSES.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
