classdef XL_CATEGORY_TYPE
%XL_CATEGORY_TYPE  Enumeration (BaseEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/chart.py::XL_CATEGORY_TYPE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        AUTOMATIC_SCALE = mat2ppt.enum.BaseEnum("AUTOMATIC_SCALE", -4105)
        CATEGORY_SCALE = mat2ppt.enum.BaseEnum("CATEGORY_SCALE", 2)
        TIME_SCALE = mat2ppt.enum.BaseEnum("TIME_SCALE", 3)
    end
end
