classdef XL_DATA_LABEL_POSITION
%XL_DATA_LABEL_POSITION  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/chart.py::XL_DATA_LABEL_POSITION
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        ABOVE = mat2ppt.enum.BaseXmlEnum("ABOVE", 0, "t")
        BELOW = mat2ppt.enum.BaseXmlEnum("BELOW", 1, "b")
        BEST_FIT = mat2ppt.enum.BaseXmlEnum("BEST_FIT", 5, "bestFit")
        CENTER = mat2ppt.enum.BaseXmlEnum("CENTER", -4108, "ctr")
        INSIDE_BASE = mat2ppt.enum.BaseXmlEnum("INSIDE_BASE", 4, "inBase")
        INSIDE_END = mat2ppt.enum.BaseXmlEnum("INSIDE_END", 3, "inEnd")
        LEFT = mat2ppt.enum.BaseXmlEnum("LEFT", -4131, "l")
        MIXED = mat2ppt.enum.BaseXmlEnum("MIXED", 6, "")
        OUTSIDE_END = mat2ppt.enum.BaseXmlEnum("OUTSIDE_END", 2, "outEnd")
        RIGHT = mat2ppt.enum.BaseXmlEnum("RIGHT", -4152, "r")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "XL_DATA_LABEL_POSITION has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.XL_DATA_LABEL_POSITION);
            for i = 1:numel(names)
                mem = mat2ppt.enum.XL_DATA_LABEL_POSITION.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "XL_DATA_LABEL_POSITION has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.XL_DATA_LABEL_POSITION);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.XL_DATA_LABEL_POSITION.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of XL_DATA_LABEL_POSITION");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "XL_DATA_LABEL_POSITION.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
