classdef XL_LEGEND_POSITION
%XL_LEGEND_POSITION  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/chart.py::XL_LEGEND_POSITION
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        BOTTOM = mat2ppt.enum.BaseXmlEnum("BOTTOM", -4107, "b")
        CORNER = mat2ppt.enum.BaseXmlEnum("CORNER", 2, "tr")
        CUSTOM = mat2ppt.enum.BaseXmlEnum("CUSTOM", -4161, "")
        LEFT = mat2ppt.enum.BaseXmlEnum("LEFT", -4131, "l")
        RIGHT = mat2ppt.enum.BaseXmlEnum("RIGHT", -4152, "r")
        TOP = mat2ppt.enum.BaseXmlEnum("TOP", -4160, "t")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "XL_LEGEND_POSITION has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.XL_LEGEND_POSITION);
            for i = 1:numel(names)
                mem = mat2ppt.enum.XL_LEGEND_POSITION.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "XL_LEGEND_POSITION has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.XL_LEGEND_POSITION);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.XL_LEGEND_POSITION.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of XL_LEGEND_POSITION");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "XL_LEGEND_POSITION.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
