classdef XL_MARKER_STYLE
%XL_MARKER_STYLE  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/chart.py::XL_MARKER_STYLE
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        AUTOMATIC = mat2ppt.enum.BaseXmlEnum("AUTOMATIC", -4105, "auto")
        CIRCLE = mat2ppt.enum.BaseXmlEnum("CIRCLE", 8, "circle")
        DASH = mat2ppt.enum.BaseXmlEnum("DASH", -4115, "dash")
        DIAMOND = mat2ppt.enum.BaseXmlEnum("DIAMOND", 2, "diamond")
        DOT = mat2ppt.enum.BaseXmlEnum("DOT", -4118, "dot")
        NONE = mat2ppt.enum.BaseXmlEnum("NONE", -4142, "none")
        PICTURE = mat2ppt.enum.BaseXmlEnum("PICTURE", -4147, "picture")
        PLUS = mat2ppt.enum.BaseXmlEnum("PLUS", 9, "plus")
        SQUARE = mat2ppt.enum.BaseXmlEnum("SQUARE", 1, "square")
        STAR = mat2ppt.enum.BaseXmlEnum("STAR", 5, "star")
        TRIANGLE = mat2ppt.enum.BaseXmlEnum("TRIANGLE", 3, "triangle")
        X = mat2ppt.enum.BaseXmlEnum("X", -4168, "x")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "XL_MARKER_STYLE has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.XL_MARKER_STYLE);
            for i = 1:numel(names)
                mem = mat2ppt.enum.XL_MARKER_STYLE.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "XL_MARKER_STYLE has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.XL_MARKER_STYLE);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.XL_MARKER_STYLE.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of XL_MARKER_STYLE");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "XL_MARKER_STYLE.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
