classdef XL_TICK_MARK
%XL_TICK_MARK  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/chart.py::XL_TICK_MARK
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        CROSS = mat2ppt.enum.BaseXmlEnum("CROSS", 4, "cross")
        INSIDE = mat2ppt.enum.BaseXmlEnum("INSIDE", 2, "in")
        NONE = mat2ppt.enum.BaseXmlEnum("NONE", -4142, "none")
        OUTSIDE = mat2ppt.enum.BaseXmlEnum("OUTSIDE", 3, "out")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "XL_TICK_MARK has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.XL_TICK_MARK);
            for i = 1:numel(names)
                mem = mat2ppt.enum.XL_TICK_MARK.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "XL_TICK_MARK has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.XL_TICK_MARK);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.XL_TICK_MARK.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of XL_TICK_MARK");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "XL_TICK_MARK.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
