classdef XL_TICK_LABEL_POSITION
%XL_TICK_LABEL_POSITION  Enumeration (BaseXmlEnum).
%
%   Ported from python-pptx 1.0.2: src/pptx/enum/chart.py::XL_TICK_LABEL_POSITION
%   Generated by harness/gen_matlab_enums.py — do not hand-edit member list.

    properties (Constant)
        HIGH = mat2ppt.enum.BaseXmlEnum("HIGH", -4127, "high")
        LOW = mat2ppt.enum.BaseXmlEnum("LOW", -4134, "low")
        NEXT_TO_AXIS = mat2ppt.enum.BaseXmlEnum("NEXT_TO_AXIS", 4, "nextTo")
        NONE = mat2ppt.enum.BaseXmlEnum("NONE", -4142, "none")
    end

    methods (Static)
        function m = from_xml(xmlValue)
            xmlValue = char(string(xmlValue));
            if strlength(string(xmlValue)) == 0
                error("mat2ppt:ValueError", "XL_TICK_LABEL_POSITION has no XML mapping for ''");
            end
            names = properties(mat2ppt.enum.XL_TICK_LABEL_POSITION);
            for i = 1:numel(names)
                mem = mat2ppt.enum.XL_TICK_LABEL_POSITION.(names{i});
                if isa(mem, "mat2ppt.enum.BaseXmlEnum") && strcmp(char(mem.xml_value), xmlValue)
                    m = mem;
                    return
                end
            end
            error("mat2ppt:ValueError", "XL_TICK_LABEL_POSITION has no XML mapping for '%s'", xmlValue);
        end

        function x = to_xml(value)
            if isa(value, "mat2ppt.enum.BaseXmlEnum")
                mem = value;
            else
                names = properties(mat2ppt.enum.XL_TICK_LABEL_POSITION);
                mem = [];
                for i = 1:numel(names)
                    cand = mat2ppt.enum.XL_TICK_LABEL_POSITION.(names{i});
                    if isa(cand, "mat2ppt.enum.BaseEnum") && cand.value == double(value)
                        mem = cand;
                        break
                    end
                end
                if isempty(mem)
                    error("mat2ppt:ValueError", "value is not a member of XL_TICK_LABEL_POSITION");
                end
            end
            if strlength(string(mem.xml_value)) == 0
                error("mat2ppt:ValueError", "XL_TICK_LABEL_POSITION.%s has no XML representation", mem.name);
            end
            x = char(mem.xml_value);
        end
    end
end
