%% demo.m — Recreate 04_Box_Treasurer__SLG_CheckoutDotCom_RequestedInfo_Rev1 via Mat2Ppt public API
% Source: 04_Box_Treasurer__SLG_CheckoutDotCom_RequestedInfo_Rev1.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image1.jpg
img = fullfile(assets, 'image1.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(6126480), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(742950));
end

% picture MasterLogo_image2.png
img = fullfile(assets, 'image2.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(0), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(6858000));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(2420471), mat2ppt.util.Emu(887991), mat2ppt.util.Emu(8624048), mat2ppt.util.Emu(2541431));
sp.text_frame().text = 'The Saint Luke GuildCheckout.com Requested Info';

% Subtitle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(5087501), mat2ppt.util.Emu(4508825), mat2ppt.util.Emu(7104499), mat2ppt.util.Emu(1605104));
sp.text_frame().text = 'Douglas CoombsJuly 1, 2022, Rev. 1';


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(318053), mat2ppt.util.Emu(1), mat2ppt.util.Emu(10736802), mat2ppt.util.Emu(868705));
sp.text_frame().text = 'Transaction InformationData Request';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(480061), mat2ppt.util.Emu(938440), mat2ppt.util.Emu(11496786), mat2ppt.util.Emu(5687646));
sp.text_frame().text = 'A payment flow to properly understand what Checkout.com is exactly processing for.See the next slidePlease provide further details on what the merchant will be accepting payments for.We are accepting donations to fundArt displays at schoolsProjects to help schools in the selection of art (e.g., a timeline/database of art masterpieces)Costs to attend educational conferences and educate schools on the value of art reproductionsPlease provide the URL where payments will be accepted. Please also provide demo or Test login details to verify the websitewww.saintlukeguild.com/projects (this will be updated when we begin taking payments)Please confirm the annual processing volumeMaybe $5k-$10k/year to begin.  It is hard to say.  We currently bring in around $20k/year in large checks.  Most larger donors will probably still choose to give via check.';


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% connector Connector: Elbow 33
sh.add_connector('bentConnector3', mat2ppt.util.Emu(6539551), mat2ppt.util.Emu(2438050), mat2ppt.util.Emu(8265640), mat2ppt.util.Emu(5392890));

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(110836), mat2ppt.util.Emu(46180), mat2ppt.util.Emu(12081164), mat2ppt.util.Emu(876687));
sp.text_frame().text = 'Transaction Flow Chart for Website Donor Funds';

% Content Placeholder 7
sp = sh.add_shape('rect', mat2ppt.util.Emu(110836), mat2ppt.util.Emu(4590252), mat2ppt.util.Emu(5541614), mat2ppt.util.Emu(1519145));
sp.text_frame().text = 'General support projects are not specific to any school Project costs are school specific';

% Rectangle: Rounded Corners 3
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(110836), mat2ppt.util.Emu(2712492), mat2ppt.util.Emu(2932615), mat2ppt.util.Emu(1750326));
sp.text_frame().text = 'Donors give to either a school project (restricted), a general support project, (restricted) or general funds (unrestricted)';

% Rectangle: Rounded Corners 16
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(8265640), mat2ppt.util.Emu(4676382), mat2ppt.util.Emu(2932615), mat2ppt.util.Emu(1433015));
sp.text_frame().text = 'Project costs are spent 100% on school art projects for specific schools';

% Rectangle: Rounded Corners 17
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(3606936), mat2ppt.util.Emu(1721542), mat2ppt.util.Emu(2932615), mat2ppt.util.Emu(1433015));
sp.text_frame().text = 'General funds are discretionary and can cover either overhead or project costs';

% connector Connector: Elbow 8
sh.add_connector('bentConnector3', mat2ppt.util.Emu(3043451), mat2ppt.util.Emu(3587655), mat2ppt.util.Emu(8265640), mat2ppt.util.Emu(5392890));

% connector Connector: Elbow 18
sh.add_connector('bentConnector3', mat2ppt.util.Emu(3043451), mat2ppt.util.Emu(3587655), mat2ppt.util.Emu(3606936), mat2ppt.util.Emu(2438050));

% Rectangle: Rounded Corners 21
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(8265641), mat2ppt.util.Emu(1101172), mat2ppt.util.Emu(2932615), mat2ppt.util.Emu(1433015));
sp.text_frame().text = 'Overhead costs are things like PO box and website fees';

% Rectangle: Rounded Corners 23
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(8265640), mat2ppt.util.Emu(2888777), mat2ppt.util.Emu(2932615), mat2ppt.util.Emu(1433015));
sp.text_frame().text = 'General support project costs are for things like an art timeline database to help schools select art for their hallways';

% connector Connector: Elbow 29
sh.add_connector('bentConnector3', mat2ppt.util.Emu(6539551), mat2ppt.util.Emu(2438050), mat2ppt.util.Emu(8301485), mat2ppt.util.Emu(1798030));

% connector Connector: Elbow 31
sh.add_connector('bentConnector3', mat2ppt.util.Emu(6539551), mat2ppt.util.Emu(2438050), mat2ppt.util.Emu(8265640), mat2ppt.util.Emu(3605285));

% connector Straight Arrow Connector 35
sh.add_connector('straightConnector1', mat2ppt.util.Emu(3043451), mat2ppt.util.Emu(3587655), mat2ppt.util.Emu(8265640), mat2ppt.util.Emu(3605285));


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(110836), mat2ppt.util.Emu(46180), mat2ppt.util.Emu(12081164), mat2ppt.util.Emu(876687));
sp.text_frame().text = 'Website Donor FormsEntry Point for Project Funding';

% Content Placeholder 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(253639), mat2ppt.util.Emu(938439), mat2ppt.util.Emu(4869072), mat2ppt.util.Emu(3597702));
sp.text_frame().text = 'Simple Donate Button next to each project on website takes donors to a common donation form with a drop down menu to select a projectThe Saint Luke Guild should be able to add projects to the listAll form information should be communicated to the Saint Luke Guild along with money';

% Rectangle: Rounded Corners 2
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(1728951), mat2ppt.util.Emu(4731972), mat2ppt.util.Emu(1918447), mat2ppt.util.Emu(703729));
sp.text_frame().text = 'Donate Now';

% Rectangle: Rounded Corners 3
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(5122711), mat2ppt.util.Emu(1473267), mat2ppt.util.Emu(5970494), mat2ppt.util.Emu(5513521));

% TextBox 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(5673421), mat2ppt.util.Emu(1474189), mat2ppt.util.Emu(5419783), mat2ppt.util.Emu(5512599));
sp.text_frame().text = 'First Name: _______________________Last Name: _______________________Address: _________________________City: ____________________________State:  [Drop Down ]         Zip: ___________  Keep me anonymous to project schools.Project: [Drop Down List]Pledge Amount: $  ___________Credit Card Info';

% Arrow: Right 7
sp = sh.add_shape('rightArrow', mat2ppt.util.Emu(4087905), mat2ppt.util.Emu(4840244), mat2ppt.util.Emu(932325), mat2ppt.util.Emu(487183));


%% ===== Slide 5 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(110836), mat2ppt.util.Emu(46180), mat2ppt.util.Emu(12081164), mat2ppt.util.Emu(876687));
sp.text_frame().text = 'Website Donor FormsIdeal Point';

% Content Placeholder 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(253639), mat2ppt.util.Emu(938439), mat2ppt.util.Emu(4869072), mat2ppt.util.Emu(3597702));
sp.text_frame().text = 'In an ideal world, we would be able to have bar graphs showing how much money has been donated to a given projectSimilar to KickstarterSLG staff would be able to enter check donations to move the barThis would mean each project would have a standalone donor form.';

% Rectangle: Rounded Corners 2
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(1201275), mat2ppt.util.Emu(5276081), mat2ppt.util.Emu(1918447), mat2ppt.util.Emu(703729));
sp.text_frame().text = 'Donate Now';

% Rectangle: Rounded Corners 3
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(5122711), mat2ppt.util.Emu(1473267), mat2ppt.util.Emu(5970494), mat2ppt.util.Emu(5236522));

% TextBox 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(5673422), mat2ppt.util.Emu(1474189), mat2ppt.util.Emu(4869072), mat2ppt.util.Emu(5235600));
sp.text_frame().text = 'Project: Holy Child Catholic SchoolFirst Name: _______________________Last Name: _______________________Address: _________________________City: ____________________________State:  [Drop Down ]         Zip: ___________ Keep me anonymous to the above school.Pledge Amount: $  ___________Credit Card Info';

% Arrow: Right 7
sp = sh.add_shape('rightArrow', mat2ppt.util.Emu(4255368), mat2ppt.util.Emu(5334618), mat2ppt.util.Emu(932325), mat2ppt.util.Emu(487183));

% Oval 8
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(6060142), mat2ppt.util.Emu(914404), mat2ppt.util.Emu(594360), mat2ppt.util.Emu(594360));

% Rectangle 9
sp = sh.add_shape('rect', mat2ppt.util.Emu(6338048), mat2ppt.util.Emu(1050772), mat2ppt.util.Emu(1882588), mat2ppt.util.Emu(321624));

% Rectangle 10
sp = sh.add_shape('rect', mat2ppt.util.Emu(8086165), mat2ppt.util.Emu(1050772), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(321624));

% TextBox 11
sp = sh.add_shape('rect', mat2ppt.util.Emu(9914965), mat2ppt.util.Emu(857186), mat2ppt.util.Emu(1890320), mat2ppt.util.Emu(646331));
sp.text_frame().text = '$15,250 of $30,000 Raised';

% Oval 14
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(6060142), mat2ppt.util.Emu(914404), mat2ppt.util.Emu(594360), mat2ppt.util.Emu(594360));

% Rectangle 15
sp = sh.add_shape('rect', mat2ppt.util.Emu(6338048), mat2ppt.util.Emu(1050772), mat2ppt.util.Emu(1882588), mat2ppt.util.Emu(321624));

% Rectangle 16
sp = sh.add_shape('rect', mat2ppt.util.Emu(8086165), mat2ppt.util.Emu(1050772), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(321624));

% TextBox 17
sp = sh.add_shape('rect', mat2ppt.util.Emu(9914965), mat2ppt.util.Emu(857186), mat2ppt.util.Emu(1890320), mat2ppt.util.Emu(646331));
sp.text_frame().text = '$15,250 of $30,000 Raised';


%% ===== Slide 6 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(318053), mat2ppt.util.Emu(1), mat2ppt.util.Emu(10736802), mat2ppt.util.Emu(868705));
sp.text_frame().text = 'Bank Account Info';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(129981), mat2ppt.util.Emu(938440), mat2ppt.util.Emu(4459948), mat2ppt.util.Emu(5687646));
sp.text_frame().text = 'Routing #: 307083911Auto WD and Direct Deposit #: 9225000161Account #: 10422500-9001Not used for electronic transactions';

% picture Picture 4
img = fullfile(assets, 'image3.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4762187), mat2ppt.util.Emu(926471), mat2ppt.util.Emu(7111760), mat2ppt.util.Emu(5896834));
end


%% ===== Slide 7 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(318053), mat2ppt.util.Emu(1), mat2ppt.util.Emu(10736802), mat2ppt.util.Emu(868705));
sp.text_frame().text = 'KYC documentation';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(480061), mat2ppt.util.Emu(938440), mat2ppt.util.Emu(10386722), mat2ppt.util.Emu(675207));
sp.text_frame().text = 'Passport/Driver’s License for Douglas Coombs';

% picture Picture 4
img = fullfile(assets, 'image4.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(67047), mat2ppt.util.Emu(1683381), mat2ppt.util.Emu(6042212), mat2ppt.util.Emu(3729317));
end

% picture Picture 6
img = fullfile(assets, 'image5.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6220216), mat2ppt.util.Emu(1689847), mat2ppt.util.Emu(5923677), mat2ppt.util.Emu(3722851));
end


%% ===== Slide 8 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(318053), mat2ppt.util.Emu(1), mat2ppt.util.Emu(10736802), mat2ppt.util.Emu(868705));
sp.text_frame().text = 'Legalese on Website';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(480060), mat2ppt.util.Emu(938440), mat2ppt.util.Emu(11052297), mat2ppt.util.Emu(5687646));
sp.text_frame().text = 'Legal entity name: The Saint Luke GuildGoverning jurisdiction: New MexicoMerchant registered business address: 2718 University Blvd NE, Albuquerque, NM 87107Privacy PolicySee next slideRefund/Cancellation/Return PolicySee next slideSee www.SaintLukeGuild.com/About-UsTo be moved to www.SaintLukeGuild.com/Legalese at a future date';


%% ===== Slide 9 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(318053), mat2ppt.util.Emu(1), mat2ppt.util.Emu(10736802), mat2ppt.util.Emu(868705));
sp.text_frame().text = 'Privacy and Refund Policy';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(318052), mat2ppt.util.Emu(938439), mat2ppt.util.Emu(11425713), mat2ppt.util.Emu(5193419));
sp.text_frame().text = 'https://www.saintlukeguild.com/about-usRefund PolicyThe Saint Luke Guild does not deliver products to individuals; therefore cancellations and returns are not applicable.  Also, donor refunds are not generally offered.  Refunds will be considered on a case-by-case basis before money is distributed to the designated project (e.g., if someone accidentally entered the wrong donation amount and contact is made within one business day).  To request a refund, contact us at refunds@saintlukeguild.com.Privacy PolicyThe Saint Luke Guild takes donor information and privacy very seriously.  We will never sell donor information to a third party for any reason.Donor information will only be shared with outside businesses as necessary to deliver services (e.g., processing credit card donations, etc.).The exception is when donors choose a specific school project to donate to.  When this occurs, donor information will typically be shared with the specified school, so that they can know to whom they should be grateful.  Donors may opt out of information sharing on the donor form.';


%% ===== Slide 10 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(318053), mat2ppt.util.Emu(1), mat2ppt.util.Emu(10736802), mat2ppt.util.Emu(868705));
sp.text_frame().text = 'Regulatory Documents';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(480061), mat2ppt.util.Emu(938440), mat2ppt.util.Emu(10386722), mat2ppt.util.Emu(5687646));
sp.text_frame().text = 'License required to operate the businessNM_SoS_InitialReport_2016917025-502856.pdfNM_ArticlesOfIncorporation_AoI_Approved.pdfLicenses for all jurisdictions in which you intend to provide your services.Starting in NM.  Other locations unknown, so far.  Copy of AML/KYC policy and proceduresNot sure what this would look like.  Are there examples?Completed AML QuestionnaireHas this been done?';


%% ===== Slide 11 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(318053), mat2ppt.util.Emu(1), mat2ppt.util.Emu(10736802), mat2ppt.util.Emu(868705));
sp.text_frame().text = 'Corporate Documents';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(480061), mat2ppt.util.Emu(938440), mat2ppt.util.Emu(10386722), mat2ppt.util.Emu(5687646));
sp.text_frame().text = 'Please provide 501c3 document to confirm tax exempt statusThe following are attachedIRS_f1023ez_SaintLukeGuild_20210711_AsSubmitted.pdfIRS_fSS4_EIN_Letter_CP575Notice_1622224687610.pdf';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);
