addpath('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt');
nOk=0;nFail=0;
try, fprintf(1,'RUN 09_Dropbox_aAdela__FairiesAdela\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/09_Dropbox_aAdela__FairiesAdela/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 01_Box_Conferences__SLG_Intro4Scientists\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/01_Box_Conferences__SLG_Intro4Scientists/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 07_Dropbox_a_Chesterton__ChestertonABQ_EmergencyCommunicationOptions_2022-0\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/07_Dropbox_a_Chesterton__ChestertonABQ_EmergencyCommunicationOptions_2022-0/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 17_Dropbox_Politics__Meme Creation\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/17_Dropbox_Politics__Meme Creation/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 08_Dropbox_a_Holy_Child__Experiment_14_Atoms_and_Molecules\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/08_Dropbox_a_Holy_Child__Experiment_14_Atoms_and_Molecules/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 14_Dropbox_Ethics__High School NFP presentation\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/14_Dropbox_Ethics__High School NFP presentation/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 13_Dropbox_Education__Engineering_CareerOverview_SHS_DMCoombs_20210407_r\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/13_Dropbox_Education__Engineering_CareerOverview_SHS_DMCoombs_20210407_r/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 19_Dropbox_Real_Estate__Coombs_500 Chama_Proof that Moving is a Good Idea\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/19_Dropbox_Real_Estate__Coombs_500 Chama_Proof that Moving is a Good Idea/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 25_Dropbox_w-job_search__CES Recap_Modeling_100513_FinalD2\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/25_Dropbox_w-job_search__CES Recap_Modeling_100513_FinalD2/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 10_Dropbox_aDietrich__Oregon State Report Pictures\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/10_Dropbox_aDietrich__Oregon State Report Pictures/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 03_Box_Secretary__ArtNonprofit_Info_Planning_Meeting_20201220\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/03_Box_Secretary__ArtNonprofit_Info_Planning_Meeting_20201220/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 04_Box_Treasurer__SLG_CheckoutDotCom_RequestedInfo_Rev1\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/04_Box_Treasurer__SLG_CheckoutDotCom_RequestedInfo_Rev1/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 24_Dropbox_technology__HCCS_PrinterInstall_20180206_r0\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/24_Dropbox_technology__HCCS_PrinterInstall_20180206_r0/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'RUN 20_Dropbox_Recreation__ExampleItinerary\n'); run('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt/examples/recreations/20_Dropbox_Recreation__ExampleItinerary/demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
fprintf(1,'BATCH ok=%d fail=%d\n',nOk,nFail);
