addpath('C:/Users/dougl/Repos/MSOffice_Grok/Mat2Ppt');
nOk=0;nFail=0;
try, fprintf(1,'[1] 02_Box_FoundingDocs__Dissolution_DistributionOfAssets_FlowChart.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\02_Box_FoundingDocs__Dissolution_DistributionOfAssets_FlowChart\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[2] 21_Dropbox_Religion__Rupnik_Saturno_Clericalism.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\21_Dropbox_Religion__Rupnik_Saturno_Clericalism\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[3] 12_Dropbox_aReuben__Fall 2018_Math Schedule.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\12_Dropbox_aReuben__Fall 2018_Math Schedule\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[4] 05_Box_Website__Thermometer_Graphic.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\05_Box_Website__Thermometer_Graphic\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[5] 11_Dropbox_aEmmerich__Denmark_Pictures.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\11_Dropbox_aEmmerich__Denmark_Pictures\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[6] 17_Dropbox_Politics__Meme Creation.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\17_Dropbox_Politics__Meme Creation\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[7] 16_Dropbox_Friends__Maile_UMary_Course Plan_TheoMajor_ArtMinor_Graphic.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\16_Dropbox_Friends__Maile_UMary_Course Plan_TheoMajor_ArtMinor_Graphic\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[8] 23_Dropbox_Soccer__SoccerAward.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\23_Dropbox_Soccer__SoccerAward\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[9] 06_Box_Zeffy__Donation_Form_Question_Discrepencies_by_Link_Type_.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\06_Box_Zeffy__Donation_Form_Question_Discrepencies_by_Link_Type_\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[10] 20_Dropbox_Recreation__ExampleItinerary.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\20_Dropbox_Recreation__ExampleItinerary\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[11] 18_Dropbox_Poverty_Awareness__Display Board Titles Headers.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\18_Dropbox_Poverty_Awareness__Display Board Titles Headers\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[12] 26_Dropbox_w-Sandia__Vibrationdata_download.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\26_Dropbox_w-Sandia__Vibrationdata_download\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[13] 01_Box_Conferences__SLG_Intro4Scientists.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\01_Box_Conferences__SLG_Intro4Scientists\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[14] 15_Dropbox_Family__picturesForPuttingAwayClothes.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\15_Dropbox_Family__picturesForPuttingAwayClothes\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[15] 22_Dropbox_Sangre_de_Cristo__Aerial_Views_Markup.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\22_Dropbox_Sangre_de_Cristo__Aerial_Views_Markup\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[16] 07_Dropbox_a_Chesterton__ChestertonABQ_EmergencyCommunicationOptions_2022-0.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\07_Dropbox_a_Chesterton__ChestertonABQ_EmergencyCommunicationOptions_2022-0\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[17] 24_Dropbox_technology__HCCS_PrinterInstall_20180206_r0.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\24_Dropbox_technology__HCCS_PrinterInstall_20180206_r0\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[18] 03_Box_Secretary__ArtNonprofit_Info_Planning_Meeting_20201220.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\03_Box_Secretary__ArtNonprofit_Info_Planning_Meeting_20201220\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[19] 04_Box_Treasurer__SLG_CheckoutDotCom_RequestedInfo_Rev1.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\04_Box_Treasurer__SLG_CheckoutDotCom_RequestedInfo_Rev1\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[20] 10_Dropbox_aDietrich__Oregon State Report Pictures.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\10_Dropbox_aDietrich__Oregon State Report Pictures\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[21] 09_Dropbox_aAdela__FairiesAdela.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\09_Dropbox_aAdela__FairiesAdela\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[22] 08_Dropbox_a_Holy_Child__Experiment_14_Atoms_and_Molecules.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\08_Dropbox_a_Holy_Child__Experiment_14_Atoms_and_Molecules\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[23] 19_Dropbox_Real_Estate__Coombs_500 Chama_Proof that Moving is a Good Idea.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\19_Dropbox_Real_Estate__Coombs_500 Chama_Proof that Moving is a Good Idea\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[24] 13_Dropbox_Education__Engineering_CareerOverview_SHS_DMCoombs_20210407_r.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\13_Dropbox_Education__Engineering_CareerOverview_SHS_DMCoombs_20210407_r\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[25] 25_Dropbox_w-job_search__CES Recap_Modeling_100513_FinalD2.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\25_Dropbox_w-job_search__CES Recap_Modeling_100513_FinalD2\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
try, fprintf(1,'[26] 14_Dropbox_Ethics__High School NFP presentation.pptx\n'); run('C:\Users\dougl\Repos\MSOffice_Grok\Mat2Ppt\examples\recreations\14_Dropbox_Ethics__High School NFP presentation\demo.m'); nOk=nOk+1; catch ME, nFail=nFail+1; fprintf(1,'FAIL %s\n',ME.message); end
fprintf(1,'BATCH ok=%d fail=%d\n',nOk,nFail);
