%% demo.m — Recreate 22_Dropbox_Sangre_de_Cristo__Aerial_Views_Markup via Mat2Ppt public API
% Source: 22_Dropbox_Sangre_de_Cristo__Aerial_Views_Markup.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(9144000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% TODO: group shape Group 6


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% TODO: group shape Group 6


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% TODO: group shape Group 6


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% TODO: group shape Group 6


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide1 group shape Group 6 not expanded
% GAP: slide2 group shape Group 6 not expanded
% GAP: slide3 group shape Group 6 not expanded
% GAP: slide4 group shape Group 6 not expanded
