classdef AreaChartXmlWriter < handle
%AREACHARTXMLWRITER  c:chartSpace for area charts (R5-W1).
%
%   Ported from python-pptx chart/xmlwriter.py::_AreaChartXmlWriter

    properties (Access = private)
        chartType_
        chartData_
    end

    methods
        function obj = AreaChartXmlWriter(chartType, chartData)
            obj.chartType_ = chartType;
            obj.chartData_ = chartData;
        end

        function xml = xml(obj)
            nl = char(10);
            xml = [ ...
                '<?xml version=''1.0'' encoding=''UTF-8'' standalone=''yes''?>' nl ...
                '<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" ' ...
                'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ' ...
                'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">' nl ...
                '  <c:date1904 val="0"/>' nl ...
                '  <c:chart>' nl ...
                '    <c:autoTitleDeleted val="0"/>' nl ...
                '    <c:plotArea>' nl ...
                '      <c:areaChart>' nl ...
                obj.grouping_xml_() ...
                obj.ser_xml_() ...
                '        <c:axId val="-2101159928"/>' nl ...
                '        <c:axId val="-2100718248"/>' nl ...
                '      </c:areaChart>' nl ...
                '      <c:catAx>' nl ...
                '        <c:axId val="-2101159928"/>' nl ...
                '        <c:scaling/>' nl ...
                '        <c:delete val="0"/>' nl ...
                '        <c:axPos val="b"/>' nl ...
                '        <c:majorTickMark val="out"/>' nl ...
                '        <c:tickLblPos val="nextTo"/>' nl ...
                '        <c:crossAx val="-2100718248"/>' nl ...
                '      </c:catAx>' nl ...
                '      <c:valAx>' nl ...
                '        <c:axId val="-2100718248"/>' nl ...
                '        <c:scaling/>' nl ...
                '        <c:delete val="0"/>' nl ...
                '        <c:axPos val="l"/>' nl ...
                '        <c:majorGridlines/>' nl ...
                '        <c:majorTickMark val="out"/>' nl ...
                '        <c:tickLblPos val="nextTo"/>' nl ...
                '        <c:crossAx val="-2101159928"/>' nl ...
                '      </c:valAx>' nl ...
                '    </c:plotArea>' nl ...
                '    <c:dispBlanksAs val="zero"/>' nl ...
                '  </c:chart>' nl ...
                '</c:chartSpace>' nl];
        end
    end

    methods (Access = private)
        function s = grouping_xml_(obj)
            XL = mat2ppt.enum.XL_CHART_TYPE;
            v = obj.ct_val_();
            nl = char(10);
            if v == XL.AREA_STACKED.value
                g = 'stacked';
            elseif v == XL.AREA_STACKED_100.value
                g = 'percentStacked';
            else
                g = 'standard';
            end
            s = sprintf('        <c:grouping val="%s"/>%s', g, nl);
        end

        function s = ser_xml_(obj)
            data = obj.chartData_;
            s = '';
            for i = 1:data.series_count()
                sw = mat2ppt.chart.CategorySeriesXmlWriter(data, i);
                pyIdx = i - 1;
                s = [s, sprintf([ ...
                    '        <c:ser>\n' ...
                    '          <c:idx val="%d"/>\n' ...
                    '          <c:order val="%d"/>\n' ...
                    '%s%s%s' ...
                    '        </c:ser>\n'], ...
                    pyIdx, pyIdx, sw.tx_xml(), sw.cat_xml(), sw.val_xml())]; %#ok<AGROW>
            end
        end

        function v = ct_val_(obj)
            ct = obj.chartType_;
            if isa(ct, "mat2ppt.enum.BaseEnum"), v = ct.value; else, v = double(ct); end
        end
    end
end
