classdef BarChartXmlWriter < handle
%BARCHARTXMLWRITER  Default c:chartSpace for bar/column charts (P8-W4).
%
%   Ported from python-pptx 1.0.2: chart/xmlwriter.py::_BarChartXmlWriter

    properties (Access = private)
        chartType_
        chartData_
    end

    methods
        function obj = BarChartXmlWriter(chartType, chartData)
            obj.chartType_ = chartType;
            obj.chartData_ = chartData;
        end

        function xml = xml(obj)
            nl = char(10);
            xml = [ ...
                '<?xml version=''1.0'' encoding=''UTF-8'' standalone=''yes''?>' nl ...
                '<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" ' ...
                'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ' ...
                'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">' nl ...
                '  <c:date1904 val="0"/>' nl ...
                '  <c:chart>' nl ...
                '    <c:autoTitleDeleted val="0"/>' nl ...
                '    <c:plotArea>' nl ...
                '      <c:barChart>' nl ...
                obj.barDir_xml_() ...
                obj.grouping_xml_() ...
                obj.ser_xml_() ...
                obj.overlap_xml_() ...
                '        <c:axId val="-2068027336"/>' nl ...
                '        <c:axId val="-2113994440"/>' nl ...
                '      </c:barChart>' nl ...
                obj.cat_ax_xml_() ...
                '      <c:valAx>' nl ...
                '        <c:axId val="-2113994440"/>' nl ...
                '        <c:scaling/>' nl ...
                '        <c:delete val="0"/>' nl ...
                sprintf('        <c:axPos val="%s"/>%s', obj.val_ax_pos_(), nl) ...
                '        <c:majorGridlines/>' nl ...
                '        <c:majorTickMark val="out"/>' nl ...
                '        <c:minorTickMark val="none"/>' nl ...
                '        <c:tickLblPos val="nextTo"/>' nl ...
                '        <c:crossAx val="-2068027336"/>' nl ...
                '        <c:crosses val="autoZero"/>' nl ...
                '      </c:valAx>' nl ...
                '    </c:plotArea>' nl ...
                '    <c:dispBlanksAs val="gap"/>' nl ...
                '  </c:chart>' nl ...
                '  <c:txPr>' nl ...
                '    <a:bodyPr/>' nl ...
                '    <a:lstStyle/>' nl ...
                '    <a:p>' nl ...
                '      <a:pPr>' nl ...
                '        <a:defRPr sz="1800"/>' nl ...
                '      </a:pPr>' nl ...
                '      <a:endParaRPr lang="en-US"/>' nl ...
                '    </a:p>' nl ...
                '  </c:txPr>' nl ...
                '</c:chartSpace>' nl ...
                ];
        end
    end

    methods (Access = private)
        function v = ct_val_(obj)
            ct = obj.chartType_;
            if isa(ct, "mat2ppt.enum.BaseEnum")
                v = ct.value;
            else
                v = double(ct);
            end
        end

        function s = barDir_xml_(obj)
            XL = mat2ppt.enum.XL_CHART_TYPE;
            v = obj.ct_val_();
            nl = char(10);
            if any(v == [XL.BAR_CLUSTERED.value, XL.BAR_STACKED.value, XL.BAR_STACKED_100.value])
                s = ['        <c:barDir val="bar"/>' nl];
            elseif any(v == [XL.COLUMN_CLUSTERED.value, XL.COLUMN_STACKED.value, XL.COLUMN_STACKED_100.value])
                s = ['        <c:barDir val="col"/>' nl];
            else
                error("mat2ppt:ValueError", "no barDir for chart type %g", v);
            end
        end

        function s = grouping_xml_(obj)
            XL = mat2ppt.enum.XL_CHART_TYPE;
            v = obj.ct_val_();
            nl = char(10);
            if any(v == [XL.BAR_CLUSTERED.value, XL.COLUMN_CLUSTERED.value])
                s = ['        <c:grouping val="clustered"/>' nl];
            elseif any(v == [XL.BAR_STACKED.value, XL.COLUMN_STACKED.value])
                s = ['        <c:grouping val="stacked"/>' nl];
            elseif any(v == [XL.BAR_STACKED_100.value, XL.COLUMN_STACKED_100.value])
                s = ['        <c:grouping val="percentStacked"/>' nl];
            else
                error("mat2ppt:ValueError", "no grouping for chart type %g", v);
            end
        end

        function s = overlap_xml_(obj)
            XL = mat2ppt.enum.XL_CHART_TYPE;
            v = obj.ct_val_();
            nl = char(10);
            stacked = [XL.BAR_STACKED.value, XL.BAR_STACKED_100.value, ...
                XL.COLUMN_STACKED.value, XL.COLUMN_STACKED_100.value];
            if any(v == stacked)
                s = ['        <c:overlap val="100"/>' nl];
            else
                s = '';
            end
        end

        function s = cat_ax_pos_(obj)
            XL = mat2ppt.enum.XL_CHART_TYPE;
            v = obj.ct_val_();
            if any(v == [XL.BAR_CLUSTERED.value, XL.BAR_STACKED.value, XL.BAR_STACKED_100.value])
                s = 'l';
            else
                s = 'b';
            end
        end

        function s = val_ax_pos_(obj)
            XL = mat2ppt.enum.XL_CHART_TYPE;
            v = obj.ct_val_();
            if any(v == [XL.BAR_CLUSTERED.value, XL.BAR_STACKED.value, XL.BAR_STACKED_100.value])
                s = 'b';
            else
                s = 'l';
            end
        end

        function s = cat_ax_xml_(obj)
            s = sprintf([ ...
                '      <c:catAx>\n' ...
                '        <c:axId val="-2068027336"/>\n' ...
                '        <c:scaling>\n' ...
                '          <c:orientation val="minMax"/>\n' ...
                '        </c:scaling>\n' ...
                '        <c:delete val="0"/>\n' ...
                '        <c:axPos val="%s"/>\n' ...
                '        <c:majorTickMark val="out"/>\n' ...
                '        <c:minorTickMark val="none"/>\n' ...
                '        <c:tickLblPos val="nextTo"/>\n' ...
                '        <c:crossAx val="-2113994440"/>\n' ...
                '        <c:crosses val="autoZero"/>\n' ...
                '        <c:auto val="1"/>\n' ...
                '        <c:lblAlgn val="ctr"/>\n' ...
                '        <c:lblOffset val="100"/>\n' ...
                '        <c:noMultiLvlLbl val="0"/>\n' ...
                '      </c:catAx>\n'], obj.cat_ax_pos_());
        end

        function s = ser_xml_(obj)
            data = obj.chartData_;
            s = '';
            for i = 1:data.series_count()
                sw = mat2ppt.chart.CategorySeriesXmlWriter(data, i);
                pyIdx = i - 1;  % XML idx/order are 0-based like python-pptx
                s = [s, sprintf([ ...
                    '        <c:ser>\n' ...
                    '          <c:idx val="%d"/>\n' ...
                    '          <c:order val="%d"/>\n' ...
                    '%s%s%s' ...
                    '        </c:ser>\n'], ...
                    pyIdx, pyIdx, sw.tx_xml(), sw.cat_xml(), sw.val_xml())]; %#ok<AGROW>
            end
        end
    end
end
