classdef BubbleChartXmlWriter < handle
%BUBBLECHARTXMLWRITER  bubbleChart XML (R5-W4).
%
%   Ported from python-pptx _BubbleChartXmlWriter (simplified)

    properties (Access = private)
        chartType_
        chartData_
    end

    methods
        function obj = BubbleChartXmlWriter(chartType, chartData)
            obj.chartType_ = chartType;
            obj.chartData_ = chartData;
        end

        function xml = xml(obj)
            nl = char(10);
            xml = [ ...
                '<?xml version=''1.0'' encoding=''UTF-8'' standalone=''yes''?>' nl ...
                '<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" ' ...
                'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ' ...
                'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">' nl ...
                '  <c:chart>' nl ...
                '    <c:plotArea>' nl ...
                '      <c:bubbleChart>' nl ...
                obj.ser_xml_() ...
                '        <c:axId val="-2128940872"/>' nl ...
                '        <c:axId val="-2129643912"/>' nl ...
                '      </c:bubbleChart>' nl ...
                '      <c:valAx>' nl ...
                '        <c:axId val="-2128940872"/>' nl ...
                '        <c:scaling/>' nl ...
                '        <c:axPos val="b"/>' nl ...
                '        <c:crossAx val="-2129643912"/>' nl ...
                '      </c:valAx>' nl ...
                '      <c:valAx>' nl ...
                '        <c:axId val="-2129643912"/>' nl ...
                '        <c:scaling/>' nl ...
                '        <c:axPos val="l"/>' nl ...
                '        <c:majorGridlines/>' nl ...
                '        <c:crossAx val="-2128940872"/>' nl ...
                '      </c:valAx>' nl ...
                '    </c:plotArea>' nl ...
                '    <c:dispBlanksAs val="gap"/>' nl ...
                '  </c:chart>' nl ...
                '</c:chartSpace>' nl];
        end
    end

    methods (Access = private)
        function s = ser_xml_(obj)
            data = obj.chartData_;
            s = '';
            for i = 1:data.series_count()
                ser = data.series(i);
                pyIdx = i - 1;
                name = mat2ppt.oxml.escape_xml_text_(ser.name);
                n = numel(ser.xs);
                xpts = ''; ypts = ''; spts = '';
                for j = 1:n
                    xpts = [xpts, sprintf('                <c:pt idx="%d"><c:v>%g</c:v></c:pt>\n', j-1, ser.xs(j))]; %#ok<AGROW>
                    ypts = [ypts, sprintf('                <c:pt idx="%d"><c:v>%g</c:v></c:pt>\n', j-1, ser.ys(j))]; %#ok<AGROW>
                    sz = 1;
                    if numel(ser.sizes) >= j, sz = ser.sizes(j); end
                    spts = [spts, sprintf('                <c:pt idx="%d"><c:v>%g</c:v></c:pt>\n', j-1, sz)]; %#ok<AGROW>
                end
                s = [s, sprintf([ ...
                    '        <c:ser>\n' ...
                    '          <c:idx val="%d"/>\n' ...
                    '          <c:order val="%d"/>\n' ...
                    '          <c:tx><c:v>%s</c:v></c:tx>\n' ...
                    '          <c:xVal><c:numLit><c:ptCount val="%d"/>\n%s          </c:numLit></c:xVal>\n' ...
                    '          <c:yVal><c:numLit><c:ptCount val="%d"/>\n%s          </c:numLit></c:yVal>\n' ...
                    '          <c:bubbleSize><c:numLit><c:ptCount val="%d"/>\n%s          </c:numLit></c:bubbleSize>\n' ...
                    '        </c:ser>\n'], ...
                    pyIdx, pyIdx, name, n, xpts, n, ypts, n, spts)]; %#ok<AGROW>
            end
        end
    end
end
