classdef CategorySeriesXmlWriter < handle
%CATEGORYSERIESXMLWRITER  c:tx / c:cat / c:val snippets for category series (P8-W4).
%
%   Ported from python-pptx 1.0.2: chart/xmlwriter.py::_CategorySeriesXmlWriter

    properties (Access = private)
        chartData_
        seriesIdx_   % 1-based MATLAB index
    end

    methods
        function obj = CategorySeriesXmlWriter(chartData, seriesIdx)
            obj.chartData_ = chartData;
            obj.seriesIdx_ = double(seriesIdx);
        end

        function xml = tx_xml(obj)
            s = obj.chartData_.series(obj.seriesIdx_);
            name = mat2ppt.oxml.escape_xml_text_(s.name);
            ref = obj.chartData_.series_name_ref(obj.seriesIdx_);
            xml = sprintf([ ...
                '          <c:tx>\n' ...
                '            <c:strRef>\n' ...
                '              <c:f>%s</c:f>\n' ...
                '              <c:strCache>\n' ...
                '                <c:ptCount val="1"/>\n' ...
                '                <c:pt idx="0">\n' ...
                '                  <c:v>%s</c:v>\n' ...
                '                </c:pt>\n' ...
                '              </c:strCache>\n' ...
                '            </c:strRef>\n' ...
                '          </c:tx>\n'], ref, name);
        end

        function xml = cat_xml(obj)
            data = obj.chartData_;
            n = data.category_count();
            ref = data.categories_ref();
            labels = data.get_categories();
            pts = '';
            for i = 1:n
                lab = mat2ppt.oxml.escape_xml_text_(labels{i});
                pts = [pts, sprintf([ ...
                    '                <c:pt idx="%d">\n' ...
                    '                  <c:v>%s</c:v>\n' ...
                    '                </c:pt>\n'], i - 1, lab)]; %#ok<AGROW>
            end
            xml = sprintf([ ...
                '          <c:cat>\n' ...
                '            <c:strRef>\n' ...
                '              <c:f>%s</c:f>\n' ...
                '              <c:strCache>\n' ...
                '                <c:ptCount val="%d"/>\n' ...
                '%s' ...
                '              </c:strCache>\n' ...
                '            </c:strRef>\n' ...
                '          </c:cat>\n'], ref, n, pts);
        end

        function xml = val_xml(obj)
            s = obj.chartData_.series(obj.seriesIdx_);
            vals = s.values;
            n = numel(vals);
            ref = obj.chartData_.values_ref(obj.seriesIdx_);
            nf = s.number_format;
            if isempty(nf)
                nf = 'General';
            else
                nf = char(string(nf));
            end
            pts = '';
            for i = 1:n
                v = vals(i);
                if isempty(v) || (isnumeric(v) && ~isfinite(v))
                    continue
                end
                pts = [pts, sprintf([ ...
                    '                <c:pt idx="%d">\n' ...
                    '                  <c:v>%g</c:v>\n' ...
                    '                </c:pt>\n'], i - 1, v)]; %#ok<AGROW>
            end
            xml = sprintf([ ...
                '          <c:val>\n' ...
                '            <c:numRef>\n' ...
                '              <c:f>%s</c:f>\n' ...
                '              <c:numCache>\n' ...
                '                <c:formatCode>%s</c:formatCode>\n' ...
                '                <c:ptCount val="%d"/>\n' ...
                '%s' ...
                '              </c:numCache>\n' ...
                '            </c:numRef>\n' ...
                '          </c:val>\n'], ref, nf, n, pts);
        end
    end
end
