classdef LineChartXmlWriter < handle
%LINECHARTXMLWRITER  Default c:chartSpace for line charts (P8-W4).
%
%   Ported from python-pptx 1.0.2: chart/xmlwriter.py::_LineChartXmlWriter

    properties (Access = private)
        chartType_
        chartData_
    end

    methods
        function obj = LineChartXmlWriter(chartType, chartData)
            obj.chartType_ = chartType;
            obj.chartData_ = chartData;
        end

        function xml = xml(obj)
            nl = char(10);
            xml = [ ...
                '<?xml version=''1.0'' encoding=''UTF-8'' standalone=''yes''?>' nl ...
                '<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" ' ...
                'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ' ...
                'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">' nl ...
                '  <c:date1904 val="0"/>' nl ...
                '  <c:chart>' nl ...
                '    <c:autoTitleDeleted val="0"/>' nl ...
                '    <c:plotArea>' nl ...
                '      <c:lineChart>' nl ...
                obj.grouping_xml_() ...
                '        <c:varyColors val="0"/>' nl ...
                obj.ser_xml_() ...
                '        <c:marker val="1"/>' nl ...
                '        <c:smooth val="0"/>' nl ...
                '        <c:axId val="2118791784"/>' nl ...
                '        <c:axId val="2140495176"/>' nl ...
                '      </c:lineChart>' nl ...
                obj.cat_ax_xml_() ...
                '      <c:valAx>' nl ...
                '        <c:axId val="2140495176"/>' nl ...
                '        <c:scaling/>' nl ...
                '        <c:delete val="0"/>' nl ...
                '        <c:axPos val="l"/>' nl ...
                '        <c:majorGridlines/>' nl ...
                '        <c:majorTickMark val="out"/>' nl ...
                '        <c:minorTickMark val="none"/>' nl ...
                '        <c:tickLblPos val="nextTo"/>' nl ...
                '        <c:crossAx val="2118791784"/>' nl ...
                '        <c:crosses val="autoZero"/>' nl ...
                '      </c:valAx>' nl ...
                '    </c:plotArea>' nl ...
                '    <c:legend>' nl ...
                '      <c:legendPos val="r"/>' nl ...
                '      <c:layout/>' nl ...
                '      <c:overlay val="0"/>' nl ...
                '    </c:legend>' nl ...
                '    <c:plotVisOnly val="1"/>' nl ...
                '    <c:dispBlanksAs val="gap"/>' nl ...
                '    <c:showDLblsOverMax val="0"/>' nl ...
                '  </c:chart>' nl ...
                '  <c:txPr>' nl ...
                '    <a:bodyPr/>' nl ...
                '    <a:lstStyle/>' nl ...
                '    <a:p>' nl ...
                '      <a:pPr>' nl ...
                '        <a:defRPr sz="1800"/>' nl ...
                '      </a:pPr>' nl ...
                '      <a:endParaRPr lang="en-US"/>' nl ...
                '    </a:p>' nl ...
                '  </c:txPr>' nl ...
                '</c:chartSpace>' nl ...
                ];
        end
    end

    methods (Access = private)
        function v = ct_val_(obj)
            ct = obj.chartType_;
            if isa(ct, "mat2ppt.enum.BaseEnum")
                v = ct.value;
            else
                v = double(ct);
            end
        end

        function s = grouping_xml_(obj)
            XL = mat2ppt.enum.XL_CHART_TYPE;
            v = obj.ct_val_();
            nl = char(10);
            if any(v == [XL.LINE_STACKED.value, XL.LINE_MARKERS_STACKED.value])
                s = ['        <c:grouping val="stacked"/>' nl];
            elseif any(v == [XL.LINE_STACKED_100.value, XL.LINE_MARKERS_STACKED_100.value])
                s = ['        <c:grouping val="percentStacked"/>' nl];
            else
                s = ['        <c:grouping val="standard"/>' nl];
            end
        end

        function s = cat_ax_xml_(obj)
            nl = char(10);
            s = [ ...
                '      <c:catAx>' nl ...
                '        <c:axId val="2118791784"/>' nl ...
                '        <c:scaling>' nl ...
                '          <c:orientation val="minMax"/>' nl ...
                '        </c:scaling>' nl ...
                '        <c:delete val="0"/>' nl ...
                '        <c:axPos val="b"/>' nl ...
                '        <c:majorTickMark val="out"/>' nl ...
                '        <c:minorTickMark val="none"/>' nl ...
                '        <c:tickLblPos val="nextTo"/>' nl ...
                '        <c:crossAx val="2140495176"/>' nl ...
                '        <c:crosses val="autoZero"/>' nl ...
                '        <c:auto val="1"/>' nl ...
                '        <c:lblAlgn val="ctr"/>' nl ...
                '        <c:lblOffset val="100"/>' nl ...
                '        <c:noMultiLvlLbl val="0"/>' nl ...
                '      </c:catAx>' nl ...
                ];
        end

        function s = ser_xml_(obj)
            data = obj.chartData_;
            s = '';
            for i = 1:data.series_count()
                sw = mat2ppt.chart.CategorySeriesXmlWriter(data, i);
                pyIdx = i - 1;
                s = [s, sprintf([ ...
                    '        <c:ser>\n' ...
                    '          <c:idx val="%d"/>\n' ...
                    '          <c:order val="%d"/>\n' ...
                    '%s%s%s' ...
                    '        </c:ser>\n'], ...
                    pyIdx, pyIdx, sw.tx_xml(), sw.cat_xml(), sw.val_xml())]; %#ok<AGROW>
            end
        end
    end
end
