classdef PieChartXmlWriter < handle
%PIECHARTXMLWRITER  Default c:chartSpace for pie/doughnut charts (P8-W5).
%
%   Ported from python-pptx 1.0.2: chart/xmlwriter.py::_PieChartXmlWriter

    properties (Access = private)
        chartType_
        chartData_
    end

    methods
        function obj = PieChartXmlWriter(chartType, chartData)
            obj.chartType_ = chartType;
            obj.chartData_ = chartData;
        end

        function xml = xml(obj)
            nl = char(10);
            v = obj.ct_val_();
            XL = mat2ppt.enum.XL_CHART_TYPE;
            isDoughnut = any(v == [XL.DOUGHNUT.value, XL.DOUGHNUT_EXPLODED.value]);
            if isDoughnut
                plotOpen = '      <c:doughnutChart>';
                plotClose = '      </c:doughnutChart>';
                hole = ['        <c:holeSize val="50"/>' nl];
            else
                plotOpen = '      <c:pieChart>';
                plotClose = '      </c:pieChart>';
                hole = '';
            end
            xml = [ ...
                '<?xml version=''1.0'' encoding=''UTF-8'' standalone=''yes''?>' nl ...
                '<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" ' ...
                'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ' ...
                'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">' nl ...
                '  <c:chart>' nl ...
                '    <c:autoTitleDeleted val="0"/>' nl ...
                '    <c:plotArea>' nl ...
                plotOpen nl ...
                '        <c:varyColors val="1"/>' nl ...
                obj.ser_xml_() ...
                hole ...
                plotClose nl ...
                '    </c:plotArea>' nl ...
                '    <c:dispBlanksAs val="gap"/>' nl ...
                '  </c:chart>' nl ...
                '  <c:txPr>' nl ...
                '    <a:bodyPr/>' nl ...
                '    <a:lstStyle/>' nl ...
                '    <a:p>' nl ...
                '      <a:pPr>' nl ...
                '        <a:defRPr sz="1800"/>' nl ...
                '      </a:pPr>' nl ...
                '      <a:endParaRPr lang="en-US"/>' nl ...
                '    </a:p>' nl ...
                '  </c:txPr>' nl ...
                '</c:chartSpace>' nl ...
                ];
        end
    end

    methods (Access = private)
        function v = ct_val_(obj)
            ct = obj.chartType_;
            if isa(ct, "mat2ppt.enum.BaseEnum")
                v = ct.value;
            else
                v = double(ct);
            end
        end

        function s = explosion_xml_(obj)
            XL = mat2ppt.enum.XL_CHART_TYPE;
            v = obj.ct_val_();
            nl = char(10);
            if any(v == [XL.PIE_EXPLODED.value, XL.DOUGHNUT_EXPLODED.value])
                s = ['          <c:explosion val="25"/>' nl];
            else
                s = '';
            end
        end

        function s = ser_xml_(obj)
            data = obj.chartData_;
            % pie uses first series only (python-pptx)
            sw = mat2ppt.chart.CategorySeriesXmlWriter(data, 1);
            s = sprintf([ ...
                '        <c:ser>\n' ...
                '          <c:idx val="0"/>\n' ...
                '          <c:order val="0"/>\n' ...
                '%s%s%s%s' ...
                '        </c:ser>\n'], ...
                sw.tx_xml(), obj.explosion_xml_(), sw.cat_xml(), sw.val_xml());
        end
    end
end
