classdef RadarChartXmlWriter < handle
%RADARCHARTXMLWRITER  c:chartSpace for radar charts (R5-W5).
%
%   Ported from python-pptx chart/xmlwriter.py::_RadarChartXmlWriter

    properties (Access = private)
        chartType_
        chartData_
    end

    methods
        function obj = RadarChartXmlWriter(chartType, chartData)
            obj.chartType_ = chartType;
            obj.chartData_ = chartData;
        end

        function xml = xml(obj)
            nl = char(10);
            style = 'marker';
            XL = mat2ppt.enum.XL_CHART_TYPE;
            if obj.ct_val_() == XL.RADAR_FILLED.value
                style = 'filled';
            end
            xml = [ ...
                '<?xml version=''1.0'' encoding=''UTF-8'' standalone=''yes''?>' nl ...
                '<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" ' ...
                'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ' ...
                'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">' nl ...
                '  <c:date1904 val="0"/>' nl ...
                '  <c:chart>' nl ...
                '    <c:autoTitleDeleted val="0"/>' nl ...
                '    <c:plotArea>' nl ...
                '      <c:radarChart>' nl ...
                sprintf('        <c:radarStyle val="%s"/>%s', style, nl) ...
                '        <c:varyColors val="0"/>' nl ...
                obj.ser_xml_() ...
                '        <c:axId val="2073612648"/>' nl ...
                '        <c:axId val="-2112772216"/>' nl ...
                '      </c:radarChart>' nl ...
                '      <c:catAx>' nl ...
                '        <c:axId val="2073612648"/>' nl ...
                '        <c:scaling/>' nl ...
                '        <c:axPos val="b"/>' nl ...
                '        <c:crossAx val="-2112772216"/>' nl ...
                '      </c:catAx>' nl ...
                '      <c:valAx>' nl ...
                '        <c:axId val="-2112772216"/>' nl ...
                '        <c:scaling/>' nl ...
                '        <c:axPos val="l"/>' nl ...
                '        <c:majorGridlines/>' nl ...
                '        <c:crossAx val="2073612648"/>' nl ...
                '      </c:valAx>' nl ...
                '    </c:plotArea>' nl ...
                '    <c:dispBlanksAs val="gap"/>' nl ...
                '  </c:chart>' nl ...
                '</c:chartSpace>' nl];
        end
    end

    methods (Access = private)
        function s = ser_xml_(obj)
            data = obj.chartData_;
            s = '';
            XL = mat2ppt.enum.XL_CHART_TYPE;
            mark = '';
            if obj.ct_val_() == XL.RADAR.value
                mark = ['          <c:marker>' char(10) '            <c:symbol val="none"/>' char(10) '          </c:marker>' char(10)];
            end
            for i = 1:data.series_count()
                sw = mat2ppt.chart.CategorySeriesXmlWriter(data, i);
                pyIdx = i - 1;
                s = [s, sprintf([ ...
                    '        <c:ser>\n' ...
                    '          <c:idx val="%d"/>\n' ...
                    '          <c:order val="%d"/>\n' ...
                    '%s%s%s%s' ...
                    '        </c:ser>\n'], ...
                    pyIdx, pyIdx, sw.tx_xml(), mark, sw.cat_xml(), sw.val_xml())]; %#ok<AGROW>
            end
        end
        function v = ct_val_(obj)
            ct = obj.chartType_;
            if isa(ct, "mat2ppt.enum.BaseEnum"), v = ct.value; else, v = double(ct); end
        end
    end
end
