classdef XyChartXmlWriter < handle
%XYCHARTXMLWRITER  scatterChart XML (R5-W3).
%
%   Ported from python-pptx _XyChartXmlWriter (simplified)

    properties (Access = private)
        chartType_
        chartData_
    end

    methods
        function obj = XyChartXmlWriter(chartType, chartData)
            obj.chartType_ = chartType;
            obj.chartData_ = chartData;
        end

        function xml = xml(obj)
            nl = char(10);
            style = 'lineMarker';
            XL = mat2ppt.enum.XL_CHART_TYPE;
            v = obj.ct_val_();
            if any(v == [XL.XY_SCATTER_SMOOTH.value, XL.XY_SCATTER_SMOOTH_NO_MARKERS.value])
                style = 'smoothMarker';
            end
            xml = [ ...
                '<?xml version=''1.0'' encoding=''UTF-8'' standalone=''yes''?>' nl ...
                '<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" ' ...
                'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ' ...
                'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">' nl ...
                '  <c:chart>' nl ...
                '    <c:plotArea>' nl ...
                '      <c:scatterChart>' nl ...
                sprintf('        <c:scatterStyle val="%s"/>%s', style, nl) ...
                '        <c:varyColors val="0"/>' nl ...
                obj.ser_xml_() ...
                '        <c:axId val="-2128940872"/>' nl ...
                '        <c:axId val="-2129643912"/>' nl ...
                '      </c:scatterChart>' nl ...
                '      <c:valAx>' nl ...
                '        <c:axId val="-2128940872"/>' nl ...
                '        <c:scaling/>' nl ...
                '        <c:axPos val="b"/>' nl ...
                '        <c:crossAx val="-2129643912"/>' nl ...
                '      </c:valAx>' nl ...
                '      <c:valAx>' nl ...
                '        <c:axId val="-2129643912"/>' nl ...
                '        <c:scaling/>' nl ...
                '        <c:axPos val="l"/>' nl ...
                '        <c:majorGridlines/>' nl ...
                '        <c:crossAx val="-2128940872"/>' nl ...
                '      </c:valAx>' nl ...
                '    </c:plotArea>' nl ...
                '    <c:dispBlanksAs val="gap"/>' nl ...
                '  </c:chart>' nl ...
                '</c:chartSpace>' nl];
        end
    end

    methods (Access = private)
        function s = ser_xml_(obj)
            data = obj.chartData_;
            s = '';
            XL = mat2ppt.enum.XL_CHART_TYPE;
            v = obj.ct_val_();
            noMark = any(v == [XL.XY_SCATTER_LINES_NO_MARKERS.value, XL.XY_SCATTER_SMOOTH_NO_MARKERS.value]);
            for i = 1:data.series_count()
                ser = data.series(i);
                pyIdx = i - 1;
                name = mat2ppt.oxml.escape_xml_text_(ser.name);
                n = numel(ser.xs);
                xpts = ''; ypts = '';
                for j = 1:n
                    xpts = [xpts, sprintf('                <c:pt idx="%d"><c:v>%g</c:v></c:pt>\n', j-1, ser.xs(j))]; %#ok<AGROW>
                    ypts = [ypts, sprintf('                <c:pt idx="%d"><c:v>%g</c:v></c:pt>\n', j-1, ser.ys(j))]; %#ok<AGROW>
                end
                mark = '';
                if noMark || v == XL.XY_SCATTER.value
                    if noMark
                        mark = ['          <c:marker>' char(10) '            <c:symbol val="none"/>' char(10) '          </c:marker>' char(10)];
                    end
                end
                spPr = '';
                if v == XL.XY_SCATTER.value
                    spPr = ['          <c:spPr>' char(10) '            <a:ln w="47625"><a:noFill/></a:ln>' char(10) '          </c:spPr>' char(10)];
                end
                s = [s, sprintf([ ...
                    '        <c:ser>\n' ...
                    '          <c:idx val="%d"/>\n' ...
                    '          <c:order val="%d"/>\n' ...
                    '          <c:tx><c:v>%s</c:v></c:tx>\n' ...
                    '%s%s' ...
                    '          <c:xVal><c:numLit><c:ptCount val="%d"/>\n%s          </c:numLit></c:xVal>\n' ...
                    '          <c:yVal><c:numLit><c:ptCount val="%d"/>\n%s          </c:numLit></c:yVal>\n' ...
                    '          <c:smooth val="0"/>\n' ...
                    '        </c:ser>\n'], ...
                    pyIdx, pyIdx, name, spPr, mark, n, xpts, n, ypts)]; %#ok<AGROW>
            end
        end
        function v = ct_val_(obj)
            ct = obj.chartType_;
            if isa(ct, "mat2ppt.enum.BaseEnum"), v = ct.value; else, v = double(ct); end
        end
    end
end
