%% demo.m — Recreate 21_Dropbox_Religion__Rupnik_Saturno_Clericalism via Mat2Ppt public API
% Source: 21_Dropbox_Religion__Rupnik_Saturno_Clericalism.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 4
img = fullfile(assets, 'image1.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(436084), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(5449019));
end

% TextBox 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(602673), mat2ppt.util.Emu(5885103), mat2ppt.util.Emu(10986654), mat2ppt.util.Emu(523220));
sp.text_frame().text = 'One of these is a symbol of scandal and clericalism.  The other is a hat.';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);
