%% demo.m — Recreate 03_Box_Secretary__ArtNonprofit_Info_Planning_Meeting_20201220 via Mat2Ppt public API
% Source: 03_Box_Secretary__ArtNonprofit_Info_Planning_Meeting_20201220.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525929), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638881), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Art Non-profit';

% Subtitle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Informational and Planning MeetingDecember 20, 2020';


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525929), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638881), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Overview';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(493095), mat2ppt.util.Emu(1132764), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(4651451));
sp.text_frame().text = 'Summary of Current Project and StatusOverview of Potential Non-profit Purpose and GoalsSurvey of Participants and Potential Next Steps';


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525929), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638881), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Holy Child Project Overview';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(493095), mat2ppt.util.Emu(1160585), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(4623630));
sp.text_frame().text = 'Mother Seton Hall art schema finishedFive main hallway sections, plus intro, closing, and side hallwaysFocus is on reproductions of masterpiece paintings and will not include photos of statues and other architectureEach main section to cover an era of history Also looking to highlight art history Intro section complete10 paintings for just over $10k Modern Era Funding Promised – Currently in RFQ StageTwo pieces awaiting final down select15 paintings for $10.5k-14kFundraising and final selection remains for following sectionsCradle of Civilization and OT Greece and Rome Paschal MysteryEarly Church to Medieval EraEstimated Costs remaining: ~40 paintings for $35k plus lightingPlanning not yet begun for Blessed Miguel Pro Hall';

% Rectangle 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(7996518), mat2ppt.util.Emu(2586006), mat2ppt.util.Emu(4195482), mat2ppt.util.Emu(1938992));
sp.text_frame().text = 'Mother Seton Hall Nearly 1/3 Complete!!!';


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525929), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638881), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(493095), mat2ppt.util.Emu(1226), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1072559));
sp.text_frame().text = 'Mother Seton Hall Art Schema';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(1436528), mat2ppt.util.Emu(4766554), mat2ppt.util.Emu(2863098), mat2ppt.util.Emu(1384625));
sp.text_frame().text = 'CompletedIn-progressPlanning Stages';

% picture Picture 4
img = fullfile(assets, 'image4.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(707407), mat2ppt.util.Emu(1155858), mat2ppt.util.Emu(9944387), mat2ppt.util.Emu(3686175));
end

% connector Straight Connector 7
sh.add_connector('line', mat2ppt.util.Emu(856034), mat2ppt.util.Emu(3196147), mat2ppt.util.Emu(2597285), mat2ppt.util.Emu(3196147));

% connector Straight Connector 8
sh.add_connector('line', mat2ppt.util.Emu(2908571), mat2ppt.util.Emu(3225331), mat2ppt.util.Emu(5332530), mat2ppt.util.Emu(3225331));

% connector Straight Connector 13
sh.add_connector('line', mat2ppt.util.Emu(856034), mat2ppt.util.Emu(2755158), mat2ppt.util.Emu(2597285), mat2ppt.util.Emu(2755158));

% connector Straight Connector 14
sh.add_connector('line', mat2ppt.util.Emu(856033), mat2ppt.util.Emu(4026238), mat2ppt.util.Emu(1643974), mat2ppt.util.Emu(4026238));

% connector Straight Connector 16
sh.add_connector('line', mat2ppt.util.Emu(875488), mat2ppt.util.Emu(4002527), mat2ppt.util.Emu(875489), mat2ppt.util.Emu(3196147));

% connector Straight Connector 18
sh.add_connector('line', mat2ppt.util.Emu(5332530), mat2ppt.util.Emu(3338820), mat2ppt.util.Emu(5750894), mat2ppt.util.Emu(3338820));

% connector Straight Connector 20
sh.add_connector('line', mat2ppt.util.Emu(2908571), mat2ppt.util.Emu(2776845), mat2ppt.util.Emu(5332530), mat2ppt.util.Emu(2776845));

% connector Straight Connector 23
sh.add_connector('line', mat2ppt.util.Emu(5658256), mat2ppt.util.Emu(2776845), mat2ppt.util.Emu(7859949), mat2ppt.util.Emu(2776845));

% connector Straight Connector 25
sh.add_connector('line', mat2ppt.util.Emu(6066816), mat2ppt.util.Emu(3197366), mat2ppt.util.Emu(7840493), mat2ppt.util.Emu(3197366));

% connector Straight Connector 27
sh.add_connector('line', mat2ppt.util.Emu(8164749), mat2ppt.util.Emu(3205875), mat2ppt.util.Emu(10340502), mat2ppt.util.Emu(3205875));

% connector Straight Connector 29
sh.add_connector('line', mat2ppt.util.Emu(8164749), mat2ppt.util.Emu(2776845), mat2ppt.util.Emu(9377464), mat2ppt.util.Emu(2776845));

% connector Straight Connector 31
sh.add_connector('line', mat2ppt.util.Emu(6086271), mat2ppt.util.Emu(3729144), mat2ppt.util.Emu(6086271), mat2ppt.util.Emu(3196147));

% connector Straight Connector 33
sh.add_connector('line', mat2ppt.util.Emu(5661497), mat2ppt.util.Emu(2597285), mat2ppt.util.Emu(5661497), mat2ppt.util.Emu(2222162));

% connector Straight Connector 34
sh.add_connector('line', mat2ppt.util.Emu(5371442), mat2ppt.util.Emu(2776845), mat2ppt.util.Emu(5371442), mat2ppt.util.Emu(2243848));

% connector Straight Connector 35
sh.add_connector('line', mat2ppt.util.Emu(5750894), mat2ppt.util.Emu(3531943), mat2ppt.util.Emu(5750894), mat2ppt.util.Emu(3338820));


%% ===== Slide 5 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525929), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638881), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(493095), mat2ppt.util.Emu(1227), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1141774));
sp.text_frame().text = 'Non-profit PurposesAsset Protection';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(493094), mat2ppt.util.Emu(1485899), mat2ppt.util.Emu(11332560), mat2ppt.util.Emu(4298315));
sp.text_frame().text = 'Asset protection is critical to fundraising in parishes/dioceses where future friendliness toward classical education and great art is in questionBarbarian bishops and modernist priests have destroyed much church art and sold off numerous assets to pay abuse settlementsMost people have stories of friends/family saving church art from literal dumpstersNon-profit can hold assets in trust and give them away to other schools if unfriendly powers take control and want to dispose of the art';


%% ===== Slide 6 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525929), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638881), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(493095), mat2ppt.util.Emu(1227), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1141774));
sp.text_frame().text = 'Non-profit PurposesProject and Concept Promotion';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(493094), mat2ppt.util.Emu(1485899), mat2ppt.util.Emu(11332560), mat2ppt.util.Emu(4298315));
sp.text_frame().text = 'Holy Child is pioneering something newNever before have modern printing methods been combined with the ever-growing library of high resolution photos of museum paintings to bring the best masterpiece paintings in the western canon to schoolsThe classical school movement is rapidly expanding and pioneering new ways to bring the a traditional education to the modern worldMany schools would likely be interested if they could see this projectWays to promote conceptSpeak at educational conferencesNews coveragePublishing in academic journals and educational magazinesPartnerships with local art museumsPartnerships with other schools';


%% ===== Slide 7 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525929), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638881), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(493095), mat2ppt.util.Emu(1227), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1141774));
sp.text_frame().text = 'Non-profit PurposesConnecting School Communities and Museums';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(493094), mat2ppt.util.Emu(1143001), mat2ppt.util.Emu(11332560), mat2ppt.util.Emu(4641213));
sp.text_frame().text = 'Reproductions shouldn’t be the only art children seeMost masterpiece paintings live in museumsTraveling exhibits bring masterpieces to even smaller cities like AlbuquerqueReserving a section of wall to display the best of local art museums would encourage families to visitRequires working with museum staff to acquire rights and select pieces for displayProvides visibility of museum exhibits to school familiesProvides visibility of school in the wider communityWin-win for families, museum, and schoolStrong partnerships generate opportunity for positive media interest and coverageMuseum staff will likely lead this effort';


%% ===== Slide 8 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525929), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638881), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(493095), mat2ppt.util.Emu(1227), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1141774));
sp.text_frame().text = 'Non-profit PurposesConnecting Likeminded School Communities';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(493094), mat2ppt.util.Emu(1143001), mat2ppt.util.Emu(11332560), mat2ppt.util.Emu(4641213));
sp.text_frame().text = 'Serve as central resource to connect classical schools that want to implement this ideaProvide planning and logistical support to schools lacking expertiseCan help schools with planning and piece selectionHoly Child has already looked at thousands of paintings and has presentations with hundreds of potential candidatesProvide logistical support to schoolsConnect with Duraplaq and Derek BrooksDevelop connections to companies in other parts of  the country/world as time progressesProvide support to schools looking to circulate loaned paintingsSimilar to how most museums have traveling exhibitsHelp connect schools with their local art community';


%% ===== Slide 9 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525929), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638881), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(493095), mat2ppt.util.Emu(1226), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1106605));
sp.text_frame().text = 'Starting a Non-profit';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(562708), mat2ppt.util.Emu(1182569), mat2ppt.util.Emu(5533292), mat2ppt.util.Emu(4462095));
sp.text_frame().text = 'Decide on purpose for organization and general goalsFeedback - Disagreement on goals in previous slides or other ideas?Select board modelRecruit and vote on transition board members (with future in mind)Highlight business/non-profit experience, time, motivation, and art expertiseAvoid conflicts of interestDecide on committees - both business and art relatedVote on a name';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(5972908), mat2ppt.util.Emu(1559171), mat2ppt.util.Emu(6134100), mat2ppt.util.Emu(4462095));
sp.text_frame().text = 'Set board meeting dates for regular meetingsSet due dates and goals for tasksWrite Articles of Incorporation and BylawsSelect annual meeting date (mostly set in stone)Formally vote on board membersWork with volunteer legal help toSubmit paperwork to state of NMSubmit paperwork to IRSGet training for IRS paperwork and business aspects of tax deductibilityPrioritize art-related projects and get to workCan’t do everything at once – Figure out projects with high impact and low difficulty to begin';


%% ===== Slide 10 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525929), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638881), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2955441), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Questions and Feedback';


%% ===== Slide 11 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture MasterLogo_image2.jpeg
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(188120), mat2ppt.util.Emu(5525929), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1224229));
end

% picture MasterLogo_image3.jpg
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(10638881), mat2ppt.util.Emu(139366), mat2ppt.util.Emu(1410420), mat2ppt.util.Emu(1371600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Resources';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide1 sp used title-area default geom: Title 1
% GAP: slide1 sp used title-area default geom: Subtitle 2
% GAP: slide2 sp used title-area default geom: Title 1
% GAP: slide3 sp used title-area default geom: Title 1
% GAP: slide11 sp used title-area default geom: Title 1
% GAP: slide11 sp missing geom: Content Placeholder 2
