%% demo.m — Recreate 09_Dropbox_aAdela__FairiesAdela via Mat2Ppt public API
% Source: 09_Dropbox_aAdela__FairiesAdela.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(9144000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 5 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 6 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(5410200), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(3429000), mat2ppt.util.Emu(2057400));
sp.text_frame().text = 'Daisy Fairy';


%% ===== Slide 7 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 8 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(5389098), mat2ppt.util.Emu(2514600), mat2ppt.util.Emu(2535702), mat2ppt.util.Emu(685800));
sp.text_frame().text = 'Rose Fairy';


%% ===== Slide 9 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 10 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 11 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 12 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 13 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 14 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 15 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 16 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 17 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 18 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 19 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 20 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 21 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide1 sp missing geom: Title 1
% GAP: slide2 sp missing geom: Title 1
% GAP: slide2 pic incomplete: Picture 2
% GAP: slide3 sp missing geom: Title 1
% GAP: slide3 pic incomplete: Picture 4
% GAP: slide4 sp missing geom: Title 1
% GAP: slide4 pic incomplete: Picture 2
% GAP: slide5 sp missing geom: Title 3
% GAP: slide5 pic incomplete: Picture 2
% GAP: slide6 pic incomplete: Picture 2
% GAP: slide7 sp missing geom: Title 1
% GAP: slide7 pic incomplete: Picture 11
% GAP: slide8 pic incomplete: Picture 10
% GAP: slide9 sp missing geom: Title 1
% GAP: slide9 pic incomplete: Picture 4
% GAP: slide10 sp missing geom: Title 1
% GAP: slide10 pic incomplete: Picture 1
% GAP: slide11 sp missing geom: Title 1
% GAP: slide11 pic incomplete: Picture 1
% GAP: slide12 sp missing geom: Title 1
% GAP: slide12 pic incomplete: Picture 2
% GAP: slide13 sp missing geom: Title 1
% GAP: slide13 pic incomplete: Picture 4
% GAP: slide14 sp missing geom: Title 1
% GAP: slide14 pic incomplete: Picture 4
% GAP: slide15 sp missing geom: Title 1
% GAP: slide15 pic incomplete: Picture 2
% GAP: slide16 sp missing geom: Title 1
% GAP: slide16 pic incomplete: Picture 2
% GAP: slide17 sp missing geom: Title 1
% GAP: slide17 pic incomplete: Picture 2
% GAP: slide18 sp missing geom: Title 1
% GAP: slide18 pic incomplete: Picture 2
% GAP: slide19 sp missing geom: Title 1
% GAP: slide19 pic incomplete: Picture 2
% GAP: slide20 sp missing geom: Title 1
% GAP: slide20 pic incomplete: Picture 2
% GAP: slide21 sp missing geom: Title 1
% GAP: slide21 pic incomplete: Picture 2
