%% demo.m — Recreate 11_Dropbox_aEmmerich__Denmark_Pictures via Mat2Ppt public API
% Source: 11_Dropbox_aEmmerich__Denmark_Pictures.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 4
img = fullfile(assets, 'image1.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5460490), mat2ppt.util.Emu(2862071), mat2ppt.util.Emu(1271019), mat2ppt.util.Emu(1133858));
end

% picture Picture 6
img = fullfile(assets, 'image2.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6731510), mat2ppt.util.Emu(2862071), mat2ppt.util.Emu(2675538), mat2ppt.util.Emu(1137374));
end


prs.save(outPath);
fprintf("Wrote %s\n", outPath);
