%% demo.m — Recreate 19_Dropbox_Real_Estate__Coombs_500 Chama_Proof that Moving is a Good Idea via Mat2Ppt public API
% Source: 19_Dropbox_Real_Estate__Coombs_500 Chama_Proof that Moving is a Good Idea.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(9144000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Incontrovertible Proof that Moving to Town is a Step Up in the World for the Coombs Family';

% Subtitle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'December 31, 2014 @1454';


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Only Warm Bedroom in House';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(8305800), mat2ppt.util.Emu(1295399));
sp.text_frame().text = 'There is the one and only warm room in the housePolyisocyanurate insulation covers outside wall including single pane windows and single pane sliding glass doorsHas a massive gap at joint between stationary and moving parts which covered with duct tape to prevent wind from blowing in (see picture on right).For most of winter, I’ve slept on the floor, my daughter on the top bunk and my 3 boys on the bottom bunk.When my dad visited for Christmas, he slept on the floor of the unheated living room in a 20 degree sleeping bag';

% picture Picture 5
img = fullfile(assets, 'image1.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(685800), mat2ppt.util.Emu(2895600), mat2ppt.util.Emu(3556000), mat2ppt.util.Emu(2667000));
end

% picture Picture 3
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5029200), mat2ppt.util.Emu(3200400), mat2ppt.util.Emu(3556000), mat2ppt.util.Emu(2667000));
end


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'State of Usable Bathroom';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(1371600), mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(1143001));
sp.text_frame().text = 'Old heater in bathroom removed because 1” gaps “protecting” exposed heater wire were extreme danger to small kids, such as I have.Bathroom unheated, but usable.  Old asbestos tile remediated and shower/toilet/sink work.Lighting still an issue and ceiling unfinished.';

% picture Picture 4
img = fullfile(assets, 'image3.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1862137), mat2ppt.util.Emu(3357563), mat2ppt.util.Emu(3695700), mat2ppt.util.Emu(2771775));
end

% picture Picture 5
img = fullfile(assets, 'image4.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5181600), mat2ppt.util.Emu(2971800), mat2ppt.util.Emu(3556000), mat2ppt.util.Emu(2667000));
end


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'State of Kitchen';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(1600201), mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(1295400));
sp.text_frame().text = 'Wife removed cupboard doors and have had trouble finding them.Note exposed wiring and 50 year old fluorescent lights that sometimes don’t work when it gets cold.';

% picture Picture 3
img = fullfile(assets, 'image5.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(2895600), mat2ppt.util.Emu(4572000), mat2ppt.util.Emu(3429000));
end


%% ===== Slide 5 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'State of living room (1/3)';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(990601), mat2ppt.util.Emu(8305800), mat2ppt.util.Emu(1066799));
sp.text_frame().text = 'One of the 4’x6’ single pane window replaced with used double pane off craig’s list. It has not been trimmed out.Three other single pane windows remain plus single pane sliding glass door. One window has broken frame and one can see through to the outside';

% picture Picture 4
img = fullfile(assets, 'image6.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5301836), mat2ppt.util.Emu(4267200), mat2ppt.util.Emu(3112328), mat2ppt.util.Emu(2334246));
end

% picture Picture 7
img = fullfile(assets, 'image7.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(381000), mat2ppt.util.Emu(3040534), mat2ppt.util.Emu(4572000), mat2ppt.util.Emu(3429000));
end

% Rectangle 11
sp = sh.add_shape('rect', mat2ppt.util.Emu(2422584), mat2ppt.util.Emu(3741887), mat2ppt.util.Emu(914400), mat2ppt.util.Emu(762000));

% connector Straight Connector 12
sh.add_connector('line', mat2ppt.util.Emu(3336984), mat2ppt.util.Emu(4503888), mat2ppt.util.Emu(5334000), mat2ppt.util.Emu(3993312));

% connector Straight Connector 13
sh.add_connector('line', mat2ppt.util.Emu(3336984), mat2ppt.util.Emu(3733800), mat2ppt.util.Emu(5334000), mat2ppt.util.Emu(2462122));

% picture Picture 17
img = fullfile(assets, 'image8.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5349814), mat2ppt.util.Emu(2462122), mat2ppt.util.Emu(2041586), mat2ppt.util.Emu(1531190));
end


%% ===== Slide 6 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'State of living room (2/3)';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(1600201), mat2ppt.util.Emu(8458200), mat2ppt.util.Emu(1295399));
sp.text_frame().text = 'Note single pane sliding glass door with unsealed gap between sliding and stationary parts.';

% picture Picture 5
img = fullfile(assets, 'image9.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(685800), mat2ppt.util.Emu(3009899), mat2ppt.util.Emu(4572000), mat2ppt.util.Emu(3429000));
end

% picture Picture 6
img = fullfile(assets, 'image10.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5524500), mat2ppt.util.Emu(3505200), mat2ppt.util.Emu(3352799), mat2ppt.util.Emu(2514599));
end


%% ===== Slide 7 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'State of living room (3/3)';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(1295401), mat2ppt.util.Emu(8534400), mat2ppt.util.Emu(1676400));
sp.text_frame().text = 'Picture on left from earlier in Dec. 2014 shows old propane heater.Picture on right shows this week’s installation of electric wall furnace.30,000 BTU, 40+ amps.  Can only afford to run for a few hours a day.  Full time would cost $400+/month and only heat one room.  Can’t afford $10-20k to outfit entire house with efficient heat pumps.  Got quote earlier this  month for 12 amp heat pump for this one room.  It was $6k.  I can buy the parts for $3.25k and do myself when I have more money, but will still need to pull a permit and hire a plumber for $500 to hook up the refrigerant.';

% picture Picture 7
img = fullfile(assets, 'image11.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1981200), mat2ppt.util.Emu(3043687), mat2ppt.util.Emu(1836050), mat2ppt.util.Emu(3533682));
end

% picture Picture 8
img = fullfile(assets, 'image12.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4814887), mat2ppt.util.Emu(3490913), mat2ppt.util.Emu(3543300), mat2ppt.util.Emu(2657475));
end


%% ===== Slide 8 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'State of 2nd bedroom';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(304800), mat2ppt.util.Emu(1295400), mat2ppt.util.Emu(8382000), mat2ppt.util.Emu(1066800));
sp.text_frame().text = 'Single pane windows replaced in 2nd and 3rd bedrooms Nov. - Dec. of 2014Trim finished just this week in one room, not in the otherNote temperature is 47 degrees despite space heater being on 24-7.  Obviously, I have a serious problem here.  Walls on this side of the house are more poorly insulated than I anticipated.  Quality in this regard is very uneven throughout the house.  Also, floor is uninsulated above vented crawl space, which probably has a big effect.  When wood stove is run constantly, a space heater can keep the room tolerable.  Without it, it is miserable.';

% picture Picture 5
img = fullfile(assets, 'image13.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4267200), mat2ppt.util.Emu(3392958), mat2ppt.util.Emu(4048400), mat2ppt.util.Emu(3036300));
end

% picture Picture 6
img = fullfile(assets, 'image14.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1313546), mat2ppt.util.Emu(3245992), mat2ppt.util.Emu(1627644), mat2ppt.util.Emu(3365265));
end

% Rectangle 7
sp = sh.add_shape('rect', mat2ppt.util.Emu(4648200), mat2ppt.util.Emu(5257800), mat2ppt.util.Emu(914400), mat2ppt.util.Emu(762000));

% connector Straight Connector 9
sh.add_connector('line', mat2ppt.util.Emu(4648200), mat2ppt.util.Emu(5257800), mat2ppt.util.Emu(3810001), mat2ppt.util.Emu(4114802));

% connector Straight Connector 10
sh.add_connector('line', mat2ppt.util.Emu(4648200), mat2ppt.util.Emu(6019800), mat2ppt.util.Emu(3810001), mat2ppt.util.Emu(5742447));


%% ===== Slide 9 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(437072), mat2ppt.util.Emu(0), mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(1143000));
sp.text_frame().text = 'State of third bedroom';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(436593), mat2ppt.util.Emu(1120383), mat2ppt.util.Emu(8174007), mat2ppt.util.Emu(708417));
sp.text_frame().text = 'Single pane window replaced in November 2014, but hasn’t been trimmed out or finished.Third bedroom is open to the bathroom since wall has been removed.';

% picture Picture 4
img = fullfile(assets, 'image15.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3429000), mat2ppt.util.Emu(2209800), mat2ppt.util.Emu(2608531), mat2ppt.util.Emu(1956398));
end

% picture Picture 6
img = fullfile(assets, 'image16.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(436593), mat2ppt.util.Emu(4791253), mat2ppt.util.Emu(2611408), mat2ppt.util.Emu(1958556));
end

% picture Picture 7
img = fullfile(assets, 'image17.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6376358), mat2ppt.util.Emu(2282553), mat2ppt.util.Emu(2414523), mat2ppt.util.Emu(1810892));
end

% picture Picture 8
img = fullfile(assets, 'image18.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6376358), mat2ppt.util.Emu(4791253), mat2ppt.util.Emu(2626504), mat2ppt.util.Emu(1969878));
end

% picture Picture 9
img = fullfile(assets, 'image19.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3515624), mat2ppt.util.Emu(4779931), mat2ppt.util.Emu(2641600), mat2ppt.util.Emu(1981200));
end

% TextBox 10
sp = sh.add_shape('rect', mat2ppt.util.Emu(6477000), mat2ppt.util.Emu(1752600), mat2ppt.util.Emu(2133600), mat2ppt.util.Emu(430887));
sp.text_frame().text = 'Hole in floor for removed propane heater covered by duct tape';

% TextBox 11
sp = sh.add_shape('rect', mat2ppt.util.Emu(3666465), mat2ppt.util.Emu(1883404), mat2ppt.util.Emu(2371066), mat2ppt.util.Emu(261610));
sp.text_frame().text = 'View of bedroom from 2nd bathroom';

% TextBox 12
sp = sh.add_shape('rect', mat2ppt.util.Emu(472057), mat2ppt.util.Emu(1968043), mat2ppt.util.Emu(2371066), mat2ppt.util.Emu(261610));
sp.text_frame().text = 'View of bathroom from bedroom';

% TextBox 13
sp = sh.add_shape('rect', mat2ppt.util.Emu(476370), mat2ppt.util.Emu(4412551), mat2ppt.util.Emu(2371066), mat2ppt.util.Emu(261610));
sp.text_frame().text = 'Untrimmed window in third bedroom';

% TextBox 14
sp = sh.add_shape('rect', mat2ppt.util.Emu(3515624), mat2ppt.util.Emu(4360366), mat2ppt.util.Emu(5487238), mat2ppt.util.Emu(430887));
sp.text_frame().text = 'Overall views of bedroom showing ungrounded plugs, untrimmed windows, asbestos flooring and old recently removed single pane windows.';


%% ===== Slide 10 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'State of Second Bathroom';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(381000), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(8382000), mat2ppt.util.Emu(1066799));
sp.text_frame().text = 'Shower tile had been placed over unprotected drywall and was falling apart.  Walls were covered with broken mirrors which were used as wall tile and were a cutting hazard since some of the grout was starting to fall out.Currently walls are torn out, old ungrounded wiring needs toi be replaced with modern GFI outlets and shower needs to be finished.Note frost on single pane window in the afternoon (nearly warmest part of the day,  plenty of time to warm up)';

% picture Picture 3
img = fullfile(assets, 'image20.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(304800), mat2ppt.util.Emu(2819400), mat2ppt.util.Emu(4114800), mat2ppt.util.Emu(3086100));
end

% picture Picture 5
img = fullfile(assets, 'image21.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4837723), mat2ppt.util.Emu(3225800), mat2ppt.util.Emu(4064000), mat2ppt.util.Emu(3048000));
end


%% ===== Slide 11 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'State of Basement (1/2)';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(1143001), mat2ppt.util.Emu(8458200), mat2ppt.util.Emu(1828800));
sp.text_frame().text = 'Basement was used as a second bedroom in the summer 2nd bedroom had broken single pane window from domestic violence incident for which ex-wife was charged by AG.  Since then it has been replaced as recorded earlier.Note massive gap to outside under 2nd door and huge hole in wall with light coming in from outside (shown below).Basement completely inappropriate to use as bedroom in winter.Note broken window on door which is covered in packing tape and shown below (another DV incident)';

% picture Picture 8
img = fullfile(assets, 'image22.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(990600), mat2ppt.util.Emu(2971800), mat2ppt.util.Emu(4572000), mat2ppt.util.Emu(3429000));
end

% picture Picture 15
img = fullfile(assets, 'image23.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5974871), mat2ppt.util.Emu(3550129), mat2ppt.util.Emu(3407433), mat2ppt.util.Emu(2555575));
end

% Rectangle 16
sp = sh.add_shape('rect', mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(6096000), mat2ppt.util.Emu(1306902), mat2ppt.util.Emu(228600));

% Rectangle 17
sp = sh.add_shape('rect', mat2ppt.util.Emu(2133600), mat2ppt.util.Emu(3405996), mat2ppt.util.Emu(392502), mat2ppt.util.Emu(327804));

% Rectangle 18
sp = sh.add_shape('rect', mat2ppt.util.Emu(7286084), mat2ppt.util.Emu(4375748), mat2ppt.util.Emu(1019715), mat2ppt.util.Emu(1034451));


%% ===== Slide 12 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'State of Basement (2/2)';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(1143001), mat2ppt.util.Emu(8458200), mat2ppt.util.Emu(1828800));
sp.text_frame().text = 'Basement was used as a second bedroom in the summer 2nd bedroom had broken window from domestic violence incident for which ex-wife was charged by AG.  Since then it has been replaced as recorded earlier.Basement completely inappropriate to use as bedroom in winter.Note broken window on door which is covered in packing tape and shown below (another DV incident), Note massive gap to outside under 2nd door and huge hole in wall with light coming in from outside (shown below).Also note that basement is open to crawl space /unfinished utility room and exposed wiring (shown below).';

% picture Picture 15
img = fullfile(assets, 'image24.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(334034), mat2ppt.util.Emu(3269471), mat2ppt.util.Emu(3860800), mat2ppt.util.Emu(2895600));
end

% picture Picture 16
img = fullfile(assets, 'image25.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4038600), mat2ppt.util.Emu(4082750), mat2ppt.util.Emu(3454400), mat2ppt.util.Emu(2590800));
end

% picture Picture 17
img = fullfile(assets, 'image26.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6858000), mat2ppt.util.Emu(2743200), mat2ppt.util.Emu(2209800), mat2ppt.util.Emu(1657350));
end

% Rectangle 18
sp = sh.add_shape('rect', mat2ppt.util.Emu(6130506), mat2ppt.util.Emu(4400550), mat2ppt.util.Emu(914400), mat2ppt.util.Emu(762000));

% connector Straight Connector 19
sh.add_connector('line', mat2ppt.util.Emu(7044906), mat2ppt.util.Emu(5162550), mat2ppt.util.Emu(9067801), mat2ppt.util.Emu(4392463));

% connector Straight Connector 20
sh.add_connector('line', mat2ppt.util.Emu(6130506), mat2ppt.util.Emu(4392463), mat2ppt.util.Emu(6858000), mat2ppt.util.Emu(2743201));


%% ===== Slide 13 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(304800), mat2ppt.util.Emu(152400), mat2ppt.util.Emu(8382000), mat2ppt.util.Emu(1265238));
sp.text_frame().text = 'Unworking Propane Heaters in most Rooms';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(304799), mat2ppt.util.Emu(1143001), mat2ppt.util.Emu(8539163), mat2ppt.util.Emu(1219199));
sp.text_frame().text = 'Propane was pulled by Amerigas due to dangerous piping which was undisclosed.Rusted pipes (shown below)and main supply line running through concrete make replumbing entire house necessary to ever use again.Propane heaters were inefficient and unsafe anyway.';

% picture Picture 3
img = fullfile(assets, 'image27.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6139312), mat2ppt.util.Emu(3886020), mat2ppt.util.Emu(4171950), mat2ppt.util.Emu(1362974));
end

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(2209800), mat2ppt.util.Emu(5410199), mat2ppt.util.Emu(1752600));
sp.text_frame().text = 'Wood heat used on one side of house butDoesn’t reach basement or other side of houseIs only tolerable as whole house heat if someone is home most of the day to keep it going.  Is unworkable since I leave the house at 7:45 and get home at 6:30 most days, at best.';

% picture Picture 5
img = fullfile(assets, 'image28.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3924299), mat2ppt.util.Emu(3827253), mat2ppt.util.Emu(3429000), mat2ppt.util.Emu(2571750));
end

% picture Picture 6
img = fullfile(assets, 'image29.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(255197), mat2ppt.util.Emu(3888537), mat2ppt.util.Emu(3454400), mat2ppt.util.Emu(2590800));
end


%% ===== Slide 14 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'State of Flooring';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(1371601), mat2ppt.util.Emu(8001000), mat2ppt.util.Emu(1600200));
sp.text_frame().text = 'Asbestos tile covers one side of house.  It is coming up in numerous places, as shown below.50 year old nylon carpet covers other side of house, except for hole where old homemade fireplace used to exist (shown below) .  Old fireplace was removed because it was a fire hazard, didn’t draft properly filling room with smoke when fire got low and sucked more heat up the chimney than it gave to room when fire was not low.';

% picture Picture 5
img = fullfile(assets, 'image30.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(381000), mat2ppt.util.Emu(3352800), mat2ppt.util.Emu(3886200), mat2ppt.util.Emu(2914650));
end

% picture Picture 6
img = fullfile(assets, 'image31.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4724400), mat2ppt.util.Emu(3352800), mat2ppt.util.Emu(3962400), mat2ppt.util.Emu(2971800));
end


%% ===== Slide 15 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Misc. Issues';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(1371601), mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(1066800));
sp.text_frame().text = 'Note outside trim not finished on replaced widnows.Note rotting wood and nails sticking up on outside deck.Why I don’t allow the kids to play there.';

% picture Picture 3
img = fullfile(assets, 'image32.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5384800), mat2ppt.util.Emu(4022705), mat2ppt.util.Emu(3759200), mat2ppt.util.Emu(2819400));
end

% picture Picture 4
img = fullfile(assets, 'image33.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3324045), mat2ppt.util.Emu(2579298), mat2ppt.util.Emu(2238555), mat2ppt.util.Emu(1678916));
end

% picture Picture 5
img = fullfile(assets, 'image34.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(304800), mat2ppt.util.Emu(4022705), mat2ppt.util.Emu(3280061), mat2ppt.util.Emu(2460046));
end

% Rectangle 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(2866845), mat2ppt.util.Emu(5333280), mat2ppt.util.Emu(914400), mat2ppt.util.Emu(762000));

% connector Straight Connector 7
sh.add_connector('line', mat2ppt.util.Emu(3781245), mat2ppt.util.Emu(6095281), mat2ppt.util.Emu(5562600), mat2ppt.util.Emu(4258214));

% connector Straight Connector 8
sh.add_connector('line', mat2ppt.util.Emu(2866845), mat2ppt.util.Emu(5325194), mat2ppt.util.Emu(3324045), mat2ppt.util.Emu(2579298));


%% ===== Slide 16 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Undisclosed Problems Preventing Sale';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(4343400), mat2ppt.util.Emu(4953000));
sp.text_frame().text = 'Foundation problem discovered after buying the house has outside wall leaning over an inch in just 8’.This was not disclosed when I bought the place and must be fixed before sale.  The problem is the foundation is not solid concrete.  It is a mixed concrete and rock, making jacking it up the normal way impossible since it is only strong in compression and not tension.Similar to the rubble trench foundations which Frank Lloyd Wright was famous for, but which are a nightmare to fix if not done properly.';

% picture Picture 3
img = fullfile(assets, 'image35.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4162425), mat2ppt.util.Emu(2295525), mat2ppt.util.Emu(5562600), mat2ppt.util.Emu(4171950));
end


%% ===== Slide 17 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Conclusions';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(1600200), mat2ppt.util.Emu(8305800), mat2ppt.util.Emu(4038600));
sp.text_frame().text = 'Anyone who thinks this is a proper place to raise kids in winter needs to have their head examined.  It is bitterly cold and needs much work to be rentable, comfortably livable or even saleable at anything but a huge loss.This is only a small sampling of the problems I have with this house, some of which I’m afraid to document in pictures given to people I don’t trust.The worst part about this whole thing is that now I have to live here an extra month (the 2nd coldest month of the year), because somebody made themselves judge and jury of things had no understanding of and forced me to jump through numerous ridiculous hoops which delayed closing past Dec. 31, costing me tons of money in legal fees and forcing my kids to endure another month of mind-numbing cold.I only bought this house because I thought I had a partner in life who could help me fix the place up and make it livable. A lawsuit over the driveway that cost me tens of thousands of dollars and tied up funds designated for fixing this house combined with my ex losing her mind, leaving me with full custody of the kids and alimony to pay conspired to cost me that dream.  Now, somebody who has no fucking idea what it is like to live here wants to take away my chance to get out of here by not allowing a loan to go through.  What are my other options: selling at a massive loss or walking a way and defaulting on the loan.  Are those options really preferable?  I think not.Now that I’ve been completely humiliated, “Mother, may I please have my loan?”';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide1 sp used title-area default geom: Title 1
% GAP: slide1 sp used title-area default geom: Subtitle 2
% GAP: slide2 sp used title-area default geom: Title 1
% GAP: slide3 sp used title-area default geom: Title 1
% GAP: slide4 sp used title-area default geom: Title 1
% GAP: slide6 sp used title-area default geom: Title 1
% GAP: slide7 sp used title-area default geom: Title 1
% GAP: slide8 sp used title-area default geom: Title 1
% GAP: slide10 sp used title-area default geom: Title 1
% GAP: slide11 sp used title-area default geom: Title 1
% GAP: slide12 sp used title-area default geom: Title 1
% GAP: slide14 sp used title-area default geom: Title 1
% GAP: slide15 sp used title-area default geom: Title 1
% GAP: slide16 sp used title-area default geom: Title 1
% GAP: slide17 sp used title-area default geom: Title 1
