%% demo.m — Recreate 14_Dropbox_Ethics__High School NFP presentation via Mat2Ppt public API
% Source: 14_Dropbox_Ethics__High School NFP presentation.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(9144000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(381000), mat2ppt.util.Emu(304800), mat2ppt.util.Emu(8077200), mat2ppt.util.Emu(1143000));
sp.text_frame().text = 'Jeff and Erika Cowman';

% Rectangle 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(4724400), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(4038600), mat2ppt.util.Emu(4114800));
sp.text_frame().text = 'Met when Jeff was 17 and Erika 18, on Bishop Kelly campusMarried at St. John’s Cathedral June 2003Became NFP Teachers 2009';

% picture Picture 4
img = fullfile(assets, 'image2.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(381000), mat2ppt.util.Emu(1793837), mat2ppt.util.Emu(3962400), mat2ppt.util.Emu(4479235));
end


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 2
img = fullfile(assets, 'image1.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(1416050), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(5456238));
end

% Rectangle 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(381000), mat2ppt.util.Emu(304800), mat2ppt.util.Emu(8610600), mat2ppt.util.Emu(1143000));
sp.text_frame().text = 'Children';

% Rectangle 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(6406682), mat2ppt.util.Emu(1585579), mat2ppt.util.Emu(2804553), mat2ppt.util.Emu(4800600));
sp.text_frame().text = 'Mikaela Joan 13Kaleb Alexander 11Baby George in heavenJohn Paul 7Gilbert Joseph 4';

% picture Picture 3
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(67235), mat2ppt.util.Emu(1585579), mat2ppt.util.Emu(6272212), mat2ppt.util.Emu(4478671));
end


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(495300), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'How we discovered NFP:';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2362200), mat2ppt.util.Emu(1401763), mat2ppt.util.Emu(6324600), mat2ppt.util.Emu(4114800));
sp.text_frame().text = 'Grew up on dairy farmKnew about chastity, but not teaching on contraceptionOverheard parents joking about the Pope not liking vasectomiesVet science class in college—Animal reproduction—fertility is scienceAudio Talk:  Professor Janet Smith—Contraception:  Why Not?/Cracking the Myths';

% TextBox 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(2667000), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(830997));
sp.text_frame().text = 'Erika';


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(122237), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'How we discovered NFP:';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2209800), mat2ppt.util.Emu(1600200), mat2ppt.util.Emu(6934200), mat2ppt.util.Emu(5257800));
sp.text_frame().text = 'Learned about development and testing of the Pill in high school and how women diedMen fertile 24/7, Women a few days, seemed unjust to sterilize a womenLearned about NFP on a H.S. retreat Heard talks on Theology of the Body at Seminary and with ErikaCollege- completed a group project for statistics class on contraceptive use; I knew more about women’s cycles than my female classmates';

% TextBox 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(2667000), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1200329));
sp.text_frame().text = 'Jeff';


%% ===== Slide 5 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Our purpose here';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2362200), mat2ppt.util.Emu(1676400), mat2ppt.util.Emu(6629400), mat2ppt.util.Emu(4114800));
sp.text_frame().text = 'Provide information on what NFP is & what it is notProvide facts / dispel mythsBenefits of NFPAnswer questions';


%% ===== Slide 6 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 3
img = fullfile(assets, 'image1.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(5562600));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(685800), mat2ppt.util.Emu(2209800), mat2ppt.util.Emu(7772400), mat2ppt.util.Emu(2536825));
sp.text_frame().text = 'Inform…not judge!';

% Text Box 24
sp = sh.add_shape('rect', mat2ppt.util.Emu(8305799), mat2ppt.util.Emu(6443246), mat2ppt.util.Emu(522287), mat2ppt.util.Emu(338554));
sp.text_frame().text = '6';


%% ===== Slide 7 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(122237), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Fact or Myth?';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(6629400), mat2ppt.util.Emu(4495800));
sp.text_frame().text = 'Natural Family Planning (NFP) is an old fashioned method of trying to prevent pregnancy (Some call it the Rhythm method or Calendar method)';

% picture Picture 7
img = fullfile(assets, 'image4.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(3392959), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(3456000));
end


%% ===== Slide 8 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(31376), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Myth!';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2057400), mat2ppt.util.Emu(1752600), mat2ppt.util.Emu(6629400), mat2ppt.util.Emu(4114800));
sp.text_frame().text = 'Modern NFP is NOT the old Rhythm method our grandparents and great-grandparents used, but is based on scientifically studied signs of fertility';


%% ===== Slide 9 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 12
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(175418), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'What is NFP?';

% Rectangle 13
sp = sh.add_shape('rect', mat2ppt.util.Emu(2971800), mat2ppt.util.Emu(1474087), mat2ppt.util.Emu(5543550), mat2ppt.util.Emu(4114800));
sp.text_frame().text = 'Scientific knowledge of    fertilityReading body’s signs of fertility and infertilityNatural Family Planning (NFP)Fertility Awareness Method (FAM)';

% picture Picture 2
img = fullfile(assets, 'image5.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(3132635), mat2ppt.util.Emu(2362200), mat2ppt.util.Emu(3743294));
end

% Text Box 24
sp = sh.add_shape('rect', mat2ppt.util.Emu(8305799), mat2ppt.util.Emu(6443246), mat2ppt.util.Emu(522287), mat2ppt.util.Emu(338554));
sp.text_frame().text = '9';


%% ===== Slide 10 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 9
img = fullfile(assets, 'image1.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(5562600));
end

% picture Picture 4
img = fullfile(assets, 'image6.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1076325), mat2ppt.util.Emu(2030412), mat2ppt.util.Emu(6991350), mat2ppt.util.Emu(1659845));
end

% Rectangle 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(3911600), mat2ppt.util.Emu(2157412), mat2ppt.util.Emu(1320800), mat2ppt.util.Emu(317500));

% Text Box 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(4000500), mat2ppt.util.Emu(2106612), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(338138));
sp.text_frame().text = 'Men';

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(381000), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(8458200), mat2ppt.util.Emu(1143000));
sp.text_frame().text = 'Hormones in men';

% Text Box 24
sp = sh.add_shape('rect', mat2ppt.util.Emu(8305799), mat2ppt.util.Emu(6443246), mat2ppt.util.Emu(522287), mat2ppt.util.Emu(338554));
sp.text_frame().text = '10';


%% ===== Slide 11 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 9
img = fullfile(assets, 'image1.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(5562600));
end

% picture Picture 4
img = fullfile(assets, 'image6.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1076325), mat2ppt.util.Emu(2030412), mat2ppt.util.Emu(6991350), mat2ppt.util.Emu(4141788));
end

% Rectangle 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(3911600), mat2ppt.util.Emu(2157412), mat2ppt.util.Emu(1320800), mat2ppt.util.Emu(317500));

% Text Box 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(4000500), mat2ppt.util.Emu(2106612), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(338138));
sp.text_frame().text = 'Men';

% Rectangle 7
sp = sh.add_shape('rect', mat2ppt.util.Emu(3898900), mat2ppt.util.Emu(3776662), mat2ppt.util.Emu(1320800), mat2ppt.util.Emu(317500));

% Text Box 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(3879850), mat2ppt.util.Emu(3692525), mat2ppt.util.Emu(1409700), mat2ppt.util.Emu(457200));
sp.text_frame().text = 'Women';

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(381000), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(8458200), mat2ppt.util.Emu(1143000));
sp.text_frame().text = 'Hormones in women';

% Text Box 24
sp = sh.add_shape('rect', mat2ppt.util.Emu(8305799), mat2ppt.util.Emu(6443246), mat2ppt.util.Emu(522287), mat2ppt.util.Emu(338554));
sp.text_frame().text = '11';


%% ===== Slide 12 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(146794), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Putting it all together';

% Rectangle 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(76200), mat2ppt.util.Emu(4701867), mat2ppt.util.Emu(2195286), mat2ppt.util.Emu(2062103));
sp.text_frame().text = 'This image is freely available at commons.wikimedia.org/wiki/ File:MenstrualCycle.png under a creative commons cc-by-sa 3.0 license';

% picture Picture 5
img = fullfile(assets, 'image7.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(2667000), mat2ppt.util.Emu(1472357), mat2ppt.util.Emu(5181600), mat2ppt.util.Emu(5291613));
end

% TextBox 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(1981200), mat2ppt.util.Emu(2042886), mat2ppt.util.Emu(2246769));
sp.text_frame().text = 'I trust God’s design; He makes no mistakes; all of nature is cyclicalFertility=Health';


%% ===== Slide 13 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(175418), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'How NFP Works';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2438400), mat2ppt.util.Emu(1905000), mat2ppt.util.Emu(6324600), mat2ppt.util.Emu(4495800));
sp.text_frame().text = 'Measures changes in signs of fertilityRecorded on chart to define fertility and infertility Abstain or have relations based on absence or presence of fertile signs';


%% ===== Slide 14 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(198957), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Sample CCL Chart';

% TextBox 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(366793), mat2ppt.util.Emu(1600200), mat2ppt.util.Emu(1676400), mat2ppt.util.Emu(1077218));
sp.text_frame().text = 'Sympto- thermal';

% AutoShape 10
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(2971800), mat2ppt.util.Emu(1676400), mat2ppt.util.Emu(5657669), mat2ppt.util.Emu(4876800));

% picture Picture 2
img = fullfile(assets, 'image8.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3048000), mat2ppt.util.Emu(2248671), mat2ppt.util.Emu(5486400), mat2ppt.util.Emu(4258491));
end

% picture Picture 2
img = fullfile(assets, 'image9.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3060700), mat2ppt.util.Emu(1810656), mat2ppt.util.Emu(5473700), mat2ppt.util.Emu(513814));
end

% TextBox 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(3276600), mat2ppt.util.Emu(1981200), mat2ppt.util.Emu(461665));
sp.text_frame().text = 'How we chart';


%% ===== Slide 15 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(740423), mat2ppt.util.Emu(156100), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = '“There’s an app for that”';

% Rectangle 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(2923481), mat2ppt.util.Emu(1770257), mat2ppt.util.Emu(5029200), mat2ppt.util.Emu(4724400));
sp.text_frame().text = 'Fertility monitorsSoftwareMobile appsApps = virtual reality trainingClasses = real life trial and error application and instruction';

% picture Picture 2
img = fullfile(assets, 'image10.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(409569), mat2ppt.util.Emu(3650864), mat2ppt.util.Emu(1451525), mat2ppt.util.Emu(963186));
end

% picture Picture 4
img = fullfile(assets, 'image11.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(2895600), mat2ppt.util.Emu(3368622), mat2ppt.util.Emu(2641479), mat2ppt.util.Emu(3067050));
end

% picture Picture 6
img = fullfile(assets, 'image12.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5551286), mat2ppt.util.Emu(3337625), mat2ppt.util.Emu(2295526), mat2ppt.util.Emu(3067050));
end

% picture Picture 17
img = fullfile(assets, 'image13.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(407654), mat2ppt.util.Emu(1981200), mat2ppt.util.Emu(1455354), mat2ppt.util.Emu(1102113));
end

% TextBox 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(2743200), mat2ppt.util.Emu(3123654), mat2ppt.util.Emu(5715000), mat2ppt.util.Emu(1200329));
sp.text_frame().text = '“User Beware”';


%% ===== Slide 16 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(99218), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Fact or Myth?';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2438400), mat2ppt.util.Emu(1752600), mat2ppt.util.Emu(5900738), mat2ppt.util.Emu(4343400));
sp.text_frame().text = 'Couples who use NFP have sex as often as couples who use contraception – they just time it differently.';


%% ===== Slide 17 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(31376), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Fact!';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2362200), mat2ppt.util.Emu(1752600), mat2ppt.util.Emu(6553200), mat2ppt.util.Emu(4953000));
sp.text_frame().text = 'REALITY: If couples who practice NFP were to engage in intercourse on all the days when abstinence is not required for spacing births, they would be doing so at a rate almost twice the national average! NFP couples can make love no less frequently in each cycle than other couples.Abstinence is a part of marriageillnessWork travelMilitary deploymentBirthNo one has died from NOT having sex';


%% ===== Slide 18 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(914400), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(2852737));
sp.text_frame().text = 'NFP Benefit #1';

% Text Placeholder 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(609600), mat2ppt.util.Emu(4572000), mat2ppt.util.Emu(8420100), mat2ppt.util.Emu(1500187));
sp.text_frame().text = 'Authentic Love…selfless, not selfish';


%% ===== Slide 19 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(69056), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Marital love is a self-gift';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2407024), mat2ppt.util.Emu(1600200), mat2ppt.util.Emu(6705600), mat2ppt.util.Emu(4114800));
sp.text_frame().text = '100%-100%, Not 50/50Free, total, faithful, fruitfulCommitment at altar“Have you come here freely to give yourselves to each other without reservation?”“Do you promise to be faithful until death?”“Do you promise to receive children lovingly from God?”';

% picture Picture 2
img = fullfile(assets, 'image14.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(-9041), mat2ppt.util.Emu(2514600), mat2ppt.util.Emu(2258432), mat2ppt.util.Emu(3505200));
end


%% ===== Slide 20 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(381000), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(8458200), mat2ppt.util.Emu(1143000));
sp.text_frame().text = 'Every Sacrament—form & matter';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2057400), mat2ppt.util.Emu(1600200), mat2ppt.util.Emu(7086600), mat2ppt.util.Emu(5181600));
sp.text_frame().text = 'Baptism=form: baptize you in the name of the Father,…..matter: water Eucharist=Form: words of the last supperMatter: bread and wineMarriage=Form:  vows made by the coupleMatter: consummation of the marriage (to complete a marriage by the first act of sexual intercourse)';


%% ===== Slide 21 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(533400), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(8153400), mat2ppt.util.Emu(1143000));
sp.text_frame().text = 'Sexual Intercourse=Renewing Wedding Vows';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2057400), mat2ppt.util.Emu(1600200), mat2ppt.util.Emu(6934200), mat2ppt.util.Emu(5029200));
sp.text_frame().text = 'Now chastity made sense—we can’t renew vows we haven’t madeIn our vows we promise to love: Freely, Totally, Faithfully, FruitfullyWith NFP we are free to give our complete selves the way God made us, just as we are, without altering ourselves—fertility is not an illness';

% picture Picture 4
img = fullfile(assets, 'image15.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(31377), mat2ppt.util.Emu(-152400), mat2ppt.util.Emu(1645024), mat2ppt.util.Emu(1654255));
end


%% ===== Slide 22 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(762000), mat2ppt.util.Emu(-457200), mat2ppt.util.Emu(8359588), mat2ppt.util.Emu(3293209));
sp.text_frame().text = '© Couple to Couple League International';

% picture Picture 12
img = fullfile(assets, 'image16.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(2168088), mat2ppt.util.Emu(-197), mat2ppt.util.Emu(4689912), mat2ppt.util.Emu(6853715));
end

% picture Picture 13
img = fullfile(assets, 'image17.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6708711), mat2ppt.util.Emu(6248400), mat2ppt.util.Emu(2155500), mat2ppt.util.Emu(185325));
end


%% ===== Slide 23 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(152400), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Fact or Myth?';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2438400), mat2ppt.util.Emu(1825625), mat2ppt.util.Emu(6076950), mat2ppt.util.Emu(4351338));
sp.text_frame().text = 'Couples who practice NFP have a less than 5% divorce rate.';


%% ===== Slide 24 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(228600), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Fact!';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2362200), mat2ppt.util.Emu(1825625), mat2ppt.util.Emu(6153150), mat2ppt.util.Emu(4351338));
sp.text_frame().text = 'Studies of shown that couples who practice Natural Family Planning have a divorce rate between 1-5%Couples who pray together daily (not meal prayer) have a divorce rate of .01%';


%% ===== Slide 25 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(914400), mat2ppt.util.Emu(1723280), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(2852737));
sp.text_frame().text = 'NFP Benefit #2';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(304800), mat2ppt.util.Emu(4589464), mat2ppt.util.Emu(8686800), mat2ppt.util.Emu(1500187));
sp.text_frame().text = 'Stronger Marriage & Greater Intimacy';


%% ===== Slide 26 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(18255), mat2ppt.util.Emu(8839200), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Why increased intimacy?';

% Content Placeholder 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(2057400), mat2ppt.util.Emu(1343818), mat2ppt.util.Emu(6934200), mat2ppt.util.Emu(5495927));
sp.text_frame().text = 'Stronger relationships may be more likely to practice NFPCouples who reject NFP as “too much trouble” or “too restrictive” all too often turn out to be the same couples who ultimately find the demands of marriage itself to be too much to handle ~Jason EvertNFP takes virtue—so does marriagecommitment, communication, consideration, patience, sacrifice and self-control;  These are what makes marriage work.NFP requires communicationShared responsibility; chart togetherKeeps spouses from taking each other for granted and relying on physical intimacyMany women on contraception complain of feeling used. Contraception can lead the husband to assume that she was always sexually available. With NFP, Spouses are not constantly sexually available to the other Couples we know personally report that their physical life is better';


%% ===== Slide 27 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(152400), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Chastity Tests Love';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2362200), mat2ppt.util.Emu(1600200), mat2ppt.util.Emu(6400800), mat2ppt.util.Emu(4879976));
sp.text_frame().text = 'Immature views of love and relationship will rise to the surface when chastity is requiredAbstinence is a built in a time when they can “court”; every kiss does not need to lead to the bedroomHelps us focus on intellectual, emotional, spiritual intimacy';


%% ===== Slide 28 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(152400), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Fact or Myth?';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2743200), mat2ppt.util.Emu(1825625), mat2ppt.util.Emu(5772150), mat2ppt.util.Emu(4351338));
sp.text_frame().text = 'The Catholic Church calls married couples to have as many children as possible.';


%% ===== Slide 29 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(152400), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Myth!';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2743200), mat2ppt.util.Emu(1825625), mat2ppt.util.Emu(5772150), mat2ppt.util.Emu(4351338));
sp.text_frame().text = 'REALITY:  The Catholic Church encourages people to be both generous and responsible stewards over their fertility.';


%% ===== Slide 30 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(1295400), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(2852737));
sp.text_frame().text = 'NFP Benefit #3';

% Text Placeholder 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(2514600), mat2ppt.util.Emu(4589464), mat2ppt.util.Emu(5995988), mat2ppt.util.Emu(1500187));
sp.text_frame().text = 'Countercultural—Children viewed as a gift, not a burden';


%% ===== Slide 31 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(152400), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Marital Embrace';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2667000), mat2ppt.util.Emu(1752600), mat2ppt.util.Emu(6019800), mat2ppt.util.Emu(4114800));
sp.text_frame().text = 'Babies & Bonding“So they are no longer two, but one flesh. Therefore what God has joined together, let no one separate.”  ~Matthew 19:6';

% picture Picture 2
img = fullfile(assets, 'image18.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(1735811), mat2ppt.util.Emu(2285558), mat2ppt.util.Emu(1752600));
end


%% ===== Slide 32 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(304800), mat2ppt.util.Emu(80954), mat2ppt.util.Emu(8210550), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'But what about those huge families?';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(1600200), mat2ppt.util.Emu(6629400), mat2ppt.util.Emu(4343400));
sp.text_frame().text = 'All Christians are called to generosityNowhere in the Bible are children a curse or burden; they are ALWAYS a blessing; Couples who reject contraception are less likely to see children as a burden. Because of their generous spirit, they tend to have larger families, and divorce rates are highest where children are fewest.';

% picture Picture 2
img = fullfile(assets, 'image19.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1), mat2ppt.util.Emu(2309797), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(1850327));
end


%% ===== Slide 33 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(18255), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Inviting God Into the Marriage';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2362200), mat2ppt.util.Emu(1825624), mat2ppt.util.Emu(6153150), mat2ppt.util.Emu(4879975));
sp.text_frame().text = 'Monthly discernment of what God is calling that family to beHow’s our marriage?How is our family doing?Are we being generous? Prudent?Lord help us overcome…Lord, help us to trust…Not telling God our plan, but asking HimWedding invitation analogy (from Christopher West)';


%% ===== Slide 34 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(152400), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Fact or Myth?';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(3048000), mat2ppt.util.Emu(1825625), mat2ppt.util.Emu(5562600), mat2ppt.util.Emu(4351338));
sp.text_frame().text = 'Only women with regular cycles can use NFP.';


%% ===== Slide 35 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(31376), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Myth!';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2590800), mat2ppt.util.Emu(1825625), mat2ppt.util.Emu(5924550), mat2ppt.util.Emu(4351338));
sp.text_frame().text = 'Reality: NFP can be used by women with irregular cycles, and can even help detect, diagnose and treat health problems, including infertility.';


%% ===== Slide 36 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(2852737));
sp.text_frame().text = 'NFP Benefit #4';

% Text Placeholder 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(381000), mat2ppt.util.Emu(4589464), mat2ppt.util.Emu(8496300), mat2ppt.util.Emu(1500187));
sp.text_frame().text = 'Safe, Healthy, and a Diagnostic Tool';


%% ===== Slide 37 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(18255), mat2ppt.util.Emu(8686800), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'If Sex is natural, why do we make it artificial?';

% picture Picture 7
img = fullfile(assets, 'image20.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(2209800), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(4800600), mat2ppt.util.Emu(5717836));
end


%% ===== Slide 38 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(909100), mat2ppt.util.Emu(69056), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'How the pill and IUD work';

% Rectangle 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(2438400), mat2ppt.util.Emu(1663700), mat2ppt.util.Emu(6667500), mat2ppt.util.Emu(3810001));
sp.text_frame().text = 'Progestin convinces woman’s body she’s pregnantSuppress ovulationBack-up method thin uterine lining to prevent implantation (abortifacient)Breakthrough ovulation common';

% TODO: chart graphicFrame — not auto-generated

% TextBox 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(38100), mat2ppt.util.Emu(2743200), mat2ppt.util.Emu(2209800), mat2ppt.util.Emu(400110));
sp.text_frame().text = 'Combined pill';

% TextBox 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(909100), mat2ppt.util.Emu(1408172), mat2ppt.util.Emu(662361), mat2ppt.util.Emu(420628));
sp.text_frame().text = '28%';

% TODO: chart graphicFrame — not auto-generated

% TextBox 9
sp = sh.add_shape('rect', mat2ppt.util.Emu(38100), mat2ppt.util.Emu(4643735), mat2ppt.util.Emu(2209800), mat2ppt.util.Emu(400110));
sp.text_frame().text = 'Progestin-only';

% TextBox 10
sp = sh.add_shape('rect', mat2ppt.util.Emu(727961), mat2ppt.util.Emu(3465572), mat2ppt.util.Emu(1024639), mat2ppt.util.Emu(420628));
sp.text_frame().text = '33-65%';

% TODO: chart graphicFrame — not auto-generated

% TextBox 13
sp = sh.add_shape('rect', mat2ppt.util.Emu(38100), mat2ppt.util.Emu(6457890), mat2ppt.util.Emu(2209800), mat2ppt.util.Emu(400110));
sp.text_frame().text = 'Mirena';

% TextBox 14
sp = sh.add_shape('rect', mat2ppt.util.Emu(909100), mat2ppt.util.Emu(5294372), mat2ppt.util.Emu(662361), mat2ppt.util.Emu(420628));
sp.text_frame().text = '75%';

% Rectangle 16
sp = sh.add_shape('rect', mat2ppt.util.Emu(2057400), mat2ppt.util.Emu(6044625), mat2ppt.util.Emu(6749143), mat2ppt.util.Emu(584775));
sp.text_frame().text = 'Larimore W, Stanford J, Postfertilization Effects of Oral Contraceptives and Their Relationship to Informed Consent, Arch Fam Med (2000);9:126-133.';


%% ===== Slide 39 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(18255), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Adverse Effects';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(1825624), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(4879976));
sp.text_frame().text = 'Increased Risk of Breast Cancer (and other cancers)Post contraceptive infertilityDecrease libido (artificial hormones increase Sex Hormone Binding Globulin, decrease testosterone levels, sometimes permanent damage)Decreased bone densityIncreased depressionDepo Provers (the shot): CA administers it to sex offenders; veterinarians won’t give it to dogsIf mom conceives on the Pill, sons are more likely to develop prostate cancerSpeaking of Pure water…Damage to the environment';


%% ===== Slide 40 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(-39186), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = '“Gallup poll”';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2438398), mat2ppt.util.Emu(1600200), mat2ppt.util.Emu(6477001), mat2ppt.util.Emu(4114800));
sp.text_frame().text = 'Of the women in the US who discontinued hormonal contraceptives, how many did so because of side effects?33%43%53%64%';

% picture Picture 3
img = fullfile(assets, 'image21.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1), mat2ppt.util.Emu(3007110), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(3450840));
end

% Rectangle 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(3108325), mat2ppt.util.Emu(5194300), mat2ppt.util.Emu(1130300), mat2ppt.util.Emu(336550));

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2905125), mat2ppt.util.Emu(3889935), mat2ppt.util.Emu(2667000), mat2ppt.util.Emu(533400));
sp.text_frame().text = '64%';

% Rectangle 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(2286001), mat2ppt.util.Emu(4074551), mat2ppt.util.Emu(6477000), mat2ppt.util.Emu(707886));
sp.text_frame().text = 'National Survey of Family Growth 2010, CDC, Series 23, Number 29, 69.';


%% ===== Slide 41 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(152400), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Diagnostic Tool';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2296085), mat2ppt.util.Emu(1455551), mat2ppt.util.Emu(6847915), mat2ppt.util.Emu(4351338));
sp.text_frame().text = 'Charting fertility signs can help discover or diagnose health issues such as:Low thyroidLow progesteroneRepeated miscarriageInfertilityDepressionPolycystic Ovarian Syndrome';


%% ===== Slide 42 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(152400), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Fact or Myth?';

% Content Placeholder 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(2438400), mat2ppt.util.Emu(1825625), mat2ppt.util.Emu(6076950), mat2ppt.util.Emu(4351338));
sp.text_frame().text = 'Natural Family Planning is just as effective at limiting births as artificial means.';


%% ===== Slide 43 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(664509), mat2ppt.util.Emu(152400), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Fact!';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2438400), mat2ppt.util.Emu(1825625), mat2ppt.util.Emu(6076950), mat2ppt.util.Emu(4351338));
sp.text_frame().text = 'Modern scientific NFP is 99% effective at limiting birth when couples are motivated to follow the rules (80-90% effective when they don’t even follow the rules)3 Xs more successful than modern technology in helping couples of limited fertility achieve pregnancy';


%% ===== Slide 44 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(655264), mat2ppt.util.Emu(768349), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(2852737));
sp.text_frame().text = 'NFP Benefit #5';

% Text Placeholder 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Effective';


%% ===== Slide 45 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 5
img = fullfile(assets, 'image22.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(658368), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(5541263));
end


%% ===== Slide 46 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 32
img = fullfile(assets, 'image1.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(4572000), mat2ppt.util.Emu(5424488));
end

% Rectangle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(381000), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(8763000), mat2ppt.util.Emu(1143000));
sp.text_frame().text = 'NFP to achieve a pregnancy';

% Rectangle 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(4798359), mat2ppt.util.Emu(1483659), mat2ppt.util.Emu(4117041), mat2ppt.util.Emu(4612341));
sp.text_frame().text = '10-15% of couples suffer from infertility (more than 1 year of trying to conceiveFertility awareness can help couples conceive in half the time or lessKnowing how to identify the fertile window is key';

% picture Picture 4
img = fullfile(assets, 'image23.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(4376738), mat2ppt.util.Emu(3213100));
end


%% ===== Slide 47 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'WebMD';

% Content Placeholder 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(2590800), mat2ppt.util.Emu(1600200), mat2ppt.util.Emu(6553200), mat2ppt.util.Emu(4114800));
sp.text_frame().text = '“A relatively high failure rate has been reported.” The “failure rate” WebMD cites combined data from modern NFP methods with data from calendar methods artificially lowering the effectiveness of NFP';


%% ===== Slide 48 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(304800), mat2ppt.util.Emu(31376), mat2ppt.util.Emu(8458200), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'But isn’t it too complicated and unrealistic?';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(628650), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(5410200));
sp.text_frame().text = 'In a World Health Organization (WHO) study, 725 couples from five countries – El Salvador, India, New Zealand, Ireland, and the Philippines – were taught the ovulation method of NFP over the course of three months. After a year the couples were evaluated, and the method effectiveness rate was 97.2%. Note: half of the Salvadorean couples were illiterate, proving that an advanced education is unnecessary for learning NFP effectivelyBritish medical journal report: study of 19,000 women in India (52% Hindu, 27% Muslim, and 21% Christian)—failure rate of almost 0% ( 0.2 pregnancies/100 women).  Thanks to Mother Teresa, couples avoided government mandated sterilization in the 70s; today India still has sterilization quotas, leading to many deaths from botched operations From a publication of the Missionaries of Charity “Many people wonder how poor couples can exercise self-control for more than one week. Yes, they do it; it is possible. It is, after all, their own choice. Some abstain for twenty days a month; others for one, two, and even three months. From our experience we find that it is more difficult for an educated couple to abstain than for a poor and illiterate couple. Why? Perhaps because the wealthy and educated couples have more comforts, and are more inclined to enjoy the good things of life.”';


%% ===== Slide 49 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(642097), mat2ppt.util.Emu(197173), mat2ppt.util.Emu(7886700), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Isn’t NFP just “natural” birth control';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2590800), mat2ppt.util.Emu(1646707), mat2ppt.util.Emu(5924550), mat2ppt.util.Emu(4351338));
sp.text_frame().text = 'NFP is birth control; it is not contra-ception (against life).Yes, a couple using NFP could be closed to God’s will; they could use it selfishly—but rareOne is a lack of generosity; the other is using the body and making a loving act intentionally sterile, potentially aborting a new life, and separating what God designedTwo women wishing to stay slim analogy';


%% ===== Slide 50 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Resources';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(6172200), mat2ppt.util.Emu(4114800));
sp.text_frame().text = 'Web resourcesfertilitycare.orgChastity.compopepaulvi.comccli.orgboma-usa.orgnfp.marquette.edunfpandmore.orgonemoresoul.comnwfs.orghttp://nfpsst.org/fact-or-fiction/usccb.org/issues-and-action/marriage-and-family/';

% picture Picture 2
img = fullfile(assets, 'image24.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(0), mat2ppt.util.Emu(4233621), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(2628254));
end


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide37 sp missing geom: Content Placeholder 6
% GAP: slide38 chart not auto-generated (manual/API gap)
% GAP: slide38 chart not auto-generated (manual/API gap)
% GAP: slide38 chart not auto-generated (manual/API gap)
% GAP: slide44 sp used title-area default geom: Text Placeholder 4
% GAP: slide45 sp missing geom: Title 3
% GAP: slide45 sp missing geom: Content Placeholder 4
% GAP: slide47 sp used title-area default geom: Title 1
% GAP: slide50 sp used title-area default geom: Title 1
