%% demo.m — Recreate 25_Dropbox_w-job_search__CES Recap_Modeling_100513_FinalD2 via Mat2Ppt public API
% Source: 25_Dropbox_w-job_search__CES Recap_Modeling_100513_FinalD2.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(9144000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(190500), mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(8763000), mat2ppt.util.Emu(2362200));

% picture Picture 3
img = fullfile(assets, 'image6.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(457200), mat2ppt.util.Emu(4648200), mat2ppt.util.Emu(1864775), mat2ppt.util.Emu(1524000));
end

% Title 10
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(1635760), mat2ppt.util.Emu(8610600), mat2ppt.util.Emu(1640840));
sp.text_frame().text = 'Cable Effects Study Program Reviewand Cable Modelling Approach';

% Subtitle 11
sp = sh.add_shape('rect', mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(3505200), mat2ppt.util.Emu(4572000), mat2ppt.util.Emu(1295400));
sp.text_frame().text = 'Douglas CoombsMay 2, 2011';


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(1282700), mat2ppt.util.Emu(57150), mat2ppt.util.Emu(6565900), mat2ppt.util.Emu(1085850));
sp.text_frame().text = 'The Cable Effects Study Missions';

% Rectangle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(1195387), mat2ppt.util.Emu(5562600), mat2ppt.util.Emu(5129213));
sp.text_frame().text = 'Do electrical cable harnesses significantly affect dynamics of precision spacecraft structures?Lightweight and with stringent jitter budgetsCable harnesses are generally not included in spacecraft structural design.  As a consequence:Models and designs are overly conservativeIsolation system requirements are too stringentStructural control systems may be adversely affected by plant model errorsMotivation: develop techniques and methodologies to incorporate cable dynamics in models thereby reducing conservatism and program risk';

% TextBox 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(5559271), mat2ppt.util.Emu(4724400), mat2ppt.util.Emu(3584729), mat2ppt.util.Emu(938719));
sp.text_frame().text = 'Cabling makes a significant amount of dry mass http://www.dlr.de/rd/en/Portaldata/1/Resources/portal_news/newsarchiv2009_3/Tandem-X_intergration_380.jpg';

% picture Picture 2
img = fullfile(assets, 'image7.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5524500), mat2ppt.util.Emu(2057400), mat2ppt.util.Emu(3619500), mat2ppt.util.Emu(2609850));
end


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(228600), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(814388));
sp.text_frame().text = 'The Why of theCable Effects Study';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(1239838), mat2ppt.util.Emu(8763000), mat2ppt.util.Emu(5183187));
sp.text_frame().text = 'Cable harnesses are a large part of spacecraft mass and generally considered a non-structural component at low frequencies. A survey showed that the cable-to-structure mass ratio for DoD and commercial spacecraft can approach 25%.Cables are not modeled in detail because no one cared about the “mid frequency” range until a need for better large precision structure models was identified.  Mission performance is driven by on-orbit dynamics: better models are required.The program was directed to finding a solution to an Air Force need, not to develop an understanding of the fundamental mechanics of cable behavior.Applied research';


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(228600), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(814388));
sp.text_frame().text = 'The Significance of Cable Modelling';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(381000), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(5867400), mat2ppt.util.Emu(4594225));
sp.text_frame().text = 'Electrical cables mounted on space structures can influence the structural dynamics. The effects of cables on spacecraft dynamics is not documented in the industry. Cables not included in models can impact controller performance and robustness, impact isolation system requirements and increase program risk.';

% picture Picture 3
img = fullfile(assets, 'image8.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6477000), mat2ppt.util.Emu(3048000), mat2ppt.util.Emu(2546350), mat2ppt.util.Emu(2867098));
end

% TextBox 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(4724400), mat2ppt.util.Emu(5562600), mat2ppt.util.Emu(1631216));
sp.text_frame().text = 'Model errors are determined late in the flight program (i.e., when cables exist). Is there time for controller tuning? The worst time to determine that the controller is miss-tuned is when the satellite is on-station.';


%% ===== Slide 5 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(228600), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(814388));
sp.text_frame().text = 'The What of theCable Effects Study / Focus Restrictions';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(1239838), mat2ppt.util.Emu(8763000), mat2ppt.util.Emu(5183187));
sp.text_frame().text = 'Only studied small-to-moderate conductor count twisted pair cable bundles.  Not coaxial, ribbon cables, twisted pair in wire or polymer braided sleeving.Concerned with low-level vibration problem (i.e., when the spacecraft is on-station), not launch vibration or shock conditions.Cables with bends and connectors excluded from study.';

% picture Picture 3
img = fullfile(assets, 'image9.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5943600), mat2ppt.util.Emu(4419600), mat2ppt.util.Emu(2743200), mat2ppt.util.Emu(1783080));
end

% picture Picture 4
img = fullfile(assets, 'image10.gif');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3056025), mat2ppt.util.Emu(4419599), mat2ppt.util.Emu(2578537), mat2ppt.util.Emu(1828800));
end

% picture Picture 5
img = fullfile(assets, 'image11.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(304800), mat2ppt.util.Emu(4381678), mat2ppt.util.Emu(2442186), mat2ppt.util.Emu(1828800));
end

% picture Picture 7
img = fullfile(assets, 'image12.gif');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1295400), mat2ppt.util.Emu(5067301), mat2ppt.util.Emu(1371600), mat2ppt.util.Emu(1371600));
end

% picture Picture 9
img = fullfile(assets, 'image12.gif');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3505200), mat2ppt.util.Emu(5067301), mat2ppt.util.Emu(1371600), mat2ppt.util.Emu(1371600));
end

% picture Picture 10
img = fullfile(assets, 'image12.gif');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6934200), mat2ppt.util.Emu(5067301), mat2ppt.util.Emu(1371600), mat2ppt.util.Emu(1371600));
end

% picture Picture 11
img = fullfile(assets, 'image13.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(2057400), mat2ppt.util.Emu(4038600), mat2ppt.util.Emu(4800600), mat2ppt.util.Emu(914400));
end

% picture Picture 1
img = fullfile(assets, 'image14.wmf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6400800), mat2ppt.util.Emu(3962400), mat2ppt.util.Emu(990600), mat2ppt.util.Emu(911627));
end


%% ===== Slide 6 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'The How of the Cable Effects Study';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Cable models are implemented using Nastran standard elements. Well integrated with standard analysis toolsLinear beam elements are appropriate, using composite properties and general formulation.Measurements showed that cable models must include shear: a Bernoulli-Euler beam formulation cannot predict cable dynamicsEquivalent cable properties in the Nastran deck are obtained through experiment and parameter estimationThe cable-to-structure model uses linear spring elements (PBUSH)Spring properties were identified through experiment Validation experiments used throughout the program for cable parameter estimation and modeling techniquesDemonstration experiment to verify methodsValidation and verification – it was a research program';


%% ===== Slide 7 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(228600), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(814388));
sp.text_frame().text = 'Research Topics not Includedin the Cable Effects Study';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(539750), mat2ppt.util.Emu(1676400), mat2ppt.util.Emu(8255000), mat2ppt.util.Emu(4746625));
sp.text_frame().text = 'Bundles of twisted pair conductors exceeding 30 pairs and 20 AWGLimited design space to maintain focusNonlinear cable modelsParameter extraction was based on the assumption of linear behaviorDetailed cable mechanicsModel-based cable bulk property derivationCable loss mechanism modelsInter-strand in a conductor, loss due to strain energy in the conductor shields or conductor-to-conductor lossLocalized cable tie-down behavior';


%% ===== Slide 8 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 24
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(228600), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(814388));
sp.text_frame().text = 'Cable Construction and Effects on Dynamics';

% picture Content Placeholder 22
img = fullfile(assets, 'image15.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6320839), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(2365961), mat2ppt.util.Emu(2819400));
end

% Content Placeholder 25
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(6096000), mat2ppt.util.Emu(1981200));
sp.text_frame().text = 'Bundles of twisted pair single-conductor wires stitched and wrapped with Kapton® tapeConsistent with spacecraft power and signal cable fabricationCables add damping and can shift modal frequencies';

% picture Picture 2
img = fullfile(assets, 'image16.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3962400), mat2ppt.util.Emu(1611313), mat2ppt.util.Emu(1622425), mat2ppt.util.Emu(4014787));
end

% picture Picture 4
img = fullfile(assets, 'image17.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(2895600), mat2ppt.util.Emu(1676400), mat2ppt.util.Emu(927100), mat2ppt.util.Emu(3930650));
end

% Rectangle 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(3028950), mat2ppt.util.Emu(2005013), mat2ppt.util.Emu(582613), mat2ppt.util.Emu(496887));

% Line 9
sp = sh.add_shape('line', mat2ppt.util.Emu(3621088), mat2ppt.util.Emu(1843088), mat2ppt.util.Emu(747712), mat2ppt.util.Emu(419100));

% Line 12
sp = sh.add_shape('line', mat2ppt.util.Emu(2550), mat2ppt.util.Emu(1849), mat2ppt.util.Emu(230), mat2ppt.util.Emu(1));

% Line 13
sp = sh.add_shape('line', mat2ppt.util.Emu(2871), mat2ppt.util.Emu(1851), mat2ppt.util.Emu(230), mat2ppt.util.Emu(1));

% Line 14
sp = sh.add_shape('line', mat2ppt.util.Emu(2866), mat2ppt.util.Emu(1802), mat2ppt.util.Emu(0), mat2ppt.util.Emu(104));

% Line 15
sp = sh.add_shape('line', mat2ppt.util.Emu(2790), mat2ppt.util.Emu(1804), mat2ppt.util.Emu(0), mat2ppt.util.Emu(104));

% picture Picture 14
img = fullfile(assets, 'image18.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3200400), mat2ppt.util.Emu(3429000), mat2ppt.util.Emu(1095375), mat2ppt.util.Emu(666750));
end

% picture Content Placeholder 4
img = fullfile(assets, 'image19.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(2971800), mat2ppt.util.Emu(4724400), mat2ppt.util.Emu(3702288));
end

% connector Straight Arrow Connector 26
sh.add_connector('straightConnector1', mat2ppt.util.Emu(1752600), mat2ppt.util.Emu(4343400), mat2ppt.util.Emu(3048000), mat2ppt.util.Emu(4344988));

% connector Straight Arrow Connector 29
sh.add_connector('straightConnector1', mat2ppt.util.Emu(3124200), mat2ppt.util.Emu(6172200), mat2ppt.util.Emu(5867400), mat2ppt.util.Emu(6173788));

% TextBox 31
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(3962400), mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(707886));
sp.text_frame().text = 'Cable not resonant';

% TextBox 32
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(5715000), mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(707886));
sp.text_frame().text = 'Cable resonant';


%% ===== Slide 9 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(991393), mat2ppt.util.Emu(176212), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(814388));
sp.text_frame().text = 'Attachment to Host Structure:Cable-Structure Interaction';

% Slide Number Placeholder 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(7010400), mat2ppt.util.Emu(6492875), mat2ppt.util.Emu(2133600), mat2ppt.util.Emu(365125));
sp.text_frame().text = '9';

% Content Placeholder 20
sp = sh.add_shape('rect', mat2ppt.util.Emu(4800600), mat2ppt.util.Emu(1295400), mat2ppt.util.Emu(3962400), mat2ppt.util.Emu(1905000));
sp.text_frame().text = 'TC-105 mounting tabs bonded to host structureAllow controllable cable attachment using zip-ties and installation tool (zip-tie gun)Lacing cord used as an alternative to zip-ties';

% picture Content Placeholder 7
img = fullfile(assets, 'image20.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4038600), mat2ppt.util.Emu(4191000), mat2ppt.util.Emu(5105400), mat2ppt.util.Emu(2135311));
end

% picture Picture 2
img = fullfile(assets, 'image16.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6162393), mat2ppt.util.Emu(2229212), mat2ppt.util.Emu(1622425), mat2ppt.util.Emu(4014787));
end

% TextBox 14
sp = sh.add_shape('rect', mat2ppt.util.Emu(4792065), mat2ppt.util.Emu(2473466), mat2ppt.util.Emu(1232755), mat2ppt.util.Emu(437192));
sp.text_frame().text = 'TC-105';

% TextBox 15
sp = sh.add_shape('rect', mat2ppt.util.Emu(7973878), mat2ppt.util.Emu(2787505), mat2ppt.util.Emu(1151626), mat2ppt.util.Emu(755338));
sp.text_frame().text = 'Lacing cord';

% TextBox 16
sp = sh.add_shape('rect', mat2ppt.util.Emu(4902874), mat2ppt.util.Emu(4460334), mat2ppt.util.Emu(1058626), mat2ppt.util.Emu(439246));
sp.text_frame().text = 'Cable';

% TextBox 17
sp = sh.add_shape('rect', mat2ppt.util.Emu(4667405), mat2ppt.util.Emu(5236198), mat2ppt.util.Emu(1410840), mat2ppt.util.Emu(757390));
sp.text_frame().text = 'Base Structure';

% connector Straight Arrow Connector 14
sh.add_connector('straightConnector1', mat2ppt.util.Emu(6025569), mat2ppt.util.Emu(2692712), mat2ppt.util.Emu(7131113), mat2ppt.util.Emu(2688881));

% connector Straight Arrow Connector 15
sh.add_connector('straightConnector1', mat2ppt.util.Emu(7342268), mat2ppt.util.Emu(2821498), mat2ppt.util.Emu(7974695), mat2ppt.util.Emu(3164988));

% connector Straight Arrow Connector 16
sh.add_connector('straightConnector1', mat2ppt.util.Emu(5961708), mat2ppt.util.Emu(4679948), mat2ppt.util.Emu(7324255), mat2ppt.util.Emu(4474678));

% connector Straight Arrow Connector 17
sh.add_connector('straightConnector1', mat2ppt.util.Emu(6077407), mat2ppt.util.Emu(5615218), mat2ppt.util.Emu(6871433), mat2ppt.util.Emu(5342827));

% picture Picture 2
img = fullfile(assets, 'image21.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(381000), mat2ppt.util.Emu(3095625), mat2ppt.util.Emu(1095375), mat2ppt.util.Emu(666750));
end

% connector Straight Arrow Connector 30
sh.add_connector('straightConnector1', mat2ppt.util.Emu(964669), mat2ppt.util.Emu(2980198), mat2ppt.util.Emu(813262), mat2ppt.util.Emu(3059643));

% TextBox 29
sp = sh.add_shape('rect', mat2ppt.util.Emu(914400), mat2ppt.util.Emu(1371600), mat2ppt.util.Emu(2667000), mat2ppt.util.Emu(707886));
sp.text_frame().text = 'Cable attachment to host structure';

% TextBox 24
sp = sh.add_shape('rect', mat2ppt.util.Emu(4191000), mat2ppt.util.Emu(3810000), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(400110));
sp.text_frame().text = 'Cable-structure interaction';


%% ===== Slide 10 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Cable Modeling Approach Overview';

% picture Picture 6
img = fullfile(assets, 'image22.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(838200), mat2ppt.util.Emu(1371600), mat2ppt.util.Emu(7253641), mat2ppt.util.Emu(5022689));
end


%% ===== Slide 11 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 4
img = fullfile(assets, 'image23.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5542356), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(3525444), mat2ppt.util.Emu(3962400));
end

% Rectangle 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(152400), mat2ppt.util.Emu(7162800), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'The Cable ParameterExtraction Mission and Approach';

% picture Picture 3
img = fullfile(assets, 'image24.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5486400), mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(3505200), mat2ppt.util.Emu(3917950));
end

% Rectangle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(5791200), mat2ppt.util.Emu(5184775));
sp.text_frame().text = 'Test-derived cable properties are neededWhat is the appropriate model for a cable?Inputs for linear finite element modelsExtensional modulus derived through testShear modulus based on lateral driving point mobility FRFs“Easy” to measureChallengesAccount for vibrometer time delay Cancel driving point fixture mass loading effectRepeated rootsLightly damped fixture modesParameter estimation algorithm Based on a beam model including shearSpecimen cross sectional area and extensional modulus from tensile testsDetermine area moment of inertia and k’GValidated through experiment';


%% ===== Slide 12 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 2
img = fullfile(assets, 'image25.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4953000), mat2ppt.util.Emu(3733800), mat2ppt.util.Emu(3733800), mat2ppt.util.Emu(2800350));
end

% picture Picture 1
img = fullfile(assets, 'image26.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(76200), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(4571697), mat2ppt.util.Emu(3428773));
end

% AutoShape 6
sp = sh.add_shape('upArrow', mat2ppt.util.Emu(2149456), mat2ppt.util.Emu(2934801), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(457200));

% AutoShape 7
sp = sh.add_shape('upArrow', mat2ppt.util.Emu(2698713), mat2ppt.util.Emu(2651143), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(457200));

% AutoShape 8
sp = sh.add_shape('upArrow', mat2ppt.util.Emu(3048000), mat2ppt.util.Emu(2590800), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(457200));

% AutoShape 9
sp = sh.add_shape('upArrow', mat2ppt.util.Emu(3303028), mat2ppt.util.Emu(2695630), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(457200));

% AutoShape 10
sp = sh.add_shape('upArrow', mat2ppt.util.Emu(3505200), mat2ppt.util.Emu(2858601), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(457200));

% AutoShape 11
sp = sh.add_shape('upArrow', mat2ppt.util.Emu(3694598), mat2ppt.util.Emu(3042714), mat2ppt.util.Emu(76200), mat2ppt.util.Emu(457200));

% Oval 13
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(1981200), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(1905000), mat2ppt.util.Emu(1600200));

% Rectangle 10
sp = sh.add_shape('rect', mat2ppt.util.Emu(4419600), mat2ppt.util.Emu(1397764), mat2ppt.util.Emu(4572000), mat2ppt.util.Emu(2107436));
sp.text_frame().text = 'The natural frequency-to-mode number progression of a cable follows a quadratic relationship This is how an beam behavesDiverges from elementary beam theory: shear must be included';

% AutoShape 14
sp = sh.add_shape('upArrow', mat2ppt.util.Emu(4596118), mat2ppt.util.Emu(3281584), mat2ppt.util.Emu(304800), mat2ppt.util.Emu(2052641));

% Title 13
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(228600), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(814388));
sp.text_frame().text = 'Cable Natural Frequency Progression:The Beam Model Indicator';


%% ===== Slide 13 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(269875), mat2ppt.util.Emu(7159625), mat2ppt.util.Emu(720725));
sp.text_frame().text = 'Bare Cable Lateral Test: Parameter Estimation Approach';

% Rectangle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(2895600), mat2ppt.util.Emu(1295400), mat2ppt.util.Emu(6096000), mat2ppt.util.Emu(5181600));
sp.text_frame().text = 'Measurements are cleaned up Modal parameter estimation step (        ) and k´G determined from modal frequenciesEstimate I and effective diameterDamping averaged over all modesEstimated parameters benchmarked by comparing shear model frequencies and measurementParameters estimated for different spans of each cable specimen and multiple specimens of each cable construction';

% picture Picture 4
img = fullfile(assets, 'image28.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(228601), mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(2220702), mat2ppt.util.Emu(5154323));
end

% TODO: unhandled graphicFrame Object 6


%% ===== Slide 14 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Parameter Estimation: Tie down stiffness';

% Content Placeholder 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(1219201), mat2ppt.util.Emu(6248400), mat2ppt.util.Emu(2438400));
sp.text_frame().text = 'Rod-on-beam eliminates cable property uncertainty Tune attachment stiffness to correlate test and model FRFsDirect measurement tests an alternative means to estimate Assumes cable is infinitely stiff over frequency range of estimate';

% picture Picture 3
img = fullfile(assets, 'image29.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4038600), mat2ppt.util.Emu(4267200), mat2ppt.util.Emu(1779691), mat2ppt.util.Emu(2373312));
end

% Text Box 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(4419600), mat2ppt.util.Emu(4038600), mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(340735));
sp.text_frame().text = 'Copper Rod';

% picture Picture 13
img = fullfile(assets, 'image30.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(152400), mat2ppt.util.Emu(4343400), mat2ppt.util.Emu(5181600), mat2ppt.util.Emu(2377631));
end

% picture Picture 4
img = fullfile(assets, 'image31.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5470181), mat2ppt.util.Emu(4343400), mat2ppt.util.Emu(3673819), mat2ppt.util.Emu(2286953));
end


%% ===== Slide 15 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Text Box 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(269875), mat2ppt.util.Emu(7162800), mat2ppt.util.Emu(815975));
sp.text_frame().text = 'Model Validation: Tie downs';

% Text Box 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(4724400), mat2ppt.util.Emu(4038600));
sp.text_frame().text = 'Tie-down parameters play an important role in cable/structure interactionsOffset more important for stiff cables than for compliant onesRod-on-beam based attachment stiffness values used in cable-on-beam modelsStiffnesses from “direct measurement” tests did not perform as well';

% TextBox 7
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(5486400), mat2ppt.util.Emu(4343400), mat2ppt.util.Emu(1015663));
sp.text_frame().text = 'From rod-on-beam correlation: K1=K2=K3 = 3x104 lbf/inchK5 =K6 = 100 inch-lbf/rad';

% picture Picture 2
img = fullfile(assets, 'image32.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4419600), mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(4572000), mat2ppt.util.Emu(2603549));
end

% picture Picture 1
img = fullfile(assets, 'image33.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4876800), mat2ppt.util.Emu(3810001), mat2ppt.util.Emu(4064985), mat2ppt.util.Emu(3048000));
end


%% ===== Slide 16 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Cable-on-Beam Results';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(4191000), mat2ppt.util.Emu(4572000));
sp.text_frame().text = 'Cable effects differ over two distinct frequency rangesMass and stiffness effects below cable resonanceIncreased damping above cable resonanceGood agreement between measured and modeled dynamicsBuild-to-build variability is evident in predictions using “coupon” or “family” cable properties';

% picture Picture 14
img = fullfile(assets, 'image18.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6553200), mat2ppt.util.Emu(2133600), mat2ppt.util.Emu(1095375), mat2ppt.util.Emu(666750));
end

% picture Content Placeholder 4
img = fullfile(assets, 'image19.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(2971800), mat2ppt.util.Emu(4724400), mat2ppt.util.Emu(3702288));
end

% connector Straight Arrow Connector 14
sh.add_connector('straightConnector1', mat2ppt.util.Emu(1752600), mat2ppt.util.Emu(4343400), mat2ppt.util.Emu(3048000), mat2ppt.util.Emu(4344988));

% connector Straight Arrow Connector 15
sh.add_connector('straightConnector1', mat2ppt.util.Emu(3124200), mat2ppt.util.Emu(6172200), mat2ppt.util.Emu(5867400), mat2ppt.util.Emu(6173788));

% TextBox 9
sp = sh.add_shape('rect', mat2ppt.util.Emu(5105400), mat2ppt.util.Emu(1295400), mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(707886));
sp.text_frame().text = 'Cable not resonant';

% TextBox 10
sp = sh.add_shape('rect', mat2ppt.util.Emu(7315200), mat2ppt.util.Emu(5334000), mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(707886));
sp.text_frame().text = 'Cable resonant';

% picture Picture 7
img = fullfile(assets, 'image34.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4038600), mat2ppt.util.Emu(2264053), mat2ppt.util.Emu(5029200), mat2ppt.util.Emu(3679547));
end

% picture Picture 7
img = fullfile(assets, 'image34.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4642217), mat2ppt.util.Emu(1295400), mat2ppt.util.Emu(4288791), mat2ppt.util.Emu(990600));
end


%% ===== Slide 17 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(228600), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(814388));
sp.text_frame().text = 'Model Validation Effort –A Panel Structure';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(1239838), mat2ppt.util.Emu(5257800), mat2ppt.util.Emu(5183187));
sp.text_frame().text = 'Mission: A test case to prove the applicability of the cable test, parameter estimation and modelling methods to a spacecraft-like panelGround rules: Conduct experiments to quantify dynamics. Modelling effort uses estimated cable properties, but cannot include model tuning.Test caseAluminum panel 2’ x 2’ x 3/16”Three cast aluminum electronics boxesCable mass ratios ~ 3% or 6%';

% picture Picture 1
img = fullfile(assets, 'image35.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(6019800), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(2874357), mat2ppt.util.Emu(4307821));
end


%% ===== Slide 18 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Measured Driving Point FRFs';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(1239838), mat2ppt.util.Emu(4419600), mat2ppt.util.Emu(5183187));
sp.text_frame().text = 'Little influence in panel dynamics below cable resonanceVarious cable spans become resonant between ~75 and ~175 HzDetermined by cable type and open span dimensionsLow cable-to-panel mass ratio limits the cable influence on the coupled dynamics';

% picture Picture 2
img = fullfile(assets, 'image36.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4572000), mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(4114800), mat2ppt.util.Emu(2743200));
end

% picture Picture 2
img = fullfile(assets, 'image36.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5334000), mat2ppt.util.Emu(4267200), mat2ppt.util.Emu(2743200), mat2ppt.util.Emu(228600));
end


%% ===== Slide 19 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 4
img = fullfile(assets, 'image38.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4708936), mat2ppt.util.Emu(1905000), mat2ppt.util.Emu(4435064), mat2ppt.util.Emu(3962400));
end

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Panel Model Validation';

% TextBox 12
sp = sh.add_shape('rect', mat2ppt.util.Emu(5181600), mat2ppt.util.Emu(5486400), mat2ppt.util.Emu(3200400), mat2ppt.util.Emu(677108));
sp.text_frame().text = 'Running RMS error, zeroed at 90 and 200 Hz';

% picture Picture 5
img = fullfile(assets, 'image39.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4419600), mat2ppt.util.Emu(1600200), mat2ppt.util.Emu(4367213), mat2ppt.util.Emu(3902075));
end

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(4800600), mat2ppt.util.Emu(5280025));
sp.text_frame().text = 'Compared traditional modelling approach (i.e., nonstructural mass) with dynamic cable modelsRunning RMS metric is driven by modal dampingLumped mass approach does not account for coupling and over estimates responseNonstructural mass approach may be adequate for low frequencies and low cable/structure mass ratios';

% picture Picture 3
img = fullfile(assets, 'image40.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4724400), mat2ppt.util.Emu(2057400), mat2ppt.util.Emu(4419600), mat2ppt.util.Emu(4419600));
end

% TODO: unhandled graphicFrame Object 2

% picture Picture 3
img = fullfile(assets, 'image41.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4676132), mat2ppt.util.Emu(1981200), mat2ppt.util.Emu(4467868), mat2ppt.util.Emu(4876800));
end

% TextBox 17
sp = sh.add_shape('rect', mat2ppt.util.Emu(4648200), mat2ppt.util.Emu(5562600), mat2ppt.util.Emu(4495800), mat2ppt.util.Emu(923330));
sp.text_frame().text = 'Least benefit from dynamic cable models with low mass ratio and/or large magnitude non-interacting modes';


%% ===== Slide 20 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Shear Modulus Choice';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(76200), mat2ppt.util.Emu(1981200), mat2ppt.util.Emu(4362450), mat2ppt.util.Emu(4441825));
sp.text_frame().text = 'Use of “family” or “coupon” shear modulus values does not have large impact on model accuracy for cables testedDifferent conclusion than for cable-on-beam test';

% picture Picture 5
img = fullfile(assets, 'image42.emf');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4343400), mat2ppt.util.Emu(1447800), mat2ppt.util.Emu(4800600), mat2ppt.util.Emu(5029200));
end


%% ===== Slide 21 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Major Findings';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'A shear beam model predicts cable dynamicsCoupon tests may be justified for critical applicationsVariability in cable properties can be traced toCable construction due to hand fabrication Differences in wire structural properties can vary between lotsRunning stitch tensionThere is evidence of cable property dependence on spanMeasurement of cable extensional modulus requires a low load capacity tensile test machine and a custom extensometer witness fixtureRod-on-beam validation experiments were instrumental in refining connection stiffness value estimates';


%% ===== Slide 22 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Summary';

% Content Placeholder 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Innovative test, analysis and modelling approaches were developed to Increase accuracy of models to include the influence of power and signal cablesUsed standard linear finite element model methodsCables can have a significant impact on coupled structure dynamicsMass loading on the cable stiffness lineIncreased damping above first cable resonanceLarge reductions in resonant response when cable and host structure natural frequencies are close to one anotherThe traditional nonstructural mass approach cannot predict the cable interaction, leading to overestimates of resonant response';


%% ===== Slide 23 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Open Research Topics';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(1239838), mat2ppt.util.Emu(8763000), mat2ppt.util.Emu(5183187));
sp.text_frame().text = 'Develop cable fabrication techniques to increase cable predictability for structural dynamicsExtend efforts to include other cable construction methodsConsiderable interest in the space communityExtend efforts to more massive cables and those with bends and connectorsCable service loop modelling Study behavior of cables under launch vibration and mechanical shock conditionsWorkmanship under high loading conditionsMounting bracket strength Concerns in the space industry and DoD Detailed cable mechanicsReduce dependence on empirically derived propertiesAccelerate modelling and analysis programs';


%% ===== Slide 24 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(685800), mat2ppt.util.Emu(1295400), mat2ppt.util.Emu(7772400), mat2ppt.util.Emu(1470025));
sp.text_frame().text = 'Questions';


%% ===== Slide 25 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Acknowledgments';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Thanks to the Air Force Research Laboratory and the Air Force Office for Scientific Research for funding.Thanks to the following project collaborators without whom this work would not have been possible.  Dr. Vit Babuška - Sandia National LaboratoriesDr. Emil Ardelean - Schafer CorporationJames Goodding - CSA EngineeringCody Griffee - CSA EngineeringGreg Mehle - CSA EngineeringDr. Lawrence “Robbie” Robertson AFRL, SV*Dr. Steve Lane - AFRL, SV*Brea Ingram- AFRL, SV**AFRL, SV = Air Force Research Laboratory, Space Vehicles Directorate';


%% ===== Slide 26 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365125), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(1325563));
sp.text_frame().text = 'Cable Tie Down Details';

% picture Picture 3
img = fullfile(assets, 'image43.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1981200), mat2ppt.util.Emu(5260174), mat2ppt.util.Emu(3124200));
end


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide6 sp used title-area default geom: Title 1
% GAP: slide6 sp used title-area default geom: Content Placeholder 2
% GAP: slide10 sp used title-area default geom: Title 1
% GAP: slide13 unhandled graphicFrame Object 6
% GAP: slide14 sp used title-area default geom: Title 1
% GAP: slide16 sp used title-area default geom: Title 1
% GAP: slide18 sp used title-area default geom: Title 1
% GAP: slide19 sp used title-area default geom: Title 1
% GAP: slide19 unhandled graphicFrame Object 2
% GAP: slide20 sp used title-area default geom: Title 1
% GAP: slide21 sp used title-area default geom: Title 1
% GAP: slide21 sp used title-area default geom: Content Placeholder 2
% GAP: slide22 sp used title-area default geom: Title 4
% GAP: slide22 sp used title-area default geom: Content Placeholder 5
% GAP: slide23 sp used title-area default geom: Title 1
% GAP: slide25 sp used title-area default geom: Title 1
% GAP: slide25 sp used title-area default geom: Content Placeholder 2
% GAP: slide26 sp used title-area default geom: Title 1
