%% demo.m — Recreate 02_Box_FoundingDocs__Dissolution_DistributionOfAssets_FlowChart via Mat2Ppt public API
% Source: 02_Box_FoundingDocs__Dissolution_DistributionOfAssets_FlowChart.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Flowchart: Decision 4
sp = sh.add_shape('flowChartDecision', mat2ppt.util.Emu(5728260), mat2ppt.util.Emu(132588), mat2ppt.util.Emu(1855089), mat2ppt.util.Emu(987552));
sp.text_frame().text = 'Are the Assets Artistic?';

% Flowchart: Decision 5
sp = sh.add_shape('flowChartDecision', mat2ppt.util.Emu(3700272), mat2ppt.util.Emu(911352), mat2ppt.util.Emu(2395728), mat2ppt.util.Emu(1014984));
sp.text_frame().text = 'Assets Reside at a School or Nonprofit?';

% Flowchart: Decision 6
sp = sh.add_shape('flowChartDecision', mat2ppt.util.Emu(1455384), mat2ppt.util.Emu(1796796), mat2ppt.util.Emu(2606040), mat2ppt.util.Emu(1133856));
sp.text_frame().text = 'School or Nonprofit will Accept Gift of  Artistic Assets?';

% Flowchart: Process 7
sp = sh.add_shape('flowChartProcess', mat2ppt.util.Emu(150876), mat2ppt.util.Emu(5690616), mat2ppt.util.Emu(1508760), mat2ppt.util.Emu(972312));
sp.text_frame().text = 'A) Artistic Assets gifted to school or non-profit where they reside';

% Flowchart: Process 8
sp = sh.add_shape('flowChartProcess', mat2ppt.util.Emu(3443538), mat2ppt.util.Emu(4507992), mat2ppt.util.Emu(2370812), mat2ppt.util.Emu(2154936));
sp.text_frame().text = 'C) Artistic assets distributed equally among other affiliate schools where assets reside (or their specified non-profits).  Receiving schools must pay for associated packaging and transportation costs beyond what the St. Luke Guild monetary assets will cover.';

% Flowchart: Process 9
sp = sh.add_shape('flowChartProcess', mat2ppt.util.Emu(7729012), mat2ppt.util.Emu(5675376), mat2ppt.util.Emu(1975104), mat2ppt.util.Emu(987552));
sp.text_frame().text = 'D) Monetary gifts tied to specific programs returned to original donors';

% Flowchart: Process 10
sp = sh.add_shape('flowChartProcess', mat2ppt.util.Emu(9841687), mat2ppt.util.Emu(5340096), mat2ppt.util.Emu(2255824), mat2ppt.util.Emu(1322832));
sp.text_frame().text = 'F) Remaining monetary assets not used for distributing artistic assets distributed equally among schools where artistic assets reside';

% Flowchart: Process 11
sp = sh.add_shape('flowChartProcess', mat2ppt.util.Emu(5951921), mat2ppt.util.Emu(5675376), mat2ppt.util.Emu(1639520), mat2ppt.util.Emu(987552));
sp.text_frame().text = 'E) Non-monetary assets sold and proceeds enter general fund';

% Flowchart: Process 12
sp = sh.add_shape('flowChartProcess', mat2ppt.util.Emu(1797207), mat2ppt.util.Emu(5340096), mat2ppt.util.Emu(1508760), mat2ppt.util.Emu(1322832));
sp.text_frame().text = 'B) Artistic Assets gifted to non-profit specified by school or non-profit where the asset resides.';

% Flowchart: Decision 13
sp = sh.add_shape('flowChartDecision', mat2ppt.util.Emu(7235877), mat2ppt.util.Emu(1063752), mat2ppt.util.Emu(2395728), mat2ppt.util.Emu(1014984));
sp.text_frame().text = 'Are Assets Monetary?';

% Flowchart: Decision 14
sp = sh.add_shape('flowChartDecision', mat2ppt.util.Emu(9037245), mat2ppt.util.Emu(1876044), mat2ppt.util.Emu(2395728), mat2ppt.util.Emu(1133856));
sp.text_frame().text = 'Was money donated for a specific program?';

% connector Connector: Elbow 16
sh.add_connector('bentConnector2', mat2ppt.util.Emu(9631605), mat2ppt.util.Emu(1571244), mat2ppt.util.Emu(10235109), mat2ppt.util.Emu(1876044));

% connector Connector: Elbow 18
sh.add_connector('bentConnector2', mat2ppt.util.Emu(6771681), mat2ppt.util.Emu(5675376), mat2ppt.util.Emu(7235877), mat2ppt.util.Emu(1571244));

% connector Connector: Elbow 20
sh.add_connector('bentConnector2', mat2ppt.util.Emu(8716565), mat2ppt.util.Emu(5675376), mat2ppt.util.Emu(9037246), mat2ppt.util.Emu(2442972));

% connector Connector: Elbow 22
sh.add_connector('bentConnector4', mat2ppt.util.Emu(11432973), mat2ppt.util.Emu(2442972), mat2ppt.util.Emu(10969599), mat2ppt.util.Emu(5340096));

% connector Connector: Elbow 24
sh.add_connector('bentConnector2', mat2ppt.util.Emu(7583349), mat2ppt.util.Emu(626364), mat2ppt.util.Emu(8433741), mat2ppt.util.Emu(1063752));

% connector Connector: Elbow 26
sh.add_connector('bentConnector2', mat2ppt.util.Emu(4898136), mat2ppt.util.Emu(911352), mat2ppt.util.Emu(5728260), mat2ppt.util.Emu(626364));

% connector Connector: Elbow 28
sh.add_connector('bentConnector2', mat2ppt.util.Emu(905256), mat2ppt.util.Emu(5690616), mat2ppt.util.Emu(1455384), mat2ppt.util.Emu(2363724));

% Flowchart: Decision 29
sp = sh.add_shape('flowChartDecision', mat2ppt.util.Emu(2880360), mat2ppt.util.Emu(2662047), mat2ppt.util.Emu(3215640), mat2ppt.util.Emu(1471422));
sp.text_frame().text = 'School or non-profit specifies alternate non-profit to receive artistic assets?';

% connector Connector: Elbow 31
sh.add_connector('bentConnector2', mat2ppt.util.Emu(2551588), mat2ppt.util.Emu(5340096), mat2ppt.util.Emu(2880361), mat2ppt.util.Emu(3397758));

% connector Connector: Elbow 33
sh.add_connector('bentConnector4', mat2ppt.util.Emu(6096000), mat2ppt.util.Emu(3397758), mat2ppt.util.Emu(4628944), mat2ppt.util.Emu(4507992));

% connector Connector: Elbow 36
sh.add_connector('bentConnector2', mat2ppt.util.Emu(4061424), mat2ppt.util.Emu(2363724), mat2ppt.util.Emu(4488180), mat2ppt.util.Emu(2662047));

% connector Connector: Elbow 38
sh.add_connector('bentConnector2', mat2ppt.util.Emu(2758404), mat2ppt.util.Emu(1796796), mat2ppt.util.Emu(3700272), mat2ppt.util.Emu(1418844));

% connector Connector: Elbow 40
sh.add_connector('bentConnector2', mat2ppt.util.Emu(6096000), mat2ppt.util.Emu(1418844), mat2ppt.util.Emu(6336832), mat2ppt.util.Emu(3914966));

% TextBox 44
sp = sh.add_shape('rect', mat2ppt.util.Emu(7660617), mat2ppt.util.Emu(321171), mat2ppt.util.Emu(530391), mat2ppt.util.Emu(276999));
sp.text_frame().text = 'No';

% TextBox 45
sp = sh.add_shape('rect', mat2ppt.util.Emu(6772672), mat2ppt.util.Emu(1278427), mat2ppt.util.Emu(530391), mat2ppt.util.Emu(276999));
sp.text_frame().text = 'No';

% TextBox 46
sp = sh.add_shape('rect', mat2ppt.util.Emu(11292896), mat2ppt.util.Emu(2165973), mat2ppt.util.Emu(530391), mat2ppt.util.Emu(276999));
sp.text_frame().text = 'No';

% TextBox 47
sp = sh.add_shape('rect', mat2ppt.util.Emu(3980555), mat2ppt.util.Emu(2155692), mat2ppt.util.Emu(530391), mat2ppt.util.Emu(276999));
sp.text_frame().text = 'No';

% TextBox 48
sp = sh.add_shape('rect', mat2ppt.util.Emu(5967829), mat2ppt.util.Emu(3093720), mat2ppt.util.Emu(530391), mat2ppt.util.Emu(276999));
sp.text_frame().text = 'No';

% TextBox 49
sp = sh.add_shape('rect', mat2ppt.util.Emu(5967885), mat2ppt.util.Emu(1165362), mat2ppt.util.Emu(530391), mat2ppt.util.Emu(276999));
sp.text_frame().text = 'No';

% TextBox 51
sp = sh.add_shape('rect', mat2ppt.util.Emu(5048002), mat2ppt.util.Emu(347847), mat2ppt.util.Emu(530391), mat2ppt.util.Emu(276999));
sp.text_frame().text = 'Yes';

% TextBox 52
sp = sh.add_shape('rect', mat2ppt.util.Emu(2958675), mat2ppt.util.Emu(1123397), mat2ppt.util.Emu(530391), mat2ppt.util.Emu(276999));
sp.text_frame().text = 'Yes';

% TextBox 53
sp = sh.add_shape('rect', mat2ppt.util.Emu(833535), mat2ppt.util.Emu(2099126), mat2ppt.util.Emu(530391), mat2ppt.util.Emu(276999));
sp.text_frame().text = 'Yes';

% TextBox 54
sp = sh.add_shape('rect', mat2ppt.util.Emu(2412588), mat2ppt.util.Emu(3116562), mat2ppt.util.Emu(530391), mat2ppt.util.Emu(276999));
sp.text_frame().text = 'Yes';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);
