%% demo.m — Recreate 16_Dropbox_Friends__Maile_UMary_Course Plan_TheoMajor_ArtMinor_Graphic via Mat2Ppt public API
% Source: 16_Dropbox_Friends__Maile_UMary_Course Plan_TheoMajor_ArtMinor_Graphic.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(36576000);
prs.slide_height = mat2ppt.util.Emu(13716000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle: Rounded Corners 104
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(13373099), mat2ppt.util.Emu(1371600), mat2ppt.util.Emu(4000498), mat2ppt.util.Emu(11087100));
sp.text_frame().text = 'Semester in Rome';

% connector Straight Connector 4
sh.add_connector('line', mat2ppt.util.Emu(18288000), mat2ppt.util.Emu(0), mat2ppt.util.Emu(18288000), mat2ppt.util.Emu(13716000));

% connector Straight Connector 7
sh.add_connector('line', mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(0), mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(13716000));

% connector Straight Connector 8
sh.add_connector('line', mat2ppt.util.Emu(27432000), mat2ppt.util.Emu(0), mat2ppt.util.Emu(27432000), mat2ppt.util.Emu(13716000));

% Rectangle: Rounded Corners 9
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(914400), mat2ppt.util.Emu(3341246), mat2ppt.util.Emu(2387595), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'FYE 122L - President’s Seminar (0, F)';

% Rectangle: Rounded Corners 10
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(914400), mat2ppt.util.Emu(4853692), mat2ppt.util.Emu(2387595), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'ART 127 - Introduction to Drawing (3, ?)';

% Rectangle: Rounded Corners 11
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(9167021), mat2ppt.util.Emu(5474144), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'PHI 310 - Philosophy of the Human Person (3, ?)';

% Rectangle: Rounded Corners 12
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(14173200), mat2ppt.util.Emu(3653943), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 234 - Benedict: Yesterday and Today (3, B, Rome)';

% Rectangle: Rounded Corners 13
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(914400), mat2ppt.util.Emu(7878582), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'LAT 101 - Beginning Latin I (3, F)';

% Rectangle: Rounded Corners 22
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(914400), mat2ppt.util.Emu(6366137), mat2ppt.util.Emu(2387589), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'ENG 121 - Composition II (3, B)';

% Rectangle: Rounded Corners 40
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(5029200), mat2ppt.util.Emu(3658366), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'MAT 215 - Elements of Mathematics (3, B)';

% Rectangle: Rounded Corners 41
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(9186648), mat2ppt.util.Emu(1847089), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'SCI 209 - Science & Quantitative Thinking (3/1, S)';

% Rectangle: Rounded Corners 44
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(914400), mat2ppt.util.Emu(9391027), mat2ppt.util.Emu(2374892), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 120 - Search for God (3, B)';

% Rectangle: Rounded Corners 45
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(5029200), mat2ppt.util.Emu(10903473), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 250 - Sacred Tradition (3, ?)';

% Rectangle: Rounded Corners 46
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(914400), mat2ppt.util.Emu(10903473), mat2ppt.util.Emu(2285995), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 260 - Sacred Scripture (3, F)';

% Rectangle: Rounded Corners 47
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(19609308), mat2ppt.util.Emu(7389378), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'HIS 103 - Western Civ in World History I (3, ?)';

% Rectangle: Rounded Corners 51
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(5029200), mat2ppt.util.Emu(9092197), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'PHI 108 - Search for Truth (3, B)';

% Rectangle: Rounded Corners 76
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(914400), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(2387593), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'FYE 122 - First-Year Experience (1,B)';

% Rectangle: Rounded Corners 146
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(14147792), mat2ppt.util.Emu(5451790), mat2ppt.util.Emu(2311407), mat2ppt.util.Emu(1063310));
sp.text_frame().text = 'PHI 210 – Search for Happiness: Faith and Reason in Life (3, S, Rome)';

% Rectangle: Rounded Corners 147
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(5029200), mat2ppt.util.Emu(1847089), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'MAT 200 - Computing (3, ?)';

% Rectangle: Rounded Corners 148
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(9167021), mat2ppt.util.Emu(9085833), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'ART 235 - Art Practicum (2, B)';

% Rectangle: Rounded Corners 1
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(699512), mat2ppt.util.Emu(244094), mat2ppt.util.Emu(6844285), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'Freshman (2025-26)         Fall – 16                                 Spring - 18';

% Rectangle: Rounded Corners 2
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(10041875), mat2ppt.util.Emu(228600), mat2ppt.util.Emu(6400800), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'Sophomore (2026-27)Fall – 17                                        Spring - 15';

% Rectangle: Rounded Corners 3
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(19659600), mat2ppt.util.Emu(228600), mat2ppt.util.Emu(6400800), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'Junior (2027-28)Fall – 17                                        Spring - 16';

% Rectangle: Rounded Corners 5
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(28809946), mat2ppt.util.Emu(228600), mat2ppt.util.Emu(6400800), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'Senior (2028-29)Fall – 16                                        Spring - 13';

% Rectangle: Rounded Corners 35
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(9167021), mat2ppt.util.Emu(10903473), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'ART 310 - Art History I (3, F)';

% Rectangle: Rounded Corners 20
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(7658100), mat2ppt.util.Emu(-1477736), mat2ppt.util.Emu(2057399), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THEO-3420:Hist of Cath Ch I';

% Rectangle: Rounded Corners 25
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(14198607), mat2ppt.util.Emu(1847089), mat2ppt.util.Emu(2235186), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'CLA 311 - Grandeur of Rome (3, B, Rome)';

% Rectangle: Rounded Corners 26
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(9167021), mat2ppt.util.Emu(3676976), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'HIS 104 - Western Civ in World History II (3, ?)';

% Rectangle: Rounded Corners 27
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(17310116), mat2ppt.util.Emu(12609576), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'ART 410 - Art History II (3, S)';

% Rectangle: Rounded Corners 28
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(5029200), mat2ppt.util.Emu(7280920), mat2ppt.util.Emu(2235186), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'LAT 102 - Beginning Latin II (3, S)';

% Rectangle: Rounded Corners 29
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(14147792), mat2ppt.util.Emu(9806696), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'ART 121 - The Art of Italy (3, S, Rome)';

% Rectangle: Rounded Corners 31
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(19659600), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'ENG 330 - Survey of World Literature I (3, F)';

% Rectangle: Rounded Corners 32
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(19659600), mat2ppt.util.Emu(10972800), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'ART 335 - Art Practicum (3, B)';

% Rectangle: Rounded Corners 33
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(19659600), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(2235186), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'LAT 201 - Second Year Latin I (3, F)';

% Rectangle: Rounded Corners 34
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(5029200), mat2ppt.util.Emu(5469643), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 341 - Theology of the Human Person (3, ?)';

% Rectangle: Rounded Corners 42
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(19659600), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 270 - Moral Theology (3, ?)';

% Rectangle: Rounded Corners 59
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(9167021), mat2ppt.util.Emu(7199883), mat2ppt.util.Emu(2235186), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'CLA 201 - Classical Etymology (2, ?)';

% Rectangle: Rounded Corners 77
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(23774400), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'ENG 331 - Survey of World Literature II (3, S)';

% Rectangle: Rounded Corners 79
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(23774400), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(2235186), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'LAT 201 - Second Year Latin I (3, F)';

% Rectangle: Rounded Corners 80
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(23774400), mat2ppt.util.Emu(5486400), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 321 - Sacramental Theology (3, ?)';

% Rectangle: Rounded Corners 81
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(23774400), mat2ppt.util.Emu(7315200), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 315 - Virtue and Character (3, ?)';

% Rectangle: Rounded Corners 85
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(23768055), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'COM 300 - Visual Communication (3, ?)';

% Rectangle: Rounded Corners 86
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(32924745), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'HUM 499 - Senior Competency Testing (0, B)';

% Rectangle: Rounded Corners 87
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(7543799), mat2ppt.util.Emu(14744700), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'MUS 212 - Concert Choir (1, B)';

% Rectangle: Rounded Corners 89
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(32924745), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(2235186), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'PHI 422 - Aquinas & the Natural Law (3, F)';

% Rectangle: Rounded Corners 90
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(32924745), mat2ppt.util.Emu(5486400), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 303 - Church History (3, ?)';

% Rectangle: Rounded Corners 92
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(32924745), mat2ppt.util.Emu(7315200), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 429 - Seminar in Theology (3, ?)';

% Rectangle: Rounded Corners 95
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(28803600), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'PHI 327 - Metaphysics (3, F)';

% Rectangle: Rounded Corners 96
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(28803600), mat2ppt.util.Emu(10972800), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'ART 135 - Art Practicum (1, B)';

% Rectangle: Rounded Corners 97
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(28803600), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(2235186), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 302 - Suffering and Christian Healing (3, F)';

% Rectangle: Rounded Corners 98
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(28803600), mat2ppt.util.Emu(7315200), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'PHI 415 - Philosophical Theology (3, ?)';

% Rectangle: Rounded Corners 100
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(28803600), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 440 - The Theology and Legacy of St. Augustine (3, ?)';

% Rectangle: Rounded Corners 101
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(28803600), mat2ppt.util.Emu(5486400), mat2ppt.util.Emu(2235186), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 326 - Christian Marriage (3, ?)';

% Rectangle: Rounded Corners 102
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(32924745), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'THE 490 - St. Thomas Aquinas, the Angelic Doctor (3, ?)';

% TextBox 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(13373099), mat2ppt.util.Emu(13830300), mat2ppt.util.Emu(5486401), mat2ppt.util.Emu(3139321));
sp.text_frame().text = 'Fall and Spring Semester100-level Italian Language and Culture course (3 credits, liberal arts core elective)ART 121 Art of Italy (3 credits, Art core)CTH/PHI 210 Search for Happiness (3 credits, Ethics core)THE/CTH 234 Benedict: Yesterday and Today (3 credits, Theology core or “THE 200-level or above” core elective) HIS/CLA 311 Grandeur of Rome (3 credits, liberal arts core elective)';

% Rectangle: Rounded Corners 14
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(14147792), mat2ppt.util.Emu(8069092), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'ITA 101 – Beginning Italian (3, B, Rome)';

% Rectangle: Rounded Corners 15
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(10401300), mat2ppt.util.Emu(-1470440), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'Core BA Class';

% Rectangle: Rounded Corners 16
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(13601700), mat2ppt.util.Emu(-1444507), mat2ppt.util.Emu(2235186), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'Classics Minor';

% Rectangle: Rounded Corners 17
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(16669992), mat2ppt.util.Emu(-1425741), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'Theology Minor';

% Rectangle: Rounded Corners 18
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(19596116), mat2ppt.util.Emu(-1371600), mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(914400));
sp.text_frame().text = 'Art Minor';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);
