%% demo.m — Recreate 13_Dropbox_Education__Engineering_CareerOverview_SHS_DMCoombs_20210407_r via Mat2Ppt public API
% Source: 13_Dropbox_Education__Engineering_CareerOverview_SHS_DMCoombs_20210407_r.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(9144000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(190500), mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(8763000), mat2ppt.util.Emu(2362200));

% Title 10
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(1635760), mat2ppt.util.Emu(8610600), mat2ppt.util.Emu(1640840));
sp.text_frame().text = 'Mechanical EngineeringCareer Overview';

% Subtitle 11
sp = sh.add_shape('rect', mat2ppt.util.Emu(1981200), mat2ppt.util.Emu(3505200), mat2ppt.util.Emu(5486400), mat2ppt.util.Emu(1295400));
sp.text_frame().text = 'Douglas CoombsApril 8, 2021';


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(0), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(1084263));
sp.text_frame().text = 'Overview';


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(0), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(1084263));
sp.text_frame().text = 'Brief Personal Intro';


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% TODO: group shape Group 18

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(0), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(1084263));
sp.text_frame().text = 'Types of Engineering';

% TODO: group shape Group 11

% TODO: group shape Group 25

% TODO: group shape Group 35

% TODO: group shape Group 43


%% ===== Slide 5 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(0), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(1084263));
sp.text_frame().text = 'Educational Requirements';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(76200), mat2ppt.util.Emu(1143001), mat2ppt.util.Emu(9067800), mat2ppt.util.Emu(4343400));
sp.text_frame().text = 'A bachelors degree in engineering  entry level jobsA master’s (minimum) is required for more advanced projects Most flexible degree.  Takes an extra two years after getting a bachelor’s degreeMore advanced engineering pays better – Excellent investment of timeA PhD is required for very high level projects Can narrow opportunities.  Increases pay in many fields but can take a long time to attain (typically 2-8 years, average of 3-4).Sometimes the monetary pay-off isn’t there – Succeed or fail quickly is a good strategyEngineers get paid to go to graduate school.  They only take out loans for undergrad.';

% picture Picture 5
img = fullfile(assets, 'image30.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(2438401), mat2ppt.util.Emu(4497352), mat2ppt.util.Emu(4876800), mat2ppt.util.Emu(2371533));
end

% connector Straight Arrow Connector 7
sh.add_connector('straightConnector1', mat2ppt.util.Emu(5029200), mat2ppt.util.Emu(4876800), mat2ppt.util.Emu(7162800), mat2ppt.util.Emu(4876800));

% TextBox 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(5032169), mat2ppt.util.Emu(4557204), mat2ppt.util.Emu(2209801), mat2ppt.util.Emu(307777));
sp.text_frame().text = 'Get paid to go to school';


%% ===== Slide 6 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(1084264), mat2ppt.util.Emu(8991600), mat2ppt.util.Emu(5338762));
sp.text_frame().text = 'High School and College JobsPicked produce at local farmsYard work for elderlyCampus workstudy: mailroom and computer labBuilt homes for local construction companyBachelor’s degree @ University of PortlandInternship @ Boeing: Maintained manufacturing equipment for Boeing 747 and 737 Master’s degree @ University of CincinnatiTaught classes and worked on suspension modeling of pickup trucksYork InternationalDesigned and produced air handlers to keep things comfortable and quiet in schools, concert halls, and hospitalsMoog-CSA Engineering Projects: Space Launch System (rocket to go to the moon), ESPA (mount lots of small satellites on big rockets), NICER (looking at the sun’s energy from the International Space Station to feed environmental models for global warming calculations), XSS-11, DSX, Giant Magellan Telescope (six 27’ mirrors to make an 80 ft visible spectrum telescope, resolution 10 times better than Hubble), Recon Optical telescopes for pods on F-15 jets.Sandia National Laboratories Evaluate the engineering work of others to ensure that it meets technical rigor in order to keep our country safe';

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(0), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(1084263));
sp.text_frame().text = 'Career Overview';

% TextBox 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(6935417), mat2ppt.util.Emu(1463073), mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(1015663));
sp.text_frame().text = 'Step 1:Learn to work hard';

% TextBox 16
sp = sh.add_shape('rect', mat2ppt.util.Emu(6970823), mat2ppt.util.Emu(2577247), mat2ppt.util.Emu(2013857), mat2ppt.util.Emu(1015663));
sp.text_frame().text = 'Step 2:Learn a Valuable Skill';

% TextBox 18
sp = sh.add_shape('rect', mat2ppt.util.Emu(6553097), mat2ppt.util.Emu(3642111), mat2ppt.util.Emu(2608716), mat2ppt.util.Emu(1200329));
sp.text_frame().text = 'Step 3:Get Paid to Work Hard at Job Using Your  Valuable Skill';

% picture Picture 11
img = fullfile(assets, 'image31.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(9383038), mat2ppt.util.Emu(5230371), mat2ppt.util.Emu(2628900), mat2ppt.util.Emu(1743075));
end


%% ===== Slide 7 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(9510), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(1074753));
sp.text_frame().text = 'Step 1: Learn to Work Hard';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(79610), mat2ppt.util.Emu(1205418), mat2ppt.util.Emu(8566150), mat2ppt.util.Emu(5183187));
sp.text_frame().text = 'High School and College JobsPicked produce at local farmsYard work for elderlyCampus workstudy: mailroom and computer labBuilt homes for local construction company';

% TODO: group shape Group 10

% TODO: group shape Group 15

% TODO: group shape Group 19

% TODO: group shape Group 3


%% ===== Slide 8 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% TODO: group shape Group 18

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(0), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(1084263));
sp.text_frame().text = 'Step 2: Learn a Valuable Skill';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(169095), mat2ppt.util.Emu(1133172), mat2ppt.util.Emu(8625655), mat2ppt.util.Emu(5289853));
sp.text_frame().text = 'Bachelor’s degree @ University of PortlandInternship @ Boeing: Maintained manufacturing equipment for Boeing 747 and 737 Master’s degree @ University of CincinnatiTaught classes and worked on suspension modeling of pickup trucks';

% TODO: group shape Group 3


%% ===== Slide 9 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% TODO: group shape Group 5

% TODO: group shape Group 8

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(17969), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(1066294));
sp.text_frame().text = 'Step 3: Work Hard at Job Using Valuable Skill';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(-8906), mat2ppt.util.Emu(1147775), mat2ppt.util.Emu(8704696), mat2ppt.util.Emu(814388));
sp.text_frame().text = 'York InternationalDesigned and produced air handlers to keep things comfortable and quiet in schools, concert halls, and hospitals';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(-235), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(8642350), mat2ppt.util.Emu(1395411));
sp.text_frame().text = 'Moog-CSA Engineering Projects: Space Launch System (rocket to go to the moon), ESPA (mount lots of small satellites on big rockets), NICER (looking at the sun’s energy from the International Space Station to feed environmental models for global warming calculations), XSS-11, DSX, Giant Magellan Telescope (six 27’ mirrors to make an 80 ft visible spectrum telescope, resolution 10 times better than Hubble), Recon Optical telescopes for pods on F-15 jets.';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(1143000), mat2ppt.util.Emu(8642350), mat2ppt.util.Emu(814388));
sp.text_frame().text = 'Sandia National Laboratories Evaluate the engineering work of others to ensure that it meets technical rigor in order to keep our country safe';

% TODO: group shape Group 17


%% ===== Slide 10 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(990600), mat2ppt.util.Emu(0), mat2ppt.util.Emu(7161213), mat2ppt.util.Emu(1084263));
sp.text_frame().text = 'Succeed in Any Career';

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(76200), mat2ppt.util.Emu(1219200), mat2ppt.util.Emu(8991600), mat2ppt.util.Emu(5183187));
sp.text_frame().text = 'What are the most important ingredients to a successful career?Hard workLearn as much as possible about the fieldFormal educationInternshipsApprenticeshipsVery difficult and very dangerous jobs pay better than easy jobsExamples: doctors and underwater weldersJobs that can replicate at scale pay better than jobs that require individual attentionSoftware development vs. early childhood educationPay isn’t the only factor in deciding on a careerThe pay is terrible for artists, priests and stay-at-home moms, but the spiritual and emotional rewards are great – money isn’t the most important thing in life';


%% ===== Slide 11 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(685800), mat2ppt.util.Emu(3426031), mat2ppt.util.Emu(7772400), mat2ppt.util.Emu(1362075));
sp.text_frame().text = 'Questions?';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide2 sp missing geom: Content Placeholder 2
% GAP: slide3 sp missing geom: Content Placeholder 2
% GAP: slide4 group shape Group 18 not expanded
% GAP: slide4 sp missing geom: Content Placeholder 2
% GAP: slide4 group shape Group 11 not expanded
% GAP: slide4 group shape Group 25 not expanded
% GAP: slide4 group shape Group 35 not expanded
% GAP: slide4 group shape Group 43 not expanded
% GAP: slide7 group shape Group 10 not expanded
% GAP: slide7 group shape Group 15 not expanded
% GAP: slide7 group shape Group 19 not expanded
% GAP: slide7 group shape Group 3 not expanded
% GAP: slide8 group shape Group 18 not expanded
% GAP: slide8 group shape Group 3 not expanded
% GAP: slide9 group shape Group 5 not expanded
% GAP: slide9 group shape Group 8 not expanded
% GAP: slide9 group shape Group 17 not expanded
