%% demo.m — Recreate 18_Dropbox_Poverty_Awareness__Display Board Titles Headers via Mat2Ppt public API
% Source: 18_Dropbox_Poverty_Awareness__Display Board Titles Headers.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(9144000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(1600201), mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(533400));

% Rectangle 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(2057400), mat2ppt.util.Emu(8762999), mat2ppt.util.Emu(1169551));
sp.text_frame().text = 'A Few Children';

% Rectangle 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(3429000), mat2ppt.util.Emu(8762999), mat2ppt.util.Emu(1169551));
sp.text_frame().text = 'Sponsored';

% Rectangle 7
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(4724400), mat2ppt.util.Emu(8762999), mat2ppt.util.Emu(1169551));
sp.text_frame().text = 'By Parish Members';


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(1600201), mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(533400));

% Rectangle 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(2057400), mat2ppt.util.Emu(8762999), mat2ppt.util.Emu(938719));
sp.text_frame().text = 'A Few Children';

% Rectangle 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(3429000), mat2ppt.util.Emu(8762999), mat2ppt.util.Emu(938719));
sp.text_frame().text = 'Sponsored';

% Rectangle 7
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(4724400), mat2ppt.util.Emu(8762999), mat2ppt.util.Emu(938719));
sp.text_frame().text = 'By Parish Members';


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(1600201), mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(533400));

% Rectangle 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(228600), mat2ppt.util.Emu(2438400), mat2ppt.util.Emu(8762999), mat2ppt.util.Emu(938719));
sp.text_frame().text = 'A Brief Look at Poverty';

% Rectangle 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(8762999), mat2ppt.util.Emu(1169551));
sp.text_frame().text = 'at Poverty';

% Rectangle 9
sp = sh.add_shape('rect', mat2ppt.util.Emu(152400), mat2ppt.util.Emu(5105400), mat2ppt.util.Emu(8762999), mat2ppt.util.Emu(1169551));
sp.text_frame().text = 'A Brief Look';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide1 sp missing geom: Title 1
% GAP: slide2 sp missing geom: Title 1
% GAP: slide3 sp missing geom: Title 1
