%% demo.m — Recreate 10_Dropbox_aDietrich__Oregon State Report Pictures via Mat2Ppt public API
% Source: 10_Dropbox_aDietrich__Oregon State Report Pictures.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 3
img = fullfile(assets, 'image1.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(285394), mat2ppt.util.Emu(0), mat2ppt.util.Emu(7771105), mat2ppt.util.Emu(6858000));
end


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 5
img = fullfile(assets, 'image2.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3113165), mat2ppt.util.Emu(-981289), mat2ppt.util.Emu(6858000), mat2ppt.util.Emu(8820578));
end


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 5
img = fullfile(assets, 'image3.gif');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(3273742), mat2ppt.util.Emu(0), mat2ppt.util.Emu(6784653), mat2ppt.util.Emu(6858000));
end


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 3
img = fullfile(assets, 'image4.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(178970), mat2ppt.util.Emu(3364), mat2ppt.util.Emu(9139514), mat2ppt.util.Emu(6854636));
end


%% ===== Slide 5 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 3
img = fullfile(assets, 'image5.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1251284), mat2ppt.util.Emu(0), mat2ppt.util.Emu(9644250), mat2ppt.util.Emu(6890280));
end


%% ===== Slide 6 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Graphic 3
img = fullfile(assets, 'image6.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(381000), mat2ppt.util.Emu(0), mat2ppt.util.Emu(11430000), mat2ppt.util.Emu(6858000));
end


%% ===== Slide 7 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 4
img = fullfile(assets, 'image8.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(0), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(6858000));
end


%% ===== Slide 8 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 2
img = fullfile(assets, 'image9.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(864067), mat2ppt.util.Emu(707), mat2ppt.util.Emu(10100345), mat2ppt.util.Emu(6857294));
end


%% ===== Slide 9 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 4
img = fullfile(assets, 'image10.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(-15874), mat2ppt.util.Emu(0), mat2ppt.util.Emu(12223748), mat2ppt.util.Emu(6858000));
end


%% ===== Slide 10 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 3
img = fullfile(assets, 'image11.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(2219020), mat2ppt.util.Emu(-985838), mat2ppt.util.Emu(6858001), mat2ppt.util.Emu(8829676));
end


%% ===== Slide 11 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 6
img = fullfile(assets, 'image12.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1038534), mat2ppt.util.Emu(24670), mat2ppt.util.Emu(6728468), mat2ppt.util.Emu(6728468));
end


%% ===== Slide 12 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 4
img = fullfile(assets, 'image13.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(2550702), mat2ppt.util.Emu(-914866), mat2ppt.util.Emu(6849630), mat2ppt.util.Emu(8696102));
end


%% ===== Slide 13 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 7
img = fullfile(assets, 'image14.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1811096), mat2ppt.util.Emu(-1047895), mat2ppt.util.Emu(6858000), mat2ppt.util.Emu(8953789));
end


%% ===== Slide 14 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 3
img = fullfile(assets, 'image15.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(153054), mat2ppt.util.Emu(0), mat2ppt.util.Emu(9586452), mat2ppt.util.Emu(6857999));
end

% TextBox 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(1297339), mat2ppt.util.Emu(1506022), mat2ppt.util.Emu(1669409), mat2ppt.util.Emu(369332));
sp.text_frame().text = 'Mild and moist';

% TextBox 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(5643152), mat2ppt.util.Emu(3317431), mat2ppt.util.Emu(2150220), mat2ppt.util.Emu(523220));
sp.text_frame().text = 'High Desert';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide1 sp missing geom: Title 1
% GAP: slide2 sp missing geom: Title 1
% GAP: slide3 sp missing geom: Title 1
% GAP: slide4 sp missing geom: Title 1
% GAP: slide5 sp missing geom: Title 1
% GAP: slide6 sp missing geom: Title 1
% GAP: slide7 sp missing geom: Title 1
% GAP: slide8 sp missing geom: Title 1
% GAP: slide9 sp missing geom: Title 1
% GAP: slide10 sp missing geom: Title 1
% GAP: slide11 sp missing geom: Title 1
% GAP: slide12 sp missing geom: Title 1
% GAP: slide13 sp missing geom: Title 1
% GAP: slide14 sp missing geom: Title 1
