%% demo.m — Recreate 05_Box_Website__Thermometer_Graphic via Mat2Ppt public API
% Source: 05_Box_Website__Thermometer_Graphic.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(51206400);
prs.slide_height = mat2ppt.util.Emu(51206400);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Oval 20
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 21
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 22
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 19
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 26
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 27
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 28
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 25
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 32
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 33
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 34
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 31
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 38
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 39
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 40
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 37
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 44
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 45
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 46
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 43
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 50
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 51
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 52
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 49
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 56
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 57
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 58
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 55
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 62
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 63
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 64
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 61
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% TextBox 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(45589031), mat2ppt.util.Emu(13762844), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '5%';

% TextBox 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(18019039), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '10%';

% TextBox 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(22275234), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '15%';

% TextBox 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(45458062), mat2ppt.util.Emu(26531795), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '20%';

% TextBox 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(45589031), mat2ppt.util.Emu(30787990), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '25%';

% TextBox 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(45667613), mat2ppt.util.Emu(35044185), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '30%';

% TextBox 65
sp = sh.add_shape('rect', mat2ppt.util.Emu(45667613), mat2ppt.util.Emu(39300380), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '35%';

% TextBox 66
sp = sh.add_shape('rect', mat2ppt.util.Emu(45405675), mat2ppt.util.Emu(43556941), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '40%';

% TextBox 67
sp = sh.add_shape('rect', mat2ppt.util.Emu(45536644), mat2ppt.util.Emu(47813136), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '45%';

% TextBox 82
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(9506649), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '2%';

% Oval 14
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 15
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 16
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 13
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Rectangle 83
sp = sh.add_shape('rect', mat2ppt.util.Emu(3398042), mat2ppt.util.Emu(5574350), mat2ppt.util.Emu(404814), mat2ppt.util.Emu(1800224));

% Oval 90
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 91
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 92
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 89
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Rectangle 87
sp = sh.add_shape('rect', mat2ppt.util.Emu(3398042), mat2ppt.util.Emu(5574350), mat2ppt.util.Emu(404814), mat2ppt.util.Emu(1800224));

% TextBox 93
sp = sh.add_shape('rect', mat2ppt.util.Emu(45798582), mat2ppt.util.Emu(1010925), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '0%';

% Oval 99
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 100
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 101
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 98
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Rectangle 96
sp = sh.add_shape('rect', mat2ppt.util.Emu(3398042), mat2ppt.util.Emu(5574350), mat2ppt.util.Emu(404814), mat2ppt.util.Emu(1800224));

% TextBox 102
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(5267120), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '1%';

% Oval 108
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 109
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 110
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 107
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Rectangle 105
sp = sh.add_shape('rect', mat2ppt.util.Emu(3398042), mat2ppt.util.Emu(5574350), mat2ppt.util.Emu(404814), mat2ppt.util.Emu(1800224));


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Oval 14
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 15
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 16
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 13
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 20
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 21
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 22
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 19
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 26
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 27
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 28
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 25
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 32
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 33
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 34
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 31
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 38
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 39
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 40
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 37
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 44
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 45
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 46
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 43
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 50
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 51
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 52
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 49
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 56
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 57
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 58
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 55
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 62
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 63
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 64
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 61
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% TextBox 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(45589031), mat2ppt.util.Emu(1205947), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '50%';

% TextBox 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(5462142), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '55%';

% TextBox 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(9718337), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '60%';

% TextBox 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(45458062), mat2ppt.util.Emu(13974898), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '65%';

% TextBox 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(45589031), mat2ppt.util.Emu(18231093), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '70%';

% TextBox 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(45667613), mat2ppt.util.Emu(22487288), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '75%';

% TextBox 65
sp = sh.add_shape('rect', mat2ppt.util.Emu(45667613), mat2ppt.util.Emu(26743483), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '80%';

% TextBox 66
sp = sh.add_shape('rect', mat2ppt.util.Emu(45405675), mat2ppt.util.Emu(31000044), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '85%';

% TextBox 67
sp = sh.add_shape('rect', mat2ppt.util.Emu(45536644), mat2ppt.util.Emu(35256239), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '90%';

% Oval 71
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 72
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 73
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% Rectangle 70
sp = sh.add_shape('rect', mat2ppt.util.Emu(43760231), mat2ppt.util.Emu(5165885), mat2ppt.util.Emu(238125), mat2ppt.util.Emu(1800224));

% Oval 77
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 78
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 79
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% TextBox 80
sp = sh.add_shape('rect', mat2ppt.util.Emu(45327093), mat2ppt.util.Emu(39512434), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '95%';

% TextBox 81
sp = sh.add_shape('rect', mat2ppt.util.Emu(45458062), mat2ppt.util.Emu(43768629), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '98%';

% Oval 85
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(42976800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(1828800));

% Rectangle 86
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(3396342), mat2ppt.util.Emu(42062400), mat2ppt.util.Emu(1828800));

% Oval 87
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(0), mat2ppt.util.Emu(2481942), mat2ppt.util.Emu(3657600), mat2ppt.util.Emu(3657600));

% TextBox 88
sp = sh.add_shape('rect', mat2ppt.util.Emu(45327093), mat2ppt.util.Emu(48024824), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '100%';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);
