%% demo.m — Recreate 05_Box_Website__Thermometer_Graphic via Mat2Ppt public API
% Source: 05_Box_Website__Thermometer_Graphic.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(51206400);
prs.slide_height = mat2ppt.util.Emu(51206400);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% TODO: group shape Group 17

% TODO: group shape Group 23

% TODO: group shape Group 29

% TODO: group shape Group 35

% TODO: group shape Group 41

% TODO: group shape Group 47

% TODO: group shape Group 53

% TODO: group shape Group 59

% TextBox 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(45589031), mat2ppt.util.Emu(13762844), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '5%';

% TextBox 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(18019039), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '10%';

% TextBox 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(22275234), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '15%';

% TextBox 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(45458062), mat2ppt.util.Emu(26531795), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '20%';

% TextBox 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(45589031), mat2ppt.util.Emu(30787990), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '25%';

% TextBox 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(45667613), mat2ppt.util.Emu(35044185), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '30%';

% TextBox 65
sp = sh.add_shape('rect', mat2ppt.util.Emu(45667613), mat2ppt.util.Emu(39300380), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '35%';

% TextBox 66
sp = sh.add_shape('rect', mat2ppt.util.Emu(45405675), mat2ppt.util.Emu(43556941), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '40%';

% TextBox 67
sp = sh.add_shape('rect', mat2ppt.util.Emu(45536644), mat2ppt.util.Emu(47813136), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '45%';

% TextBox 82
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(9506649), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '2%';

% TODO: group shape Group 84

% TODO: group shape Group 85

% TextBox 93
sp = sh.add_shape('rect', mat2ppt.util.Emu(45798582), mat2ppt.util.Emu(1010925), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '0%';

% TODO: group shape Group 94

% TextBox 102
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(5267120), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '1%';

% TODO: group shape Group 103


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% TODO: group shape Group 11

% TODO: group shape Group 17

% TODO: group shape Group 23

% TODO: group shape Group 29

% TODO: group shape Group 35

% TODO: group shape Group 41

% TODO: group shape Group 47

% TODO: group shape Group 53

% TODO: group shape Group 59

% TextBox 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(45589031), mat2ppt.util.Emu(1205947), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '50%';

% TextBox 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(5462142), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '55%';

% TextBox 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(45720000), mat2ppt.util.Emu(9718337), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '60%';

% TextBox 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(45458062), mat2ppt.util.Emu(13974898), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '65%';

% TextBox 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(45589031), mat2ppt.util.Emu(18231093), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '70%';

% TextBox 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(45667613), mat2ppt.util.Emu(22487288), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '75%';

% TextBox 65
sp = sh.add_shape('rect', mat2ppt.util.Emu(45667613), mat2ppt.util.Emu(26743483), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '80%';

% TextBox 66
sp = sh.add_shape('rect', mat2ppt.util.Emu(45405675), mat2ppt.util.Emu(31000044), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '85%';

% TextBox 67
sp = sh.add_shape('rect', mat2ppt.util.Emu(45536644), mat2ppt.util.Emu(35256239), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '90%';

% TODO: group shape Group 68

% TODO: group shape Group 75

% TextBox 80
sp = sh.add_shape('rect', mat2ppt.util.Emu(45327093), mat2ppt.util.Emu(39512434), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '95%';

% TextBox 81
sp = sh.add_shape('rect', mat2ppt.util.Emu(45458062), mat2ppt.util.Emu(43768629), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '98%';

% TODO: group shape Group 83

% TextBox 88
sp = sh.add_shape('rect', mat2ppt.util.Emu(45327093), mat2ppt.util.Emu(48024824), mat2ppt.util.Emu(4236244), mat2ppt.util.Emu(2215991));
sp.text_frame().text = '100%';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide1 group shape Group 17 not expanded
% GAP: slide1 group shape Group 23 not expanded
% GAP: slide1 group shape Group 29 not expanded
% GAP: slide1 group shape Group 35 not expanded
% GAP: slide1 group shape Group 41 not expanded
% GAP: slide1 group shape Group 47 not expanded
% GAP: slide1 group shape Group 53 not expanded
% GAP: slide1 group shape Group 59 not expanded
% GAP: slide1 group shape Group 84 not expanded
% GAP: slide1 group shape Group 85 not expanded
% GAP: slide1 group shape Group 94 not expanded
% GAP: slide1 group shape Group 103 not expanded
% GAP: slide2 group shape Group 11 not expanded
% GAP: slide2 group shape Group 17 not expanded
% GAP: slide2 group shape Group 23 not expanded
% GAP: slide2 group shape Group 29 not expanded
% GAP: slide2 group shape Group 35 not expanded
% GAP: slide2 group shape Group 41 not expanded
% GAP: slide2 group shape Group 47 not expanded
% GAP: slide2 group shape Group 53 not expanded
% GAP: slide2 group shape Group 59 not expanded
% GAP: slide2 group shape Group 68 not expanded
% GAP: slide2 group shape Group 75 not expanded
% GAP: slide2 group shape Group 83 not expanded
