%% demo.m — Recreate 12_Dropbox_aReuben__Fall 2018_Math Schedule via Mat2Ppt public API
% Source: 12_Dropbox_aReuben__Fall 2018_Math Schedule.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(838200), mat2ppt.util.Emu(365126), mat2ppt.util.Emu(10515600), mat2ppt.util.Emu(581932));

% picture Picture 3
img = fullfile(assets, 'image1.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(411995), mat2ppt.util.Emu(277586), mat2ppt.util.Emu(11106751), mat2ppt.util.Emu(6858000));
end


prs.save(outPath);
fprintf("Wrote %s\n", outPath);
