%% demo.m — Recreate 06_Box_Zeffy__Donation_Form_Question_Discrepencies_by_Link_Type_ via Mat2Ppt public API
% Source: 06_Box_Zeffy__Donation_Form_Question_Discrepencies_by_Link_Type_.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% TODO: group shape Group 10


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% TODO: group shape Group 12

% TODO: group shape Group 14


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide1 group shape Group 10 not expanded
% GAP: slide2 group shape Group 12 not expanded
% GAP: slide2 group shape Group 14 not expanded
