%% demo.m — Recreate 23_Dropbox_Soccer__SoccerAward via Mat2Ppt public API
% Source: 23_Dropbox_Soccer__SoccerAward.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(10058400);
prs.slide_height = mat2ppt.util.Emu(7772400);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(2362200), mat2ppt.util.Emu(6492875), mat2ppt.util.Emu(685800));

% Rectangle 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(2286000), mat2ppt.util.Emu(3651250), mat2ppt.util.Emu(5670550), mat2ppt.util.Emu(1225550));


prs.save(outPath);
fprintf("Wrote %s\n", outPath);
