%% demo.m — Recreate 15_Dropbox_Family__picturesForPuttingAwayClothes via Mat2Ppt public API
% Source: 15_Dropbox_Family__picturesForPuttingAwayClothes.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 6
img = fullfile(assets, 'image1.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4081124), mat2ppt.util.Emu(321182), mat2ppt.util.Emu(2829709), mat2ppt.util.Emu(2740349));
end

% picture Picture 4
img = fullfile(assets, 'image2.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(503280), mat2ppt.util.Emu(3796470), mat2ppt.util.Emu(3350938), mat2ppt.util.Emu(2815094));
end

% picture Picture 9
img = fullfile(assets, 'image3.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(7483812), mat2ppt.util.Emu(3393058), mat2ppt.util.Emu(2005279), mat2ppt.util.Emu(3218506));
end

% picture Picture 11
img = fullfile(assets, 'image4.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(9992075), mat2ppt.util.Emu(3373009), mat2ppt.util.Emu(1906699), mat2ppt.util.Emu(3238555));
end

% picture Picture 12
img = fullfile(assets, 'image1.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(678436), mat2ppt.util.Emu(321182), mat2ppt.util.Emu(2829709), mat2ppt.util.Emu(2740349));
end

% picture Picture 16
img = fullfile(assets, 'image5.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(7483812), mat2ppt.util.Emu(227875), mat2ppt.util.Emu(3391522), mat2ppt.util.Emu(2740350));
end

% picture Picture 19
img = fullfile(assets, 'image6.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(4161281), mat2ppt.util.Emu(4050563), mat2ppt.util.Emu(2749552), mat2ppt.util.Emu(2630155));
end


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 3
img = fullfile(assets, 'image7.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(414917), mat2ppt.util.Emu(329293), mat2ppt.util.Emu(2957958), mat2ppt.util.Emu(2957958));
end

% picture Picture 2
img = fullfile(assets, 'image8.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(7472206), mat2ppt.util.Emu(4476589), mat2ppt.util.Emu(2216995), mat2ppt.util.Emu(2545826));
end

% picture Picture 11
img = fullfile(assets, 'image9.gif');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(5036619), mat2ppt.util.Emu(452927), mat2ppt.util.Emu(3337175), mat2ppt.util.Emu(4000873));
end

% Rectangle: Rounded Corners 13
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(5589036), mat2ppt.util.Emu(2379306), mat2ppt.util.Emu(2323323), mat2ppt.util.Emu(2074494));

% picture Picture 9
img = fullfile(assets, 'image9.gif');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(8725256), mat2ppt.util.Emu(452928), mat2ppt.util.Emu(3337175), mat2ppt.util.Emu(4000873));
end

% Rectangle: Rounded Corners 14
sp = sh.add_shape('roundRect', mat2ppt.util.Emu(8819128), mat2ppt.util.Emu(452927), mat2ppt.util.Emu(3142718), mat2ppt.util.Emu(1926380));

% picture Picture 20
img = fullfile(assets, 'image10.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(588117), mat2ppt.util.Emu(3221937), mat2ppt.util.Emu(3337175), mat2ppt.util.Emu(3155449));
end


prs.save(outPath);
fprintf("Wrote %s\n", outPath);
