%% demo.m — Recreate 01_Box_Conferences__SLG_Intro4Scientists via Mat2Ppt public API
% Source: reference_original.pptx
% Generated by harness/recreate_pptx_demo.py (layout-aware).
%
% Visual checklist: layout/template, fonts, textboxes, fills,
% connectors (path/adj/arrows), inches. Review + hand-tune.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Inches(10);
prs.slide_height = mat2ppt.util.Inches(7.5);
layouts = prs.slide_layouts();

lay_Comparison = layouts.get_by_name('Comparison');
lay_Title_and_Content = layouts.get_by_name('Title and Content');

%% ===== Slide 1 · layout Title and Content (source: Title and Content) =====
s = prs.slides().add_slide(lay_Title_and_Content);
sh = s.shapes();

% --- layout placeholders (1-based among cloned ph shapes) ---
% PH 1: Title 1 type=title idx=
sp = sh.item(1);  % placeholder
tf = sp.text_frame();
tf.text = 'What Makes a Great Scientist?';

% PH 2: Content Placeholder 4 type=body idx=1
sp = sh.item(2);  % placeholder
tf = sp.text_frame();
tf.clear();
ps0 = tf.paragraphs();
ps0{1}.text = 'Knowing science and math facts';
ps0{1}.level = 0;
p = tf.add_paragraph();
p.text = 'Being able to solve known scientific problems';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Being able to acquire new data and assemble new theories to expand knowledge and answer specific questions about the universe';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Is there something that many of our greatest scientists have in common?';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Pictures of Newton, Einstein, and Feynman';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Overlays of the Bible, Violin, and Congo drums';
p.level = 0;

% --- free shapes / pictures / connectors ---
% Footer Placeholder 2
sp = sh.add_textbox(mat2ppt.util.Inches(3.4167), mat2ppt.util.Inches(6.9514), mat2ppt.util.Inches(3.1667), mat2ppt.util.Inches(0.3993));
tf = sp.text_frame();
tf.text = 'Lesson 18 Biology 2';

% Slide Number Placeholder 3
sp = sh.add_textbox(mat2ppt.util.Inches(7.1667), mat2ppt.util.Inches(6.9514), mat2ppt.util.Inches(2.3333), mat2ppt.util.Inches(0.3993));
tf = sp.text_frame();
tf.text = '1';


%% ===== Slide 2 · layout Comparison (source: Comparison) =====
% Hand-tuned: smaller body fonts, subtitle under title, footer clear of columns.
s = prs.slides().add_slide(lay_Comparison);
sh = s.shapes();

% PH 1: Title
sp = sh.item(1);
tf = sp.text_frame();
tf.text = 'Science: Left-Brain or Right-Brain Thinking?';
set_tf_font_(tf, 28);

% Subtitle free text (under title; original free shape — not a layout ph)
sp = sh.add_textbox(mat2ppt.util.Inches(0.5), mat2ppt.util.Inches(1.35), ...
    mat2ppt.util.Inches(9.0), mat2ppt.util.Inches(0.35));
tf = sp.text_frame();
tf.text = 'Our perceptions of the world come from paying a certain kind of attention to it';
set_tf_font_(tf, 12);

% PH 2: Left column header
sp = sh.item(2);
tf = sp.text_frame();
tf.text = 'Left-Brain Characteristics';
set_tf_font_(tf, 14);

% PH 3: Left column body — dense nested list (use 9–10 pt so it fits)
sp = sh.item(3);
tf = sp.text_frame();
tf.clear();
ps0 = tf.paragraphs();
ps0{1}.text = 'Helps us manipulate the world';
ps0{1}.level = 0;
p = tf.add_paragraph();
p.text = 'Clinical attention';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Left hemisphere sees isolated details that are';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Familiar';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Known';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Fixed';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Graspable';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Abstracted';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Taken out of context';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Categorizable';
p.level = 1;
p = tf.add_paragraph();
p.text = 'General in nature';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Generally inanimate, because the process has completely isolated them from everything else and deanimated them';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Grasping a tiny detail';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Narrowly, focused, targeted attention to something it already knows about';
p.level = 0;
set_tf_font_(tf, 9);

% PH 4: Right column header
sp = sh.item(4);
tf = sp.text_frame();
tf.text = 'Right-Brain Characteristics';
set_tf_font_(tf, 14);

% PH 5: Right column body
sp = sh.item(5);
tf = sp.text_frame();
tf.clear();
ps0 = tf.paragraphs();
ps0{1}.text = 'Helps us understand the world';
ps0{1}.level = 0;
p = tf.add_paragraph();
p.text = 'Rapt attention';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Right hemisphere’s vision sees things that are';
p.level = 0;
p = tf.add_paragraph();
p.text = 'only partly known';
p.level = 1;
p = tf.add_paragraph();
p.text = 'only partly certain of what we are looking at';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Fresh';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Interconnected, and situated where they are in context';
p.level = 1;
p = tf.add_paragraph();
p.text = 'When we take them out of context, they change their nature';
p.level = 2;
p = tf.add_paragraph();
p.text = 'Flowing and changing, not fixed and graspable in a simple way';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Unique rather than exemplars of a common theme';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Embodied rather than abstracted and disembodied';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Animate, rather than inanimate';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Has the ability to look out for something we might be missing -- more skeptical';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Assembles facts for application in an embodied world.';
p.level = 0;
set_tf_font_(tf, 9);

% Quote at bottom
sp = sh.add_textbox(mat2ppt.util.Inches(0.2), mat2ppt.util.Inches(6.35), ...
    mat2ppt.util.Inches(9.6), mat2ppt.util.Inches(0.55));
tf = sp.text_frame();
tf.text = ['Reason is this ability to bring together the faculties of logic with ', ...
    'the faculties of an intuitive, implicit, embodied understanding of ', ...
    'what it means to be alive” –Iain McGilchrist'];
set_tf_font_(tf, 10);

% Footer + slide number (latent ph → free textboxes)
sp = sh.add_textbox(mat2ppt.util.Inches(3.4), mat2ppt.util.Inches(7.05), ...
    mat2ppt.util.Inches(3.2), mat2ppt.util.Inches(0.35));
tf = sp.text_frame();
tf.text = 'Lesson 18 Biology 2';
set_tf_font_(tf, 10);
sp = sh.add_textbox(mat2ppt.util.Inches(9.0), mat2ppt.util.Inches(7.05), ...
    mat2ppt.util.Inches(0.8), mat2ppt.util.Inches(0.35));
tf = sp.text_frame();
tf.text = '2';
set_tf_font_(tf, 10);


%% ===== Slide 3 · layout Title and Content (source: Title and Content) =====
s = prs.slides().add_slide(lay_Title_and_Content);
sh = s.shapes();

% --- layout placeholders (1-based among cloned ph shapes) ---
% PH 1: Title 8 type=title idx=
sp = sh.item(1);  % placeholder
tf = sp.text_frame();
tf.text = 'Developing the Right-Brain';

% PH 2: Content Placeholder 9 type=body idx=1
sp = sh.item(2);  % placeholder
tf = sp.text_frame();
tf.clear();
ps0 = tf.paragraphs();
ps0{1}.text = 'If we want to educate students to be world-class scientists, we need to develop and not dismiss right-brain thinking';
ps0{1}.level = 0;
p = tf.add_paragraph();
p.text = 'Both left and right-brain thinking are critical for breakthrough science';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Teach an understanding of and appreciation for Music, Art, and the Sacred';
p.level = 0;
p = tf.add_paragraph();
p.text = 'For example: band, drawing, family, and the pledge of allegiance/reveille';
p.level = 1;
p = tf.add_paragraph();
p.text = 'The Saint Luke Guild was founded to bring high quality, physical reproductions of the greatest works of art to students of average means';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Enabled by two technological developments from the last 20 years';
p.level = 1;
p = tf.add_paragraph();
p.text = 'The explosion of high-resolution, digital imagery of the greatest works of art, previously reserved to museum visitors';
p.level = 2;
p = tf.add_paragraph();
p.text = 'The dramatic improvements in low-cost, museum quality photographic printing methods';
p.level = 2;

% --- free shapes / pictures / connectors ---
% Footer Placeholder 6
sp = sh.add_textbox(mat2ppt.util.Inches(3.4167), mat2ppt.util.Inches(6.9514), mat2ppt.util.Inches(3.1667), mat2ppt.util.Inches(0.3993));
tf = sp.text_frame();
tf.text = 'Lesson 18 Biology 2';

% Slide Number Placeholder 7
sp = sh.add_textbox(mat2ppt.util.Inches(7.1667), mat2ppt.util.Inches(6.9514), mat2ppt.util.Inches(2.3333), mat2ppt.util.Inches(0.3993));
tf = sp.text_frame();
tf.text = '3';


%% ===== Slide 4 · layout Title and Content (source: Title and Content) =====
s = prs.slides().add_slide(lay_Title_and_Content);
sh = s.shapes();

% --- layout placeholders (1-based among cloned ph shapes) ---
% PH 1: Title 1 type=title idx=
sp = sh.item(1);  % placeholder
tf = sp.text_frame();
tf.text = 'Example Project';

% PH 2: Content Placeholder 2 type=body idx=1
sp = sh.item(2);  % placeholder
tf = sp.text_frame();
tf.clear();
ps0 = tf.paragraphs();
ps0{1}.text = 'Bring around 50 paintings showing both a timeline of art and world history to Holy Child Catholic School';
ps0{1}.level = 0;
p = tf.add_paragraph();
p.text = '$30k in artwork installed in the last 1.5 years';
p.level = 1;
p = tf.add_paragraph();
p.text = '$30k in funding promised by donors to complete the hallway';
p.level = 1;
p = tf.add_paragraph();
p.text = 'Over 20 years projects of a similar scale could be done in every school throughout the country for ~.05% of their budget';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Compare with Zuckerberg’s $300,000,000 donation to one school district – Zero improvement in student achievement';
p.level = 1;

% --- free shapes / pictures / connectors ---
% Footer Placeholder 3
sp = sh.add_textbox(mat2ppt.util.Inches(3.4167), mat2ppt.util.Inches(6.9514), mat2ppt.util.Inches(3.1667), mat2ppt.util.Inches(0.3993));
tf = sp.text_frame();
tf.text = 'Lesson 18 Biology 2';

% Slide Number Placeholder 4
sp = sh.add_textbox(mat2ppt.util.Inches(7.1667), mat2ppt.util.Inches(6.9514), mat2ppt.util.Inches(2.3333), mat2ppt.util.Inches(0.3993));
tf = sp.text_frame();
tf.text = '4';


%% ===== Slide 5 · layout Title and Content (source: Title and Content) =====
s = prs.slides().add_slide(lay_Title_and_Content);
sh = s.shapes();

% --- layout placeholders (1-based among cloned ph shapes) ---
% PH 1: Title 1 type=title idx=
sp = sh.item(1);  % placeholder
tf = sp.text_frame();
tf.text = 'Example Paintings';

% PH 2: Content Placeholder 2 type=body idx=1
sp = sh.item(2);  % placeholder
tf = sp.text_frame();
tf.text = 'Science brings us facts about the world';

% --- free shapes / pictures / connectors ---
% picture Picture 5
img = fullfile(assets, 'image1.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Inches(4.1844), mat2ppt.util.Inches(2.2825), mat2ppt.util.Inches(5.8342), mat2ppt.util.Inches(4.4957));
end

% picture Content Placeholder 4
img = fullfile(assets, 'image2.jpg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Inches(-0.0145), mat2ppt.util.Inches(1.9989), mat2ppt.util.Inches(4.1989), mat2ppt.util.Inches(5.2341));
end

% Footer Placeholder 3
sp = sh.add_textbox(mat2ppt.util.Inches(3.4167), mat2ppt.util.Inches(6.9514), mat2ppt.util.Inches(3.1667), mat2ppt.util.Inches(0.3993));
tf = sp.text_frame();
tf.text = 'Lesson 18 Biology 2';

% Slide Number Placeholder 4
sp = sh.add_textbox(mat2ppt.util.Inches(7.1667), mat2ppt.util.Inches(6.9514), mat2ppt.util.Inches(2.3333), mat2ppt.util.Inches(0.3993));
tf = sp.text_frame();
tf.text = '5';


%% ===== Slide 6 · layout Title and Content (source: Title and Content) =====
s = prs.slides().add_slide(lay_Title_and_Content);
sh = s.shapes();

% --- layout placeholders (1-based among cloned ph shapes) ---
% PH 1: Title 1 type=title idx=
sp = sh.item(1);  % placeholder
tf = sp.text_frame();
tf.text = 'Summary';

% PH 2: Content Placeholder 2 type=body idx=1
sp = sh.item(2);  % placeholder
tf = sp.text_frame();
tf.clear();
ps0 = tf.paragraphs();
ps0{1}.text = 'Science brings us disembodied, decontextualized facts about the world';
ps0{1}.level = 0;
p = tf.add_paragraph();
p.text = 'Art and myth are focused on how embodied humans should act in the real world, which is particular and uncertain';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Both left and right-brained thinking is necessary for a world-class scientific enterprise';
p.level = 0;
p = tf.add_paragraph();
p.text = 'The scientist is servant to the humanities major';
p.level = 0;
p = tf.add_paragraph();
p.text = 'They control how our inventions are used';
p.level = 1;
p = tf.add_paragraph();
p.text = 'The Saint Luke Guild helps develop right-brain thinking by bringing high quality reproductions of the greatest works of art in the Western Canon to average students';
p.level = 0;
p = tf.add_paragraph();
p.text = 'Developing an appreciation for rapt attention alongside clinical attention';
p.level = 1;

% --- free shapes / pictures / connectors ---
% Footer Placeholder 3
sp = sh.add_textbox(mat2ppt.util.Inches(3.4167), mat2ppt.util.Inches(6.9514), mat2ppt.util.Inches(3.1667), mat2ppt.util.Inches(0.3993));
tf = sp.text_frame();
tf.text = 'Lesson 18 Biology 2';

% Slide Number Placeholder 4
sp = sh.add_textbox(mat2ppt.util.Inches(7.1667), mat2ppt.util.Inches(6.9514), mat2ppt.util.Inches(2.3333), mat2ppt.util.Inches(0.3993));
tf = sp.text_frame();
tf.text = '6';


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

%% ----- local helpers (hand-tune fonts) -----
function set_tf_font_(tf, ptSize)
    Pt = @mat2ppt.util.Pt;
    ps = tf.paragraphs();
    for pi = 1:numel(ps)
        rs = ps{pi}.runs();
        for ri = 1:numel(rs)
            f = rs{ri}.font();
            f.size = Pt(ptSize);
        end
    end
end
