%% demo.m — Recreate 07_Dropbox_a_Chesterton__ChestertonABQ_EmergencyCommunicationOptions_2022-0 via Mat2Ppt public API
% Source: 07_Dropbox_a_Chesterton__ChestertonABQ_EmergencyCommunicationOptions_2022-0.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(1524000), mat2ppt.util.Emu(1788284), mat2ppt.util.Emu(9144000), mat2ppt.util.Emu(2387600));
sp.text_frame().text = 'Chesterton AcademyEmergency Communication Options';

% TextBox 3
sp = sh.add_shape('rect', mat2ppt.util.Emu(3756572), mat2ppt.util.Emu(4421505), mat2ppt.util.Emu(3944994), mat2ppt.util.Emu(830997));
sp.text_frame().text = 'Douglas CoombsFebruary 8, 2022';


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(493094), mat2ppt.util.Emu(1132764), mat2ppt.util.Emu(11471379), mat2ppt.util.Emu(5056001));
sp.text_frame().text = 'Comprehensive Email and Texting ProgramsJupiterEdPotentially cheapest and easiest to set upFlocknotesMuch more flexible but also more expensive and time consuming to set upStandalone Texting SolutionsExpertTexting.comSeems straightforward with intuitive user interfaceOffers two-way texting with parents, if desiredPer text pricing makes it more attractive for infrequent, emergency useTextEmAll.com';


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Content Placeholder 2
sp = sh.add_shape('rect', mat2ppt.util.Emu(493094), mat2ppt.util.Emu(1132764), mat2ppt.util.Emu(10717449), mat2ppt.util.Emu(5056001));
sp.text_frame().text = 'Parents need to login to JupiterEd and opt-in to emergency texting serviceAnother option would be to use non-emergency text messages for weather announcements, but these can get lost as they are common';


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 5 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


%% ===== Slide 6 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();


prs.save(outPath);
fprintf("Wrote %s\n", outPath);

% --- generation gaps ---
% GAP: slide2 sp missing geom: Title 1
% GAP: slide3 sp missing geom: Title 1
% GAP: slide4 sp missing geom: Title 1
% GAP: slide4 sp missing geom: Content Placeholder 2
% GAP: slide5 sp missing geom: Title 1
% GAP: slide5 sp missing geom: Content Placeholder 2
% GAP: slide6 sp missing geom: Title 1
% GAP: slide6 sp missing geom: Content Placeholder 2
