%% demo.m — Recreate 26_Dropbox_w-Sandia__Vibrationdata_download via Mat2Ppt public API
% Source: 26_Dropbox_w-Sandia__Vibrationdata_download.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(12192000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(0), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(457200));

% Rectangle 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(457200), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(0));

% Rectangle 7
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(4122738), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(457200));

% Rectangle 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(4579938), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(0));

% Rectangle 9
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(7954963), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(457200));

% TextBox 10
sp = sh.add_shape('rect', mat2ppt.util.Emu(1828800), mat2ppt.util.Emu(2496562), mat2ppt.util.Emu(7580859), mat2ppt.util.Emu(2585323));
sp.text_frame().text = 'If you going to use this package, please send an Email to:   tom@irvinemail.orgGo to:https://vibrationdata.wordpress.com/Download & extract the GUI package as shown on the next slide';

% TextBox 11
sp = sh.add_shape('rect', mat2ppt.util.Emu(2437959), mat2ppt.util.Emu(1061383), mat2ppt.util.Emu(5911562), mat2ppt.util.Emu(830997));
sp.text_frame().text = 'Download Vibration GUIby Tom Irvine';


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(0), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(457200));

% Rectangle 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(457200), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(0));

% Rectangle 7
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(4122738), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(457200));

% Rectangle 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(4579938), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(0));

% Rectangle 9
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(7954963), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(457200));

% picture Picture 1
img = fullfile(assets, 'image1.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1397863), mat2ppt.util.Emu(777010), mat2ppt.util.Emu(9396274), mat2ppt.util.Emu(5303980));
end

% Oval 10
sp = sh.add_shape('ellipse', mat2ppt.util.Emu(2058869), mat2ppt.util.Emu(4742379), mat2ppt.util.Emu(3683298), mat2ppt.util.Emu(314736));


%% ===== Slide 3 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Rectangle 5
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(0), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(457200));

% Rectangle 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(8625385), mat2ppt.util.Emu(4851779), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(0));

% Rectangle 7
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(4122738), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(457200));

% Rectangle 8
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(4579938), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(0));

% Rectangle 9
sp = sh.add_shape('rect', mat2ppt.util.Emu(0), mat2ppt.util.Emu(7954963), mat2ppt.util.Emu(12192000), mat2ppt.util.Emu(457200));

% picture Picture 1
img = fullfile(assets, 'image2.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(451456), mat2ppt.util.Emu(429356), mat2ppt.util.Emu(9323809), mat2ppt.util.Emu(5838095));
end

% TextBox 6
sp = sh.add_shape('rect', mat2ppt.util.Emu(10072048), mat2ppt.util.Emu(1296537), mat2ppt.util.Emu(1815152), mat2ppt.util.Emu(923330));
sp.text_frame().text = 'Download the newest version & extract the files';


%% ===== Slide 4 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 3
img = fullfile(assets, 'image3.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(421517), mat2ppt.util.Emu(300250), mat2ppt.util.Emu(10257143), mat2ppt.util.Emu(6133333));
end

% TextBox 4
sp = sh.add_shape('rect', mat2ppt.util.Emu(4203511), mat2ppt.util.Emu(2579427), mat2ppt.util.Emu(5704764), mat2ppt.util.Emu(1200329));
sp.text_frame().text = 'Set the path to the folder where the files have been extracted to.Then type vibrationdata in the Command Window.';


%% ===== Slide 5 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% picture Picture 3
img = fullfile(assets, 'image4.png');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(786476), mat2ppt.util.Emu(614714), mat2ppt.util.Emu(10619048), mat2ppt.util.Emu(5628571));
end


prs.save(outPath);
fprintf("Wrote %s\n", outPath);
