%% demo.m — Recreate 20_Dropbox_Recreation__ExampleItinerary via Mat2Ppt public API
% Source: 20_Dropbox_Recreation__ExampleItinerary.pptx
% Generated by harness/recreate_pptx_demo.py — review and adjust as needed.
%
% Outputs out_mat2ppt.pptx next to this script; assets/ holds images.

here = fileparts(mfilename("fullpath"));
addpath(fullfile(here, "..", "..", ".."));  % Mat2Ppt root
outPath = fullfile(here, "out_mat2ppt.pptx");
assets = fullfile(here, "assets");

prs = mat2ppt.Presentation();
prs.slide_width = mat2ppt.util.Emu(9144000);
prs.slide_height = mat2ppt.util.Emu(6858000);
blank = prs.slide_layouts().get_by_name("Blank");

%% ===== Slide 1 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(274638), mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(1143000));

% picture Picture 2
img = fullfile(assets, 'image1.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(1691640), mat2ppt.util.Emu(-1061992), mat2ppt.util.Emu(5715000), mat2ppt.util.Emu(9058182));
end


%% ===== Slide 2 =====
s = prs.slides().add_slide(blank);
sh = s.shapes();

% Title 1
sp = sh.add_shape('rect', mat2ppt.util.Emu(457200), mat2ppt.util.Emu(274638), mat2ppt.util.Emu(8229600), mat2ppt.util.Emu(1143000));

% picture Picture 2
img = fullfile(assets, 'image1.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(-2590800), mat2ppt.util.Emu(3276599), mat2ppt.util.Emu(5715000), mat2ppt.util.Emu(381000));
end

% picture Picture 2
img = fullfile(assets, 'image1.jpeg');
if isfile(img)
    sh.add_picture(img, mat2ppt.util.Emu(-195263), mat2ppt.util.Emu(1338264), mat2ppt.util.Emu(5715000), mat2ppt.util.Emu(4257673));
end


prs.save(outPath);
fprintf("Wrote %s\n", outPath);
